### PR TITLE
Add an ``'include-read'`` event

### LINKED ISSUE #11648: Documentation of source-read event: "docname" can be None
### Describe the bug

When including a file with the `include` directive, the `docname` argument can be `None` (since Sphinx 7.2).

The docs don't mention that: https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-source-read

### How to Reproduce

`conf.py`:

```python
def source_read(app, docname, source):
    print('#####')
    print('docname:', docname)


def setup(app):
    app.connect('source-read', source_read)
```

`index.rst`:

```rst
.. include:: another-file.txt
```

`another-file.txt`:

```
Some text.
```

Run this:

    python -m sphinx . _build

... and check the terminal output.

### Environment Information

```text
Platform:              linux; (Linux-6.4.0-1-amd64-x86_64-with-glibc2.37)
Python version:        3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        7.2.0
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

### Sphinx extensions

none, but this behavior is relevant for extensions that want to use the `source-read` event, like in my case https://github.com/mgeier/sphinx-last-updated-by-git

### Additional context

Maybe related: #11643

Possible work-around: https://github.com/mgeier/sphinx-last-updated-by-git/pull/59

### PR DESCRIPTION
**Pull request by AA-Turner**
closes #11648, #11643, #11620

cc: @mgeier @lmoureaux

The easy option would be to set the docname to ``self.env.docname`` (the current document being read), but this might throw off extensions that expect to only have ``"source-read"`` called exactly once per document.

Please test / let me know thoughts!

A

### CODE REVIEW

**Comment by AA-Turner** [comment]
I'm leaning towards the generated docname approach -- would appreciate your opinion @mgeier, as this solves the 'docname can be None' issue, but introduces docnames that don't work with ``doc2path()``.

A

**Comment by mgeier** [comment]
I think inventing a string (like `'include-from-mysource'`) is much worse than returning `None`.

If a string is returned, I would expect that string to be the document name.

I'm fine with returning `None`, but the documentation should be updated, as I mentioned in #11648.

**Comment by AA-Turner** [comment]
A good point -- I've also re-visited the original issue (https://github.com/sphinx-doc/sphinx/issues/10678) and have thusly changed my mind -- this PR now introduces a new ``'include-read'`` event, which no longer abuses the ``'source-read'`` event for non-documents.

I assume this would work for your purposes?

A

**Comment by mgeier** [comment]
That sounds much cleaner!

> I assume this would work for your purposes?

Yes, sure, an additional event will not break anything if I don't use it, right?

My extension `sphinx-last-updated-by-git` doesn't need an event for the `include` directive, it only needs to check the `env.dependencies` of every source file, which should contain the included files.

**Comment by mgeier** [comment]
I don't know if anyone needs this, but you could pass the parent document name to the event handler?

**Comment by AA-Turner** [comment]
Good shout!

**Comment by lucyleeow** [comment]
Thanks @AA-Turner, this is a good solution!

**Pull request merged**
