### PR TITLE
Make framing and captions of PDF literal code-blocks obey indentation

### PR DESCRIPTION
**Pull request by jfbu**
Thus, html and pdf look more similar.

### CODE REVIEW

**Comment by jfbu** [comment]
Here is a screen-shot from the Sphinx PDF documentation currently:

sans titre 2

and here is with the patch of this PR:

sans titre

**Comment by jfbu** [comment]
And for comparison a screen shot from the html version on the official site:
capture d ecran 2016-04-18 a 16 34 11

**Comment by jfbu** [comment]
One can notice that in the pdf output the top and bottom frame are a bit too close to the contents, but that's fixed as part of PR #2343 ;-)

**Comment by tk0miya** [comment]
I have nothing to say to this PR. It's very complicate for me.
But I prefer the new result.

Let's merge!

**Comment by jfbu** [comment]
rebased on current stable tip; updated CHANGES.

**Comment by jfbu** [comment]
@tk0miya it is indeed complicated as it relies on `framed.sty` code, which is not so much explained...

**Pull request merged**
