### PR TITLE
Add `aside.topic` for Docutils 0.18+

### PR DESCRIPTION
**Pull request by AA-Turner**
Found when rebuilding the Python documentation with Sphinx 5.

I'm not sure if this is worth a `5.0.1` release or not.

### Feature or Bugfix
- Bugfix

A

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
Thanks. It must be an important bug. So I'm merging this into the 5.0.x branch.

**Comment by mgeier** [comment]
This fix is still missing for Sphinx's own theme `sphinx13`.

https://github.com/sphinx-doc/sphinx/blob/af425c069f6f51ba8fb3c348fd53479f0434a779/doc/_themes/sphinx13/static/sphinx13.css#L375

I think this is a good example for how it is easy to miss fixes in the `sphinx13` theme. That's exactly why I suggested to move it to the rest of the built-in themes: #7733
Maybe this is worth reconsidering?

**Comment by AA-Turner** [comment]
@mgeier -- mea culpa, I searched within the `sphinx/themes` directory. #10521 is a fix for 5.0.2.

A

**Comment by mgeier** [comment]
I wouldn't say it's your fault, because the `sphinx13` theme is very easy to miss, that's why I suggested #7733, which would make such things harder to miss in the future.

**Pull request merged**
