### PR TITLE
Fix #10200: apidoc: Duplicated submodules are shown for modules

### LINKED ISSUE #10200: apidoc: Double entries for cython modules (both .pyx and .so found)
### Describe the bug

sphinx-apidoc adds both .pyx files and .so files to the generated .rst files. This causes duplication if both are in the same directory, or causes module lookup errors in sphinx-build if they are in different directories.

Support for .pyx was added in https://github.com/sphinx-doc/sphinx/issues/1117 and .so in https://github.com/sphinx-doc/sphinx/issues/2546

### How to Reproduce

```
python3 -m venv env
env/bin/pip install cython sphinx
mkdir mypackage
echo "# cython: language_level = 3" > mypackage/mymodule.pyx
cat > setup.py <<EOF
from setuptools import setup, Extension
setup(ext_modules=[Extension("mypackage.mymodule", sources=["mypackage/mymodule.pyx"])])
EOF
env/bin/python setup.py build_ext --inplace
env/bin/sphinx-apidoc --implicit-namespaces -fT mypackage -o doc/
cat doc/mypackage.rst
```
You will see mymodule listed twice:
```
mypackage namespace
===================

.. py:module:: mypackage

Submodules
----------

mypackage.mymodule module
-------------------------

.. automodule:: mypackage.mymodule
   :members:
   :undoc-members:
   :show-inheritance:

mypackage.mymodule module
-------------------------

.. automodule:: mypackage.mymodule
   :members:
   :undoc-members:
   :show-inheritance:
```

### Expected behavior

Expect mymodule to be listed once.

### Your project

reproducer is standalone

### Screenshots

_No response_

### OS

Linux

### Python version

3.8.10

### Sphinx version

4.4.0

### Sphinx extensions

_No response_

### Extra tools

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #10200

### CODE REVIEW

**Comment by AA-Turner** [comment]
Is it possible to add a test for this?

A

**Comment by tk0miya** [comment]
I don't have knowleged about cpython. So it's difficult to me. Could you help me?

**Comment by AA-Turner** [comment]
[Commit `bde47ce`](https://github.com/AA-Turner/sphinx/commit/bde47ce67957638712b23b5d249c085376dbf453) on my branch (https://github.com/AA-Turner/sphinx/tree/apidoc-duplicates) contains a basic test that could be cherrypicked into this branch.

A

**Comment by tk0miya** [comment]
Ah, I understand. Indeed, No knowledge of cython is needed to test this. Could you post your fix as a new PR, please? Then I'll merge it instead.

**Comment by AA-Turner** [comment]
Done, please see #10406

A

**Pull request closed without merging**
