### PR TITLE
Fix #2435: Slim down quickstarted conf.py

### LINKED ISSUE #2435: Slim down quickstarted conf.py
I don't think the `conf.py` as currently generated by `sphinx-quickstart` is useful:
- Lots of options are missing [2] because it's tiresome to keep the file updated.
- Most users don't bother to change the defaults [1] and thus bloat _every_ of their projects with our boilerplate.
- Finding the _significant_ changes is hard in the ocean of comments.

My ultimate goal is significantly reducing the size or our automatically generated configuration.  I, personally, would be fine with just removing all comments + commented out settings and maybe have more prominent links to the documentation.  I know some of us oppose this, but I'd like to start a discussion about _why_ exactly.

<br>

[1]  Most of these code search engines only cover larger projects, which I would guess are biased towards cleaner and more customized configurations.  I'd expect the actual ratios to be much higher, accounting for small projects which only ever look at their config once.

Also note I have used `texinfo_show_urls` as a proxy for commented out settings, since few people seem to bother actually using it.

| Search engine | corpus size | # hits | ratio |
| --- | --- | --- | --- |
| [Debian Code Search](codesearch.debian.net) | [1'442](https://codesearch.debian.net/results/project.%3D%20filetype%3Apython%20path%3A.*%2Fconf.py/page_0) | [567](https://codesearch.debian.net/results/%23.%3Ftexinfo_show%20filetype%3Apython%20path%3A.*%2Fconf.py/page_0) | 39% |
| [Krugle](opensearch.krugle.com) | [110](http://opensearch.krugle.org/document/search/#query=path%3Aconf.py) | [45](http://opensearch.krugle.org/document/search/#query=path%3Aconf.py%20%22%23add_module_names%22) | 41% |
| Github |  | [46'440](https://github.com/search?p=99&q=texinfo_show_urls&ref=searchresults&type=Code&utf8=%E2%9C%93) |  |

[2] A diff from `quickstart.py` to `conf.py`:

``` diff
+applehelp_bundle_id
+applehelp_bundle_name
+applehelp_bundle_version
+applehelp_codesign_flags
+applehelp_codesign_identity
+applehelp_codesign_path
+applehelp_dev_region
+applehelp_disable_external_tools
+applehelp_icon
+applehelp_index_anchors
+applehelp_indexer_path
+applehelp_kb_product
+applehelp_kb_url
+applehelp_locale
+applehelp_min_term_length
+applehelp_remote_url
+applehelp_stopwords
+applehelp_title
+copyright
+devhelp_basename
+epub_author
+epub_copyright
+epub_exclude_files
+epub_publisher
+epub_theme_options
+epub_title
+exclude_patterns
+figure_language_filename
+gettext_additional_targets
+gettext_auto_build
+gettext_compact
+gettext_location
+gettext_uuid
+highlight_language
+highlight_options
+html_add_permalinks
+html_compact_lists
+html_context
+html_copy_source
+htmlhelp_basename
+html_link_suffix
+html_output_encoding
+html_scaled_image_link
+html_secnumber_suffix
+html_static_path
+html_style
+html_theme
+html_translator_class
+html_use_modindex
+language
+latex_additional_files
+latex_docclass
+latex_documents
+latex_elements
+latex_font_size
+latex_paper_size
+latex_preamble
+latex_use_modindex
+linkcheck_anchors
+linkcheck_ignore
+linkcheck_retries
+linkcheck_timeout
+linkcheck_workers
+locale_dirs
+man_pages
+master_doc
+needs_extensions
+nitpick_ignore
+nitpicky
+numfig
+numfig_format
+numfig_secnum_depth
+primary_domain
+project
+pygments_style
+qthelp_basename
+release
+rst_epilog
+rst_prolog
+source_parsers
+source_suffix
+template_bridge
+templates_path
+texinfo_documents
+texinfo_elements
+text_newlines
+text_sectionchars
+trim_doctest_flags
+trim_footnote_reference_space
+version
+xml_pretty
```

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #2435 
I removed almost of commented-out config variables.

### CODE REVIEW

**Comment by shimizukawa** [comment]
LGTM with nits.

I think it would be better if "full version of conf.py" sample is pasted in the configuration page of the sphinx documentation ( http://www.sphinx-doc.org/en/stable/config.html ). If the sample is there, we can remove more comment-outed parts of conf.py.

**Comment by tk0miya** [comment]
@shimizukawa AFAIK, there is no "full version of conf.py". At this moment, Sphinx only generates imcomplete version of conf.py.
Did you mean that we should paste current version of conf.py to docs?

**Comment by shimizukawa** [comment]
> Did you mean that we should paste current version of conf.py to docs?

Yes.

**Comment by tk0miya** [comment]
I just added conf.py as example.

**Comment by shimizukawa** [comment]
LGTM!

2016年10月11日(火) 20:10 Takeshi KOMIYA notifications@github.com:

**Comment by tk0miya** [comment]
Merged!

**Comment by shimizukawa** [comment]
GJ!

**Pull request merged**
