### PR TITLE
Fix #7588: autosummary: allow any template suffix

### LINKED ISSUE #7588: pyplot disappears with latest master
**Describe the bug**
My pyplots graphs are not shown anymore with recent master around end of april (v3.0.3 is good, or master from 10 april), bisecting points to #7548

**To Reproduce**
I created a small testcase at https://github.com/jschueller/sphinx-pyplot-test:
```
$ git clone https://github.com/jschueller/sphinx-pyplot-test.git
$ cd sphinx-pyplot-test
$ pip install sphinx matplotlib
$ ./build.sh
```

**Expected behavior**
The pyplot graph should appear.

**Your project**
www.OpenTURNS.org

**Screenshots**
with sphinx master 10/4/20 OK: http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.GumbelCopula.html
with sphinx master end of april BAD: http://openturns.github.io/openturns/master/user_manual/_generated/openturns.GumbelCopula.html

**Environment info**
- OS: Linux
- Python version: 3.8.2
- Sphinx version: master
- Sphinx extensions:  autodoc, autosummary, matplotlib.sphinxext.plot_directive

**Additional context**
I bisected between v3.0.3 and HEAD and saw that it stems from #7548:
```
e5192ba48b45576e636e7dce82ad9183051443ed is the first bad commit
commit e5192ba48b45576e636e7dce82ad9183051443ed
Author: Takeshi KOMIYA <i.tkomiya@gmail.com>
Date:   Sat Apr 25 01:25:00 2020 +0900

    refactor: AutosummaryRender
```

but I noticed there are more commits related to this: #7570

cc @tk0miya

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #7588

### CODE REVIEW

**Comment by jschueller** [comment]
what was the allowed template suffix ?

**Review by jschueller — APPROVED** [review]
This resolves my issue, thanks again.

**Comment by tk0miya** [comment]
>what was the allowed template suffix ?

All suffixes should be allowed. My fix at #7578 supposes template suffix is `.rst` wrongly.

**Comment by tk0miya** [comment]
Thank you for confirming. I'll merge this into the master branch soon.

**Pull request merged**
