### PR TITLE
Add a l10nfigures extension to ease translation of figures.

### PR DESCRIPTION
**Pull request by benallard**
As discussed in the issue #1235, I wrote that small extension, I would be glad to see it included upstream !

As this is my first contribution to sphinx, don't hesitate to point some improvements to me !

### CODE REVIEW

**Comment by birkenfeld** [comment]
The basic idea looks good to me. @shimizukawa @tk0miya anyone want to do a more detailed review? I'm not entirely up to date with the i18n story nowadays.

**Comment by shimizukawa** [comment]
OK, I'll take a look.

**Comment by tk0miya** [comment]
LGTM!
I want to merge this idea into Sphinx core (not as an extension).
I believe Sphinx should provide I18N basic feature for images and figures like this.
It would be very nice if the third party extensions follow this feature.

**Comment by tk0miya** [comment]
I'm ready to help improving the pull request, of course :-)

**Comment by lehmannro** [comment]
I agree adding this functionality to core `figure` is useful, the current implementation is very brittle though:  parsing the source again leads to all sorts of undetected error cases (which you cannot sensibly catch with a regex), eg. `.. raw::\n .. figure::`.

Image nodes are currently processed in `Builder.post_process_images` (for `filename.*` support.)  I'm not sure if this wouldn't be cleaner as a Transform.

**Comment by birkenfeld** [comment]
Agreed with both, this is probably good in core and should have a different impl.

**Comment by benallard** [comment]
Great ! Thanks for considering this !

I agree on the fact that the regex + source manipulation is not the most elegant way to do that.

How are we proceeding ?

**Comment by shimizukawa** [comment]
@benallard if you have a chance, please develop sphinx-core version of the feature ;) Even you can't, we (I?) will develop before very long.

**Comment by tk0miya** [comment]
Now, I'm implementing this on my repository:
https://github.com/sphinx-doc/sphinx/compare/master...tk0miya:1921_figure_substitutions

I'll create pull request for reviewing within a week.
(A little while ago, I attempted to create it, but I'd forgotten the globbing `filename.*` feature...)

If you have any comments for my changes, please let me know.

**Comment by benallard** [comment]
Looks good, one remark though, I had actually tried the "name.lang.ext" format before I move to the "name-lang.ext", if I remember correctly latex had issues figuring out the format/extension of the file if you have dots in its name.

**Comment by lehmannro** [comment]
If we're looking at <tt>name.<em>language</em>.ext</tt>, we should also try to find <tt>name.en.ext</tt> so that the base language is not necessarily a special case.

Also, I can imagine lots of people would want to have this a little bit more tidy (eg., store POs and translated figures in the same directory instead of manging the filename.)  Could we make this a configuration value? (I think configuring the `%s.%s%s` part might already do a good enough job.)

**Comment by shimizukawa** [comment]
+1 for configuration.

(Some users want to use their naming rule as like as "apache language negotiation", or some other users want to use other naming rule...)

**Comment by tk0miya** [comment]
Thank you for comments!

> Looks good, one remark though, I had actually tried the "name.lang.ext" format before I move to the "name-lang.ext", if I remember correctly latex had issues figuring out the format/extension of the file if you have dots in its name.

This is fixed at #2182 . So we have no problem for this.

> If we're looking at name.language.ext, we should also try to find name.en.ext so that the base language is not necessarily a special case.

I feel this behavior is a bit strange. Why not fallback to original image file simply?
Other i18n feature behaves like that?

> Also, I can imagine lots of people would want to have this a little bit more tidy (eg., store POs and translated figures in the same directory instead of manging the filename.) Could we make this a configuration value? (I think configuring the %s.%s%s part might already do a good enough job.)

I see. I'll add it.
Do you have any good name for this config value?

Thanks,

**Comment by tk0miya** [comment]
Thank you for waiting.
I create pull request #2276 to improve this one.
Could you review this please?

**Pull request closed without merging**
