### PR TITLE
Use Ruff's ``extend-exclude``

### PR DESCRIPTION
**Pull request by danieleades**
ruff's docs list 'extend exclude' as the preferred option.
that reduces the boilerplate, and allows the config to only list the *differences* from standard python config

### CODE REVIEW

**Comment by danieleades** [comment]
now that's interesting, the `[lint]` block doesn't support the `extend-exclude` config, but the top level does.
That doesn't matter for sphinx right now, but *if* sphinx were to use ruff for formatting, and wanted to use ruff to format those files but *not* lint them, this would have to be reverted

**Comment by AA-Turner** [comment]
> now that's interesting, the `[lint]` block doesn't support the `extend-exclude` config, but the top level does.
> 
> That doesn't matter for sphinx right now, but *if* sphinx were to use ruff for formatting, and wanted to use ruff to format those files but *not* lint them, this would have to be reverted

Should we report this upstream?

**Comment by danieleades** [comment]
> Member

we could. it might also be deliberate. If you have a top-level extend exclude and then child extend excludes, then suddenly you need some kind of inheritance strategy. or rules about only having one or the other

**Comment by picnixz** [comment]
>  That doesn't matter for sphinx right now, but if sphinx were to use ruff for formatting, and wanted to use ruff to format those files but not lint them, this would have to be reverted

Is there a way for enable the formatter and disable the linter using a top-level comment ?

**Pull request merged**
