### PR TITLE
Improve codecov integration

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/sphinx-doc/sphinx/issues/7279 - let's discuss/decide it there.

### CODE REVIEW

**Comment by tk0miya** [comment]
Hmm... after merging this, pytest-cov raise an exception. @blueyed do you know what happened?
```
coverage.misc.CoverageException: Can't combine arc data with line data
```

**Comment by blueyed** [comment]
@tk0miya 
> Hmm... after merging this, pytest-cov raise an exception.

> ```
> coverage.misc.CoverageException: Can't combine arc data with line data
> ```

Should not be related to codecov, but rather the pytest unpinning (if not "flaky").

This typically happens when coverage runs with and without branch=1, and this then is being tried to be combined.  It can happen e.g. when a subprocess does not use the config with branch=1.

Is it happening constantly now?

btw: I'm also in the IRC channel, if you are using that.

**Comment by tk0miya** [comment]
No, it seems unrelated. because unpinning was merged into 3.x branch. But the error was happened on 2.4.x branch.
The same error was also raised in 3.x branch. But this change is not merged into 3.x branch yet. So I guess these errors happened unrelated with these PRs.
https://travis-ci.org/sphinx-doc/sphinx/jobs/660199606

**Comment by tk0miya** [comment]
Sorry for posting a comment in the middle. I've not used IRC.

**Comment by tk0miya** [comment]
>Is it happening constantly now?

I restarted the failed CI manually twice, but all tries were failed with the same error. I'm going to stop sending coverage data temporarily to recover our CI.

**Comment by tk0miya** [comment]
For now, CI is recovered with stopping coverage. It would be better if we can investigate why the error has happened.
Thanks,

**Pull request merged**
