### PR TITLE
Drop deprecated features (partially)

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #3237

### CODE REVIEW

**Comment by tk0miya** [comment]
This does not include following code-drop:

* `latex_elements['footer']`
* `RemovedInSphinx16Warning`
* `sphinx.util.compat:make_admonition`
* `sphinx.util.pycompat`

This will be removed in another PR.

@shimizukawa Do you have comment?

**Comment by shimizukawa** [comment]
LGTM!

In addition, we must have `Feature removed in 1.6` section in CHANGES like Django's one: https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10

**Comment by tk0miya** [comment]
Thank you for reviewing.
Just added "Features removed" section.

**Comment by shimizukawa** [comment]
LGTM!

**Comment by tk0miya** [comment]
@shimizukawa Thank you for reviewing.
I'll merge this after Travis says OK (I just resolved conflicts).

**Comment by shimizukawa** [comment]
🎉

**Pull request merged**
