### PR TITLE
C, C++: fundamental type parsing

### LINKED ISSUE #9917: C and C++, simple type specifiers should be allowed in any order
### Describe the bug

In C and C++ all of the following types are valid and the same:
- ``unsigned long int``
- ``unsigned int long``
- ``long unsigned int``
- ``long int unsigned``
- ``int unsigned long``
- ``int long unsigned``
The same goes for all other simple type specifier sequences.

Since #9547 only those on the form <modifier> <signedness> <width> <type> were accepted.

### How to Reproduce

Have a declaration with a type not on the form above.

### Expected behavior

_No response_

### Your project

N/A

### Screenshots

_No response_

### OS

Any

### Python version

Any

### Sphinx version

>= 4.2.0

### Sphinx extensions

_No response_

### Extra tools

_No response_

### Additional context

Discovered via https://github.com/michaeljones/breathe/issues/771

### PR DESCRIPTION
**Pull request by jakobandersen**
### Feature or Bugfix
- Bugfix

### Purpose
Fixes #9917 and https://github.com/michaeljones/breathe/issues/771.

Note primarily for @tk0miya: I put this in 4.3.x so it could go out immediately, and it indeed causes a crash in Breathe (because it messes with C++ internals) if users have the "wrong" order in non-type template parameters.

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Okay, I'll release a new package after this PR merged.

**Comment by jakobandersen** [comment]
@marxin, do you by chance have time to double check with the GCC docs that this didn't break anything? or do you have instructions for how I compile them in the current state?

**Comment by jakobandersen** [comment]
> Okay, I'll release a new package after this PR merged.

@tk0miya, please go ahead with a release as it fits in your schedule. I'll just rebase this if it doesn't make it in time.

**Comment by marxin** [comment]
> @marxin, do you by chance have time to double check with the GCC docs that this didn't break anything? or do you have instructions for how I compile them in the current state?

Please try that yourself:

```
git clone https://github.com/marxin/texi2rst-generated
cd texi2rst-generated/sphinx
make html
```

**Comment by jakobandersen** [comment]
> Please try that yourself:

Thanks! No breakages found. Merging.

**Pull request merged**
