### PR TITLE
Fix #3638: Allow to change a label of reference to equation

### LINKED ISSUE #3638: Reference equation with added "Equation"
When using `:eq:` to reference an equation, the LaTeX output generated by `\eqref` puts the equation number between parentheses, which looks like "(3.1)".

It would be nice if there was a way to have Sphinx output something like "Equation 3.1". This would be similar to what `:numref:` does (e.g. "Section 2.4", "Table 12"). The `numfig_format` config option could be used to set a (translated) label.

The only workaround I see know is to [override the eqref command](https://tex.stackexchange.com/questions/28894/modify-eqref-command), but that is not so user friendly

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #3638

### CODE REVIEW

**Comment by jessetan** [comment]
Two questions:

1. Why does this use `{number}` as a placeholder for the equation number, rather than `%s` as used by `numfig_format`?
2. Why is this a separate config option instead of another entry in `numfig_format`?

**Comment by tk0miya** [comment]
>Why does this use {number} as a placeholder for the equation number, rather than %s as used by numfig_format?

At present, `numfig_format` allows to use `{number}` and `{name}` as format string. So this imitates the its rule.

>Why is this a separate config option instead of another entry in numfig_format?

`numfig_format` is used only for `numref` role. I think it is not good for this case.

**Comment by jessetan** [comment]
> numfig_format is used only for numref role. I think it is not good for this case.

Can numref be extended to support equations? Currently we can use numref for all references except equations.

**Comment by tk0miya** [comment]
Agreed, it would be nice, but it is hard to support now. At present, `numref` role can't support the objects outside of std domain.

**Pull request merged**
