### PR TITLE
Fix #4137: doctest: doctest block is always highlighted as python con…

### LINKED ISSUE #4137: [sphinx.ext.doctest] set language for doctest blocks
It would be nice to have the language of `doctest` blocks set to Python.
It matters in documents that have `highlight_language` set to something else (in my case c++).
I think in such cases it's currently necessary is to use the `highlight` directive before (and after) doctests.

It's not very convenient, so I monkey-patched it in my conf.py:
```py
import sphinx.ext.doctest
def DoctestDirective_run(self):
    nodes = sphinx.ext.doctest.TestDirective.run(self)
    nodes[0]['language'] = 'pycon'
    return nodes
sphinx.ext.doctest.DoctestDirective.run = DoctestDirective_run
```

but it'd be more elegant to have it in [ext/doctest.py][1], maybe next to these lines:

        if self.name == 'testoutput':
            # don't try to highlight output
            node['language'] = 'none'

[1]: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/doctest.py#L123

### PR DESCRIPTION
**Pull request by tk0miya**
…sole (pycon)

Fix #4137

### CODE REVIEW

**Comment by wojdyr** [comment]
Thanks for looking into it.

I think the condition will also catch `testcode` in addition to `doctest`, so perhaps the language would be better set to python than pycon? I don't know how exactly the pygments lexers work.

Another thing that comes to my mind is that perhaps in some cases one would prefer to use one of the other "python-related languages" supported by pygments:
http://pygments.org/docs/lexers/#lexers-for-python-and-related-languages

**Comment by peterjc** [comment]
So would you put:

```
    if self.name in ('testoutput', 'testcode'):
```

Would it makes sense to use ``pycon`` by default only if the text contains any line starting ``>>> ``?

**Comment by tk0miya** [comment]
Now I arrange the conditions. And I will merge this after testing passed.
Please let me know if something wrong. I'll fix it again.
(Sorry for skipping reviewing. I'd like to merge this into 1.7b1 release)

**Comment by tk0miya** [comment]
Merged. Thank you for reviewing :-)

**Pull request merged**
