### PR TITLE
Fix #4531: autosummary: methods are treated as attributes

### LINKED ISSUE #4531: API doc pages generation with autosummary broken for pandas with 1.7b
### Problem

The API pages in the pandas documentation that are generated by `autosummary` pages are no longer building correctly

The reason seems to be that in the docstring pages generated by autosummary, all occurences of `.. automethod:: Series.abs` are changed in `.. autodata:: abs`, which then fails to fetch the docstrings, resulting in empty pages. 

See also https://github.com/sphinx-doc/sphinx/issues/4230#issuecomment-361649509

#### Procedure to reproduce the problem

I made a test repo with a small subset of our docs: https://github.com/jorisvandenbossche/pandas-test-docs. This should be easier to test out.

#### Error logs / results

So trying to look through the log output of sphinx 1.7. 
I see the following (when reading the source of generated/pandas.Series):

```
[autodoc] from pandas import Series.abs
[autodoc] => <module 'pandas' from '/home/joris/miniconda3/envs/sphinx-test/lib/python3.6/site-packages/pandas/__init__.py'>
[autodoc] getattr(_, 'Series')
[autodoc] => <class 'pandas.core.series.Series'>
[autodoc] getattr(_, 'abs')
[autodoc] => <function NDFrame.abs at 0x7fa3d669e598>
[app] emitting event: 'autodoc-process-docstring'('method', 'pandas.Series.abs', <function NDFrame.abs at 0x7fa3d669e598>, {}, ['Return an object wit
```

It clearly mentions 'method' in that last line, but, it writes a file with `autodata`, resulting in an error in the next step when reading the generated (in the above step) file 'generated/pandas.Series.abs':

```
reading sources... [  1%] generated/pandas.Series.abs
[app] emitting event: 'env-purge-doc'(<sphinx.environment.BuildEnvironment object at 0x7fa3c796c160>, 'generated/pandas.Series.abs')
[app] emitting event: 'source-read'('generated/pandas.Series.abs', ['pandas.Series.abs\n=================\n\n.. currentmodule:: pandas.
[autodoc] /home/joris/scipy/pandas-test-docs/source/generated/pandas.Series.abs.rst:6: input:
.. autodata:: abs
[autodoc] from pandas.Series import abs
autodoc: failed to import data 'abs' from module 'pandas.Series'; the following exception was raised:
No module named 'pandas.Series'
[app] emitting event: 'doctree-read'(<document: <section "pandas.series.abs"...>>,)
```

---

As a comparison, the equivalent bits of the log file for sphinx 1.5.6:

```
[autodoc] from pandas import Series.abs
[autodoc] import pandas
[autodoc] => <module 'pandas' from '/home/joris/miniconda3/envs/sphinx-test/lib/python3.6/site-packages/pandas/__init__.py'>
[autodoc] getattr(_, 'Series')
[autodoc] => <class 'pandas.core.series.Series'>
[autodoc] getattr(_, 'abs')
[autodoc] => <function NDFrame.abs at 0x7f1a4ab169d8>
[app] emitting event: 'autodoc-process-signature'('method', 'pandas.Series.abs', <function NDFrame.abs at 0x7f1a4ab169d8>, {}, '()', None)
[app] emitting event: 'autodoc-process-docstring'('method', 'pandas.Series.abs', <function NDFrame.abs at 0x7f1a4ab169d8>, {}, ['Return an object wit
[app] emitting event: 'autodoc-process-docstring'('method', 'pandas.Series.abs', <function NDFrame.abs at 0x7f1a4ab169d8>, {}, ['', 'Return an object
```

```
reading sources... [  1%] generated/pandas.Series.abs
[app] emitting event: 'env-purge-doc'(<sphinx.environment.BuildEnvironment object at 0x7f1a3d415d30>, 'generated/pandas.Series.abs')
[app] emitting event: 'source-read'('generated/pandas.Series.abs', ['pandas\\.Series\\.abs\n===================\n\n.. currentmodule:: p
[autodoc] /home/joris/scipy/pandas-test-docs/source/generated/pandas.Series.abs.rst:6: input:
.. automethod:: Series.abs
[autodoc] from pandas import Series.abs
[autodoc] import pandas
[autodoc] => <module 'pandas' from '/home/joris/miniconda3/envs/sphinx-test/lib/python3.6/site-packages/pandas/__init__.py'>
[autodoc] getattr(_, 'Series')
[autodoc] => <class 'pandas.core.series.Series'>
[autodoc] getattr(_, 'abs')
[autodoc] => <function NDFrame.abs at 0x7f1a4ab169d8>
[app] emitting event: 'autodoc-process-signature'('method', 'pandas.Series.abs', <function NDFrame.abs at 0x7f1a4ab169d8>, {}, '()', None)
[app] emitting event: 'autodoc-process-docstring'('method', 'pandas.Series.abs', <function NDFrame.abs at 0x7f1a4ab169d8>, {}, ['Return an object wit
[autodoc] output:

.. py:method:: Series.abs()
   :module: pandas

[... docstring]
   ..
       !! processed by numpydoc !!
[app] emitting event: 'doctree-read'(<document: <section "pandas.series.abs"...>>,)
```

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #4531

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Tested it out, and the methods are now correctly included. Thanks! 
However, I noticed that the attribute pages are not yet generated .. But it's possible that that is actually a separate issue, as this was already a problem with the 1.7b1 as well (I just didn't notice it then because also all methods were not built correctly)

**Comment by jorisvandenbossche** [comment]
Sorry for the noise. That was because I added the patch to the branch of https://github.com/sphinx-doc/sphinx/pull/4523 (the fix for the slowdown), and that branch was a bit behind the master 1.7-release branch, and the PR (my own :-)) to fix the attributes listing problem was not yet in there... 
If I now try this properly, it works fine!

**Comment by tk0miya** [comment]
@jorisvandenbossche thank you for confirmation.
Now I merged this :-)

**Comment by jorisvandenbossche** [comment]
And thanks for fixing this!

**Pull request merged**
