### PR TITLE
Ensure submodules are unique in `sphinx.ext.apidoc`

### LINKED ISSUE #10200: apidoc: Double entries for cython modules (both .pyx and .so found)
### Describe the bug

sphinx-apidoc adds both .pyx files and .so files to the generated .rst files. This causes duplication if both are in the same directory, or causes module lookup errors in sphinx-build if they are in different directories.

Support for .pyx was added in https://github.com/sphinx-doc/sphinx/issues/1117 and .so in https://github.com/sphinx-doc/sphinx/issues/2546

### How to Reproduce

```
python3 -m venv env
env/bin/pip install cython sphinx
mkdir mypackage
echo "# cython: language_level = 3" > mypackage/mymodule.pyx
cat > setup.py <<EOF
from setuptools import setup, Extension
setup(ext_modules=[Extension("mypackage.mymodule", sources=["mypackage/mymodule.pyx"])])
EOF
env/bin/python setup.py build_ext --inplace
env/bin/sphinx-apidoc --implicit-namespaces -fT mypackage -o doc/
cat doc/mypackage.rst
```
You will see mymodule listed twice:
```
mypackage namespace
===================

.. py:module:: mypackage

Submodules
----------

mypackage.mymodule module
-------------------------

.. automodule:: mypackage.mymodule
   :members:
   :undoc-members:
   :show-inheritance:

mypackage.mymodule module
-------------------------

.. automodule:: mypackage.mymodule
   :members:
   :undoc-members:
   :show-inheritance:
```

### Expected behavior

Expect mymodule to be listed once.

### Your project

reproducer is standalone

### Screenshots

_No response_

### OS

Linux

### Python version

3.8.10

### Sphinx version

4.4.0

### Sphinx extensions

_No response_

### Extra tools

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AA-Turner**
Follows on from #10402
Closes #10200

A

### Feature or Bugfix
- Bugfix

### CODE REVIEW

**Comment by AA-Turner** [comment]
By the way @tk0miya, do you know if there is a process for granting triage permissions / etc? That way I would be able to apply labels and milestones to these PRs (and others) myself -- it saves you some work!

A

**Review by tk0miya — APPROVED** [review]
Thank you for your work!

**Comment by tk0miya** [comment]
>By the way @tk0miya, do you know if there is a process for granting triage permissions / etc? 

Thank you for your proposal. It must be helpful for us. Unfortunately, we don't have a proper rule to add maintainers and contributors. But I sometimes posted issues on inviting new maintainers so far: https://github.com/sphinx-doc/sphinx/issues?q=is%3Aissue+invite+new+maintainer.

**Comment by AA-Turner** [comment]
Thanks for the context @tk0miya -- I'm one of the current PEP editors for Python so I've got somewhat of an interest in making sure Sphinx works & we've spoken on the Docutils tracker too, so very happy to help out as a maintainer if you'd like -- equally no worries if there are enough team members currently!

Thanks for your help reviewing my PRs, it is great to help out.

A

**Pull request merged**
