### PR TITLE
Update install docs

### PR DESCRIPTION
**Pull request by kurtmckee**
This updates the Windows install documentation in these ways:

* The instructions for installing pip are no longer relevant and have been removed.
* The instructions for modifying the PATH are no longer relevant and have been removed.
* The final section, "Installing Sphinx with pip", is now a subsection of the Windows install instructions.
*  The verb tense of the final section has been modified to match the rest of the headers.
* The command line examples have been converted to use the Pygments text lexer instead of the batch lexer, which highlights everything after `C:\>` incorrectly, presumably because `>` is a STDOUT redirect in batch files.
* The Python website screenshot has been updated.
* The Python installer screenshot has been updated to highlight the PATH modification option.

In addition, the MacPorts URL has been changed to use HTTPS.

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
LGTM!

**Comment by kurtmckee** [comment]
Quick question, should I update AUTHORS or is that more appropriate only for larger feature authors and ongoing maintainers?

**Comment by tk0miya** [comment]
Please add your name to the AUTHORS list :-)

**Comment by kurtmckee** [comment]
I think it got added in another pull request. =)

**Comment by tk0miya** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
