### PR TITLE
Fix #6815: i18n: some translation messages has been broken

### LINKED ISSUE #6815: Sphinx's Korean translation breaks every build when checking the default value's type of configuration.
**Describe the bug**
- [Sphinx's Korean translation](https://github.com/sphinx-doc/sphinx/blob/34acdc37aaa7a07bbd3792cf8836eca2e42d1cdd/sphinx/locale/ko/LC_MESSAGES/sphinx.po#L235-L239) breaks every build with `latex_show_urls = True` in configuration.
- When [Sphinx check the type between the default value's and user-setting value's](https://github.com/sphinx-doc/sphinx/blob/34acdc37aaa7a07bbd3792cf8836eca2e42d1cdd/sphinx/config.py#L477-L482), problem occured.
    - `ValueError: Single '}' encountered in format string`

**To Reproduce**
```sh
$ git clone https://github.com/sphinx-doc/sphinx
$ cd sphinx
$ pip install Sphinx==2.2.1
$ sed -i "s/latex_show_urls = 'footnote'/latex_show_urls = True/" doc/conf.py
$ LANG=ko_KR.UTF-8 make docs target=html
$ # Error! 
```

But `LANG=en_US.UTF-8` and `LANG=C` worked well.

**Expected behavior**
Generate html well without error.

**Your project**
- Added the reproducible code above.

**Screenshots**
```pytb
Sphinx 버전 2.2.1 실행 중
Traceback (most recent call last):
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/application.py", line 260, in __init__
    self.events.emit('config-inited', self.config)
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/config.py", line 483, in check_confval_types
    default=type(default)))
ValueError: Single '}' encountered in format string

Exception occurred:
  File "/Users/minhoryang/.anyenv/envs/pyenv/versions/3.7.4-konlpy/lib/python3.7/site-packages/sphinx/config.py", line 483, in check_confval_types
    default=type(default)))
ValueError: Single '}' encountered in format string
The full traceback has been saved in /var/folders/2z/s0qpljwj7hd60f2pm1s2f7mw0000gn/T/sphinx-err-ntins5z2.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Environment info**
- OS: macOS 10.15.1 
- Python version: 3.8.0
- Sphinx version: 2.2.1

**Additional context**
- [`latex_show_urls` can be `True` with "backwards compatibility"-help](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_show_urls)

- Problem lives here:
    https://github.com/sphinx-doc/sphinx/blob/34acdc37aaa7a07bbd3792cf8836eca2e42d1cdd/sphinx/locale/ko/LC_MESSAGES/sphinx.po#L235-L239

- Blamed: https://github.com/sphinx-doc/sphinx/commit/e02af7f9600e967660ff1ab6b0a721f159703dea (>= 2.0.0)

- My transifex username: https://www.transifex.com/user/profile/minhoryang/

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #6815 
- To apply fixed translations, this fetches newest translations from transifex.

### CODE REVIEW

**Comment by jfbu** [comment]
I wonder if fetching all translations (a priori destined for master branch) into 2.2.2 can cause problems, the `sphinx.pot` is not same a priori?

**Review by jfbu — APPROVED** [review]
LGTM with one question: here we fetch all transifex translations. The `sphinx.pot` file correspond to which branch at Sphinx? is it the one from last major release `2.0.0`?

I am glad to see in particular French translations updated earlier than next major release because I had to fix quite a few of them at transifex in recent months.

**Comment by tk0miya** [comment]
The message catalog on transifex.com correspond to last major release. In this time, it is 2.2.0.
In our release manual, uploading new message catalog will be going on first beta release (of major release).
https://github.com/sphinx-doc/sphinx/blob/c2d64a9b0a7ef1fbd56c620d292e067ded462200/utils/release-checklist#L36

So next update of message catalog will be held on 2.3.0b1 release.

**Comment by tk0miya** [comment]
Merged. Thank you for quick reviewing!

**Comment by jfbu** [comment]
Thanks for clarification! I understand much better now when transifex Sphinx catalog gets updated. Indeed, I keep getting confused about our major/minor model, so it was not clear to me `2.2.0` counted as "major".

**Comment by tk0miya** [comment]
>Indeed, I keep getting confused about our major/minor model, so it was not clear to me 2.2.0 counted as "major".

Ah, sorry. You're right. My wording is wrong. What I meant is **MINOR** release. And I have to update release checklist to follow new release model.

**Pull request merged**
