### PR TITLE
Refactor latex into multiple files

### PR DESCRIPTION
**Pull request by jfbu**
### Feature or Bugfix
- Refactoring

### Purpose
Make replacement of big chunks of Sphinx LaTeX code in one go possible, especially for customizing macros, via addition of a file from `latex_additional_ files` rather than bloated conf.py.

There does not exist in the LaTeX world anything even remotely like CSS styling in HTML.

But splitting big file into smaller units makes replacement of smaller unit possible. Actually things are really intertwined with LaTeX builder (influencing preamble contents) and LaTeX writer which outputs the mark-up, and the actual LaTeX code fragments. But for some things, for example customization of headings (now in `sphinxlatexstyleheadings.sty`) it is easier to replace the whole file with the needed changes than to add many things to ``latex_elements``.

For time being I simply split the sphinx.sty along predefined sections which had been structured on some previous refactoring. Arguably one should now move the `\RequirePackage{titlesec}` and associated bugfix from `sphinxlatexrequirepacakages.sty` to `sphinxlatexstyleheadings.sty`, only to give an example, I am not sure there are many which are as clearcut.

Also take this opportunity to adopt some uniform naming convention for LaTeX support files.

(merging 3.x will need I guess some manual intervention in `\ProvidesPackage` of `sphinxpackagefootnote` which is new name of `footnotehyper-sphinx`)

### Relates
- #8045

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
Reasonable. It sounds great!

**Comment by tk0miya** [comment]
>(merging 3.x will need I guess some manual intervention in \ProvidesPackage of sphinxpackagefootnote which is new name of footnotehyper-sphinx)

I'm going to merge 3.x into master now. Please wait a minute.

**Review by jfbu — COMMENTED** [review]
Regarding file `sphinxpackagemulticell.sty` it should probably be simply `sphinxlatexmulticell.sty`. As it does not have to handle options. 

`sphinxpackagecyrillic` may have to handle an option, and `sphinxpackagefootnote` is an adaptation of real live package `footnotehyper`. 

Also I don't know if the filename changes should make it into CHANGES. Those things are internal to Sphinx, I doubt people fiddled with `sphinxcyrillic` or  `sphinxmulticell` , ever.

**Comment by tk0miya** [comment]
Oops. Conflicted.

**Comment by tk0miya** [comment]
>Also I don't know if the filename changes should make it into CHANGES. Those things are internal to Sphinx, I doubt people fiddled with sphinxcyrillic or sphinxmulticell , ever.

I think it's okay to mention only about the separation of sphinx.sty in CHANGES.

**Comment by jfbu** [comment]
> > Also I don't know if the filename changes should make it into CHANGES. Those things are internal to Sphinx, I doubt people fiddled with sphinxcyrillic or sphinxmulticell , ever.
> 
> I think it's okay to mention only about the separation of sphinx.sty in CHANGES.

OK, done. Can you check if OK? And I resolved conflicts.

**Comment by tk0miya** [comment]
I'm okay to merge this for 4.0. But it seems Circle CI failed with unknown errors.

>stdout = b"This is LuaTeX, Version 1.0.4 (TeX Live 2017/Debian) \n restricted system commands enabled.\n(./lualatex/sphinxtests...3,4:1,5:1,7:5,8:3\n!  ==> Fatal error occurred, no output PDF file produced!\nTranscript written on sphinxtests.log.\n"

**Comment by jfbu** [comment]
OK I will check the CI. I was looking for 5mns at CI loading icon until I remembered my JavaScript is unactivate in my browser :)

I am thinking of adding a commit which moves all the table-related stuff away from `sphinxlatexrequirepackages.sty` into a file `sphinxlatextables.sty` which will also incorporate entirely the `sphinxpackagemulticell`. Indeed Sphinx really requires tabulary and longtable and all the macros from `sphinxpackagemulticell` it is only one unit.

**Comment by jfbu** [comment]
I had badly resolved conflicts in the merge, leaving an extra bracket breaking latex builds :( my bad. Fixed.

**Comment by tk0miya** [comment]
Go ahead!

**Comment by jfbu** [comment]
Thanks for review, now merging! I will make next a PR relative to putting all table cell related code in one place. It is so intricate that no separate customization is really possible, and it is intertwined with the latex templates for tables.

**Pull request merged**
