### PR TITLE
Add %O% option to make.bat template; update docs

### LINKED ISSUE #6323: Add pass-through of sphinx-build CLI arguments to make.bat.new_t
**Is your feature request related to a problem? Please describe.**

It's frustrating not being able to pass extra arguments to `make.bat` that then get provided to `sphinx-build`. E.g., `> make html -Ean` is not feasible.  (This is a subset of #3741.)

**Describe the solution you'd like**

I'd like this capability to be added to Sphinx.  I already have an implementation in [my fork](https://github.com/bskinn/sphinx/commit/1295ae861cd109089206e3e37ba5973d7fa1f714).

**Describe alternatives you've considered**

#3841 attempted a more-ambitious implementation, but was rejected due to likely too-great maintenance requirements.  It looks like the whole makefile/make.bat setup will be obsoleted by #5618; but this seems like a simple enhancement to implement in the meantime.

**Additional context**

Screencap of implemented feature in action:

image

### PR DESCRIPTION
**Pull request by bskinn**
### Subject
Add `%O%` option to make.bat templates.

### Feature or Bugfix

- Feature

### Detail
The `make.bat_t` and `make.bat.new_t` templates now pass `%O%` as well as
`%SPHINXOPTS%` to `sphinx-build`, in parity with `Makefile.new_t`.

The `sphinx-build` documentation page was updated to explicitly note
`$(O)` and `%O%` as shortcut variables.

Closes #6323, per the comment thread discussion there.

### Purpose
- No dependent environment; only affects new documentation source trees created on Windows with `sphinx-quickstart`

### Relates
- #6323

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
Could you add it to `make.bat_t` also? It is still available.

**Comment by bskinn** [comment]
@tk0miya Sure! commit is revised.

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for quick work. Merged!

**Comment by bskinn** [comment]
Absolutely! Thanks for all your efforts contributing to the maintenance & improvement of the project!

**Pull request merged**
