### PR TITLE
Replace `a and b or c` by the more legible `b if a or c`.

### PR DESCRIPTION
**Pull request by anntzer**
Subject: Replace `a and b or c` by the more legible `b if a or c`.

### Feature or Bugfix
Style.

### Purpose
Just a small legibility improvement (IMO).

### Detail
N/A

### Relates
N/A

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
It seems some tests are failed. Could you check them please?

**Comment by tk0miya** [comment]
IMO, -0 for this. I don't like python's ternary operator because it is not easily understandable to me. `value_a if cond else value_b` is not legible to me. I'm confused always why condition-block is placed at middle in the sentence. I know this is my personal opinion. It's bikeshed discussion. But...

**Comment by anntzer** [comment]
Oops, should be fixed now.
Style-wise I can't help if you don't like `true if cond else false`; I think it's much more common nowadays (and thus more readable for most devs) than `conf and true else false` but ultimately it's your choice, so feel free to close if you don't want it.

**Review by stephenfin — APPROVED** [review]
I'm personally in favour of this, for the opposite of the reason mentioned above (I find this more readable). Willing to be overruled though

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Okay, let's merge this. My opinion is not important. I know new style is well used.
BTW, could you rebase this into 2.0 branch please? It is much better to develop Sphinx to us.

**Comment by anntzer** [comment]
rebased

**Comment by tk0miya** [comment]
Thank you for rebasing. Merged!

**Pull request merged**
