### PR TITLE
Fix #2374: Init method inclusion

### LINKED ISSUE #2374: Documenting __init__ function with napoleon
Maybe it is due to the lack of my proper googling skills but I could not figure out how I could document the **init** methods of my classes. Thus, I rewrote napoleon a little bit by adding a new option (napoleon_include_init_with_doc ) alongside the existing napoleon_include_private_with_doc and napoleon_include_special_with_doc.

Would this functionality made sense to you to be included with a new version of napoleon?

### PR DESCRIPTION
**Pull request by mausr**
A new setting is added to force documentation of the **init** methods.

### CODE REVIEW

**Comment by tk0miya** [comment]
@RobRuana Could you check this pull request please?

**Comment by RobRuana** [comment]
Thanks! I'll take a look tomorrow!

**Comment by RobRuana** [comment]
@mausr this looks great, but seems to be failing the flake8 tests:

```
./sphinx/ext/napoleon/__init__.py:448:17: E129 visually indented line with same indent as next logical line
```

Maybe change it to something like [this SO answer](http://stackoverflow.com/questions/5253348/very-long-if-statement-in-python/5253419#5253419)?

**Comment by mausr** [comment]
Ohh, I've just realized everything passes the local flake8 tests on my laptop... I'll correct the problem on the weekend. Thanks for the link!

**Comment by mausr** [comment]
Flake8 error has been fixed.:)

**Pull request merged**
