### PR TITLE
Allow numbering custom elements as figure/table/block

### PR DESCRIPTION
**Pull request by Jellby**
Add the option to have other elements (added by an extension) numbered as figure, table or code block, by specifying the attribute "figtype".

### CODE REVIEW

**Comment by tk0miya** [comment]
Now, we introduce new API `Sphinx.add_enumerated_node` to support this.
More details, please refer #2317.

Anyway, your pull request has become of the wake of the feature.
Thank you for great proposal.

**Comment by eudoxos** [comment]
Coming back here, I see add_enumerable_node was merged in 1.4; how is it supposed to be used? It is not documented at all from the user perspective.

**Comment by paternal** [comment]
> Coming back here, I see add_enumerable_node was merged in 1.4; how is it supposed to be used? It is not documented at all from the user perspective.

@eudoxos: I managed to use it in  [sphinxcontrib-proof](http://pypi.org/pypi/sphinxcontrib-proof). You can see it in action [there](https://git.framasoft.org/spalax/sphinxcontrib-proof/blob/99d10615317d824d0e9e24c2463550ef1870702d/sphinxcontrib/proof/__init__.py).

Creating a dummy extension to show how to use `add_enumerable_node()` (and documenting it) is on my TODO list, but with a low priority. So if you, random passerby, want to do it, go ahead!

**Comment by paternal** [comment]
I wrote [such a dummy extension](https://sphinxcontrib-stuffcounter.readthedocs.io/en/latest/). I offered to the sphinx team to adopt it as a part of @sphinx-contrib (see #5567).

**Pull request closed without merging**
