### PR TITLE
Fix handling of local paths in html_logo/html_favicon directorives in conf.py

### LINKED ISSUE #9438: 4.1.0 regression: HTML logo or Favicon specified as file not being found on output
### Describe the bug

If you specify `html_logo` or `html_favicon` values in `conf.py` as files (not URLS), then they won't be found properly in the generated HTML output unless you place the files in the configuration root of your source.

For fuller explanation, refer to merged https://github.com/sphinx-doc/sphinx/pull/9381.

### How to Reproduce

Place a logo for your HTML docs in a subdirectory below the configuration root of your source files (like `_static/logofile.png` for example).

Build your docs as normal. Your `logofile.png` will get copied into the output tree's `_static` subdirectory as expected, but your generated HTML will refer to it as if it were in `_static/_static/logofile.png`.

**Workaround**. Placing your project's logo image and favicon file into the configuration root directory so that your `html_logo` and `html_favicon` config variables have no file path to the files is a workaround until a fix is merged.

### Expected behavior

When referring to your logo or favicon files by file path in configuration, the generated HTML output should seek to find them directly in the `_static` subdirectory in the output tree as expected.

See attached test.zip project.

[test.zip](https://github.com/sphinx-doc/sphinx/files/6804457/test.zip)

### Your project

See Test project attached in Expected behaviour

### Screenshots

_No response_

### OS

MacOS 11.4

### Python version

3.9

### Sphinx version

4.1.0

### Sphinx extensions

_No response_

### Extra tools

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tronical**
Merge request #9381 broke support for local logos/favicons as it
retained the paths that are passed to the template engine. That's wrong
as the actual path will be in _static/.

This should fix #9438

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
LGTM. But this should be rebased onto 4.1.x branch. Could you update this please? Then, I'll merge this soon.

**Comment by tronical** [comment]
> LGTM. But this should be rebased onto 4.1.x branch. Could you update this please? Then, I'll merge this soon.

Sure! Well, hmm, it seems that it's already on 4.1.x:

```sh
$ git rev-parse origin/4.1.x
3c3a734b97c99a9f2b32bd33f7b98921d9da294f
$ git rebase origin/4.1.x
Current branch logo-regression-fix is up to date.
```

I think I may have accidentally just set the target branch incorrectly on this merge request %-)

**Comment by tk0miya** [comment]
This PR contains the CHANGES entry for 4.2.0. I guess you created a commit on the 4.x branch.
Could you try the following command?
```
$ git rebase 4.x --onto 4.1.x
```

Thanks,

**Comment by tronical** [comment]
Ooops, indeed, that explains it. Ok, rebased and force-pushed. I hope it's correct now :)

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for quick update!

**Pull request merged**
