### PR TITLE
1.8

### PR DESCRIPTION
**Pull request by padila50**
Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

### CODE REVIEW

**Comment by tk0miya** [comment]
I'm closing this because of conflicts.

**Comment by padila50** [comment]
Could you explain technically in detail? Thanks.

**Comment by padila50** [comment]
Cause of the conflict.

**Comment by padila50** [comment]
I want setup language libs for Indonesian, id. Let's me know, thanks.

**Comment by tk0miya** [comment]
Would do you like to translate messages of Sphinx to Indonesian, right?
If true, please join our transifex group.
https://www.transifex.com/sphinx-doc/

Thanks,

**Comment by padila50** [comment]
Yes. Thank you for your respond.

Pada tanggal Jum, 14 Sep 2018 20.50, Takeshi KOMIYA <
notifications@github.com> menulis:

**Pull request closed without merging**
