### PR TITLE
[docs] Reduce size of PNG files

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Subject: smaller PNG files

### Feature or Bugfix

- Refactoring

### Purpose
- Load faster, less network traffic.

### Detail
- Run `optipng -o9` on screen captures in the Lumache tutorial.

### CODE REVIEW

**Comment by picnixz** [comment]
> Thanks, out of interest, do you have a comparison of the before/after size? 

GitHub is showing it if you go to files!

**Comment by DimitriPapadopoulos** [comment]
Indeed, size is reduced to approximately 77 % of the original size (all files as a whole).

Note that [optipng](https://optipng.sourceforge.net/) does lossless compression. Other software, such as [pngquant](https://pngquant.org/), achieve even better compression, at the expense of lossy compression.

**Comment by picnixz** [comment]
Just wondering but... why not just using JPG? (it may be ugly but it's lighter!)

**Comment by chrisjsewell** [comment]
> GitHub is showing it if you go to files!

Oh yeh oops I missed that 🤦

**Comment by DimitriPapadopoulos** [comment]
Indeed, JPEG sounds like a better choice for lossy compression.

All images in the documentation are currently PNG files. Perhaps lossy compression and JPEG should be addressed in a different PR - starting with a discussion or issue.

**Comment by chrisjsewell** [comment]
@picnixz I'm happy to merge this as is, since it is at least an iterative improvement?

**Pull request merged**
