### PR TITLE
fix #2352 (qthelp builder should have ) and improve qthelp readability

### LINKED ISSUE #2352: qthelp builder should have `search=False`
As per title; the qthelp builder doesn't include the necessary Javascript for the search anyway, so it may as well not even generate the search page.

### PR DESCRIPTION
**Pull request by shibukawa**
by using new `nonav` theme.

### CODE REVIEW

**Comment by tk0miya** [comment]
Could you paste screenshots? I want to know what is changed in the new theme.

**Comment by shibukawa** [comment]
Before:



After:

**Comment by tk0miya** [comment]
LGTM

**Comment by tk0miya** [comment]
Thanks!

**Pull request merged**
