### PR TITLE
literalinclude and code-block with caption allow pagebreak

### PR DESCRIPTION
**Pull request by takaakiaoki**
Proposal to #2147 

Replace legacy float by newfloat package to allow page-break
within literal-block environment. capt-of and needspace packages are
additionally required.

reference:
http://tex.stackexchange.com/questions/175650/how-to-allow-page-break-inside-a-float-environment

### CODE REVIEW

**Comment by shimizukawa** [comment]
Thanks! @takaakiaoki please check test fails on TravisCI

**Comment by takaakiaoki** [comment]
Anyway, this PR has passed the tests. However, test strings have to be modified in order to adopt newfloat package instead of legacy one. So we should be careful to merge it.
I am afraid that I have not tested the generation of 'list of codes' yet.

**Comment by tk0miya** [comment]
LGTM. It works fine!

@shimizukawa You had set milestone as 1.4.
but I think this PR should be merged into stable branch.
because it is not a new feature, a bug fix.

**Comment by shimizukawa** [comment]
@tk0miya OK. please merge this into stable.

**Comment by tk0miya** [comment]
I merged this into stable branch manually.
@takaakiaoki Thank you for contribution!

**Pull request closed without merging**
