### PR TITLE
Fix a small bug in docs on "HTML theming support"

### PR DESCRIPTION
**Pull request by nevimov**
A python code example from http://www.sphinx-doc.org/en/stable/theming.html#using-a-theme
contains javascript-style comments.

### CODE REVIEW

**Comment by lehmannro** [comment]
While we're here, we can also improve l10n of this and fix this in either of the possible ways:
- Make the comments so short they don't need l10n, ie. only `setup.py` and `your_package.py`.
- Pull the comments out into normal text.

**Comment by nevimov** [comment]
Done.

**Comment by tk0miya** [comment]
LGTM. I will merge this within a day :-)

**Comment by tk0miya** [comment]
Merged.
Thank you for contribution!

**Pull request merged**
