### PR TITLE
Fix non-translated formatted string in js

### LINKED ISSUE #12129: Strings not localized
### Describe the bug

Some strings are not localized.

For instance, with `language = 'fr'` in `conf.py`, the `.../_build/html/search.html?q=test` (see  minimal `Sphinx` joined) page displays:

> Une recherche sur plusieurs mots ne retourne que les résultats contenant tous les mots. 

(in French in the text), but also on the same page:

> Search finished, found 1 page(s) matching the search query.

(in English in the text, instead of French) and, this, despite:
```
#: sphinx/themes/basic/static/searchtools.js:118
msgid ""
"Search finished, found ${resultCount} page(s) matching the search query."
msgstr "Recherche terminée, ${resultCount} page(s) correspondant à la requête de recherche ont été trouvées."
```
in `.../sphinx/locale/fr/LC_MESSAGES/sphinx.po`.

### How to Reproduce

See [`test-sphinx.tar.gz`](https://github.com/sphinx-doc/sphinx/files/14638627/test-sphinx.tar.gz).

### Environment Information

```text
Platform:              linux; (Linux-6.6.18-desktop-1.mga9-x86_64-with-glibc2.36)
Python version:        3.10.11 (main, Apr 16 2023, 03:21:15) [GCC 12.2.1 20230415])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.17.2
```

### Sphinx extensions

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by n-peugnet**
The formatted string was evaluated before the gettext call, which prevented any translated message from being loaded. Use a plain old string instead and manually replace the text afterwards.

Fixes #12129

I tried to switch to the supposedly more correct `Document.ngettext` function by the way, but didn't manage to make it work properly for french plurals. So instead I decided to only fix the original issue. This also allows to reuse the message for languages that have already translated it.

2024-03-30-215856_673x383_scrot

### CODE REVIEW

**Review by chrisjsewell — APPROVED** [review]
Looks great to me thanks! Will leave it open a little longer, in case any one else wants to look

**Comment by picnixz** [comment]
This is interesting. Are there other places where JS strings are not correctly localized ? (if so, could you correct them in one PR?)

**Comment by n-peugnet** [comment]
> This is interesting. Are there other places where JS strings are not correctly localized ? (if so, could you correct them in one PR?)

I didn't find other places with this problem. But I saw in the generated js translation files that there are some strings with variable replacements using a différent pattern, for example in [the french translation's one](https://github.com/sphinx-doc/sphinx/blob/cb8a28dd7e11a7a0a5bc9694163fc164433e2f36/sphinx/locale/fr/LC_MESSAGES/sphinx.js#L4-L5):


https://github.com/sphinx-doc/sphinx/blob/cb8a28dd7e11a7a0a5bc9694163fc164433e2f36/sphinx/locale/fr/LC_MESSAGES/sphinx.js#L4-L5

Maybe it would be better to also use the same `%(varname)s` pattern in manually replaced strings?

For now I thought it would be best to keep the string as is, so we don't have to translate it again.

**Comment by picnixz** [comment]
> Maybe it would be better to also use the same %(varname)s pattern in manually replaced strings?

I'm sorry but I don't see the difference with what you showed (unless you are talking about the copyright line, in which case it appears we just don't translate it at all for now?)

> For now I thought it would be best to keep the string as is, so we don't have to translate it again.

Yes, let's just not change it for now. I was just wondering whether there were other issues similar to what we had.

**Review by picnixz — APPROVED** [review]

**Comment by picnixz** [comment]
Thank you!

**Pull request merged**
