### PR TITLE
fix typo in extrapackges example

### PR DESCRIPTION
**Pull request by king-phyte**
Subject: Fix typo in extrapackages example in LaTeX customization docs

### Feature or Bugfix
- Bugfix

### Purpose
The example in the docs for extrapackages under LaTeX customization is slightly incorrect (as shown below).
```
latex_elements = {
    'packages': r'\usepackage{isodate}'
}
```
Doing so will lead to Sphinx producing the following warning
`WARNING: Unknown configure key: latex_elements['packages'], ignored.`

### CODE REVIEW

**Comment by jfbu** [comment]
Indeed, thanks! Now merging (thanks @AA-Turner for branch change)

**Comment by AA-Turner** [comment]
I tried to change the base to `5.x` through the GitHub UI but it didn't really work.

A

**Comment by jfbu** [comment]
> I tried to change the base to `5.x` through the GitHub UI but it didn't really work.

ok, problem is that PR may contain patches not in 5.x that we don't want, then we must rebase, I have done that in past force-pushing to original poster branch, now taking care of it ;-)

**Comment by jfbu** [comment]
Will merge after testing completes, thank you for contribution!

**Comment by jfbu** [comment]
Hmm, I rebased this one-commit patch on top of current 5.x (at eb5b3aa25db) and now `mypy` fails (https://github.com/sphinx-doc/sphinx/actions/runs/3129148546/jobs/5077876359) for unrelated reasons...

...let's wait until this is resolved, ping @AA-Turner

**Comment by AA-Turner** [comment]
It's not the fault of this docs-only PR (might be a new mypy version), so I'd merge and see if it fails on master.

A

**Comment by jfbu** [comment]
> 

Perhaps first adapt to the new mypy (if that is explanation) 5.x before merge?

**Comment by jfbu** [comment]
@AA-Turner about
I could not recreate at my locale with 3.10.4 even though all packages listed in the CI job have exact same version.  I have now also upgrade to 3.10.7 and same
```
mypy create: /Users/path/to/sphinx/.tox/mypy
mypy develop-inst: /Users/path/to/sphinx
mypy installed: alabaster==0.7.12,astor==0.8.1,attrs==22.1.0,Babel==2.10.3,certifi==2022.9.24,charset-normalizer==2.1.1,docutils==0.19,docutils-stubs==0.0.22,flake8==5.0.4,flake8-bugbear==22.9.23,flake8-comprehensions==3.10.0,flake8-simplify==0.19.3,idna==3.4,imagesize==1.4.1,isort==5.10.1,Jinja2==3.1.2,MarkupSafe==2.1.1,mccabe==0.7.0,mypy==0.971,mypy-extensions==0.4.3,packaging==21.3,pycodestyle==2.9.1,pyflakes==2.5.0,Pygments==2.13.0,pyparsing==3.0.9,pytz==2022.2.1,requests==2.28.1,snowballstemmer==2.2.0,-e git+https://jfbu@github.com/sphinx-doc/sphinx.git@793827ce2472778e6f7fb3a21019848d9f9f877f#egg=Sphinx,sphinx-lint==0.6.1,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,tomli==2.0.1,types-requests==2.28.11,types-typed-ast==1.5.8,types-urllib3==1.26.24,typing_extensions==4.3.0,urllib3==1.26.12
mypy run-test-pre: PYTHONHASHSEED='2958459965'
mypy run-test: commands[0] | mypy sphinx/
Success: no issues found in 174 source files
___________________________________ summary ____________________________________
  mypy: commands succeeded
  congratulations :)
```

The GenericMeta is an attribute of typing_extensions, removed from typing at 3.7.

**Comment by king-phyte** [comment]
Thank you very much @jfbu @AA-Turner

**Pull request merged**
