### PR TITLE
[mypy] explicitly exclude files instead of ignoring errors by modules

### PR DESCRIPTION
**Pull request by picnixz**
After merging #12173, I suggest we change the ``[[tool.mypy.overrides]]`` into a *true* exclusion list. 

The rationale is that, with `ignore-errors`, if you mypy the file without removing the module from the overrides list, you will not do anything. However, if you mypy the file and that file is excluded by default, mypy runs normally.

### CODE REVIEW

**Comment by jayaddison** [comment]
To check my understanding of this:

#### Before
* Exclude three directories (`tests/roots`, ...) during `mypy` typechecking.
* For a large set of modules, override and set `ignore_errors` to true (check them, but don't report any problems).
* When checking an _individual_ file (`mypy <path/to/module.py`), the overrides were ignored, so errors would be reported.

#### After
* Exclude three directories (`tests/roots`, ...) as before.
* Additionally exclude a series of fixed file paths.


And a question:

Will we forget to update the paths if we move files around?  (equally could happen for module names; are inconsistencies in either approach reported by `mypy` as errors?)

**Comment by picnixz** [comment]
> When checking an individual file (mypy <path/to/module.py), the overrides were ignored, so errors would be reported.

The issue was: if you don't remove the file you are checking from the list of overrides, there won't be an error (even if you mypy it explicitly). So you needed to *first* remove from the override list AND then you could mypy it.

Now, with my PR, you can directly mypy it since an excluded file is only ignore *if* it is not explicitly passed.

> Will we forget to update the paths if we move files around? (equally could happen for module names; are inconsistencies in either approach reported by mypy as errors?)

Yes.. but the same would have been the case for the module approach. Note that with an explicit exclusion, we also do not typecheck some files (possibly caching some results).

**Review by jayaddison — APPROVED** [review]

**Review by chrisjsewell — APPROVED** [review]
when I first saw the title, I was thinking perhaps there is a difference in mypy behaviour, when these modules are imported into another module, ... but then I saw that we are only doing this for test files, so that does not apply 😄 

All good then
(maybe could change the PR / commit message to reflect this is only for tests, but not a blocker)

**Comment by picnixz** [comment]
I hate myself. I made a typo in the commit message

**Pull request merged**
