### PR TITLE
Themes: Rename 'csss' block to 'css'

### PR DESCRIPTION
**Pull request by Blendify**
Was a mistake in 618ef6492c89c50f263c4c6c5794e40e35f91be8

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
LGTM!

**Comment by tk0miya** [comment]
@Jellby What do you think? I guess you'd meant CSSs (plural).

**Comment by tk0miya** [comment]
@Blendify ah, I'd noticed that this should be merged into `1.7-release`. Could you rebase this please?

**Comment by Blendify** [comment]
I had to send my laptop away so I cant do anything beyond the web editor

**Comment by tk0miya** [comment]
Note: we talked with Jellby at here: https://github.com/sphinx-doc/sphinx/commit/618ef6492c89c50f263c4c6c5794e40e35f91be8#r26988434.

**Comment by tk0miya** [comment]
I manually cherry-picked into 1.7-release branch now.
Thank you always :-)

**Pull request closed without merging**
