### PR TITLE
Closes #4614: sphinx-build: Add :option:`--keep-going` option to show all warnings

### LINKED ISSUE #4614: Sphinx should show all warnings with -W
When using the `-W` flag to turn warnings into errors, the first warning will result in an error and cause the build to stop. It would be nice if all warnings were shown, as without using -W. 

This was first mentioned at https://github.com/sphinx-doc/sphinx/issues/4606

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Feature

### Purpose
- refs: #4614

### CODE REVIEW

**Comment by asmeurer** [comment]
I think it should be the default (with `--no-keep-going`) being the flag, but I don't feel too strongly as long as the option is there.

**Comment by tk0miya** [comment]
I'd like to keep compatibility. So I'd not like to change the behavior of `-N` option.

@shimizukawa any comments?

**Comment by asmeurer** [comment]
I don't really see how it's a compatibility break. The only difference here is that broken builds might take longer.

**Review by shimizukawa — APPROVED** [review]
LGTM!

**Comment by tk0miya** [comment]
>The only difference here is that broken builds might take longer.

AFAIK, there are very large documents using Sphinx. It takes a few minutes on building.
I'm afraid this change affects to the author of them.

So I'd like to add a new option for keep-going.

**Comment by tk0miya** [comment]
If agreed, I will merge this to 1.8 release soon.

**Comment by asmeurer** [comment]
Yes, the SymPy docs are one of them (the original motivator of this issue). It takes over 3 minutes to build them from scratch on my laptop.

Of course, the whole reason we use -W is that we never want the docs to have any warnings or errors. So the in the ideal case the docs work as expected and take the full time to build.

**Comment by tk0miya** [comment]
Merged. Thank you for comment!

**Pull request merged**
