### PR TITLE
Show the repr of the value in some warnings.

### PR DESCRIPTION
**Pull request by ezio-melotti**
Subject: Show the repr of the value in some warnings

### Feature or Bugfix

- Refactoring

### Purpose
- This PR uses `%r` to display values in some warning messages.

### Detail
- https://github.com/sphinx-doc/sphinx/issues/10438

Note that I only fixed `sphinx/domains/std.py` and the tests that failed after the fix.
There are similar warnings in other files that could be changed.
A test specific for trailing spaces could be added, but I'm not sure where.

### CODE REVIEW

**Review by AA-Turner — COMMENTED** [review]
Seems reasonable, although this probably needs a CHANGES entry.

Where else were you thinking of changing from `str` -> `repr`?

A

**Comment by ezio-melotti** [comment]
> Where else were you thinking of changing from str -> repr?

I've seen a few more that seem related by looking for `dangling_warnings`, e.g.:
https://github.com/sphinx-doc/sphinx/blob/1222bed88eb29cde43a81dd208448dc903c53de2/sphinx/domains/citation.py#L30-L32
https://github.com/sphinx-doc/sphinx/blob/1222bed88eb29cde43a81dd208448dc903c53de2/sphinx/domains/math.py#L40-L42

Searching for `logger.warning` yields plenty of results too.

Searching for `unknown` yields some more, like:
https://github.com/sphinx-doc/sphinx/blob/1222bed88eb29cde43a81dd208448dc903c53de2/sphinx/domains/c.py#L171
and several others (some even use `'...: "%s".' % value`), but I'm not sure if these are related, since I'm not too familiar with the codebase.

I only fixed `std.py` to keep the PR focused and get some initial feedback.  If you think I should fix more messages and add the `CHANGES` entry just let me know.

**Review by tk0miya — COMMENTED** [review]
As I commented at https://github.com/sphinx-doc/sphinx/issues/10438#issuecomment-1126648370, these target can contain a single quote. So -0 for changing this.

**Comment by ezio-melotti** [comment]
Python's `repr` uses single quotes by default and switches to doubles quote if the string already contains single quotes.  If the string contains both, it will use single quotes and escape any single quote in the string:
```pycon
>>> print(repr(""" "only double quotes" """))  # output uses single quotes
' "only double quotes" '
>>> print(repr(""" 'only single quotes' """))  # output uses double quotes
" 'only single quotes' "
>>> print(repr(""" "mixed" 'quotes' """))  # output uses single quotes + escapes
' "mixed" \'quotes\' '
```

Therefore, the following markup:
```rst
:ref:`in-development <in"dev"branch>`
:ref:`maintenance <maint'branch>`
:ref:`Quick Guide to Pull Requests <pull"request"-quick'guide>`
:doc:`pull request <pull'request>`
:ref:`contributor agreement < cla>`
:doc:`pull request <pullrequest >`
```
will trigger these warnings:
```
devguide/docquality.rst:33: WARNING: undefined label: 'in"dev"branch'
devguide/docquality.rst:33: WARNING: undefined label: "maint'branch"
devguide/docquality.rst:62: WARNING: undefined label: 'pull"request"-quick\'guide'
devguide/docquality.rst:107: WARNING: unknown document: "pull'request"
devguide/docquality.rst:112: WARNING: undefined label: ' cla'
devguide/docquality.rst:129: WARNING: unknown document: 'pullrequest '

```
Only the third example (that contains both single and double quotes) includes an escaped `\'`.
The last two examples show leading and trailing spaces -- now clearly visible thanks to the repr.

**Comment by AA-Turner** [comment]
@ezio-melotti please add a CHANGES entry.

A

**Comment by ezio-melotti** [comment]
Thanks for taking care of the CHANGES entry and merging this!

**Pull request merged**
