### PR TITLE
Use ``any`` to find elements in iterable

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
@AA-Turner what exactly is 'ruff' linting for?

**Comment by AA-Turner** [comment]
> what exactly is 'ruff' linting for?

Speed.

From PowerShell's `Get-History -Count 9` (formatted as a markdown table):

Id | Duration | CommandLine
-- | -------- | -----------------
 1 | 0.070    | ruff . 
 2 | 0.065    | ruff . 
 3 | 0.057    | ruff . 
 4 | 0.198    | ruff . --no-cache
 5 | 0.146    | ruff . --no-cache
 6 | 0.167    | ruff . --no-cache
 7 | 4.927    | flake8 .
 8 | 4.793    | flake8 .
 9 | 4.791    | flake8 .

A

**Comment by AA-Turner** [comment]
To solve the check error you probably need to add `SIM110` to `tool.ruff.external` in `pyproject.toml`.

A

**Comment by danieleades** [comment]
> To solve the check error you probably need to add `SIM110` to `tool.ruff.external` in `pyproject.toml`.
> 
> A

Ruff's docs claim that it does everything that `flake8-simplify` does. I might have a diddle about with this and see if I can eliminate the overlap

**Comment by danieleades** [comment]
closer inspection of ruff's repo seems to indicate that fully replacing `flake8-simplify` is more aspirational than complete

https://github.com/charliermarsh/ruff/issues/998

i'll add the ignore and leave `flake8-simplify` in for now, with a view to deprecating it later

**Comment by charliermarsh** [comment]
Saw this linked from the `flake8-simplify` issue so thought I'd just chime in to say it's actively being worked on.

**Pull request merged**
