### PR TITLE
refactor: Use repr() to make escaped string in template for conf.py

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Refactoring

### Purpose
- Use repr() to make escaped string in template for conf.py
- alternative of #3584 
  - We can use simple `repr()` because we'd dropped py2 support!

### CODE REVIEW

**Review by jdufresne — APPROVED** [review]

**Comment by shimizukawa** [comment]
My question is: as a Python specification, is this certainly true? `exec(repr(obj)) == obj`
In this PR case, maybe OK. I will investigate the python reference to solve that concern.

**Comment by shimizukawa** [comment]
https://docs.python.org/3.6/library/functions.html#repr
> For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval(),

`For may types`.

https://docs.python.org/3.6/reference/datamodel.html#object.__repr__
> Called by the repr() built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment).

`that could be used to recreate an object`

In my investigation, there is no fact that it is not good to pass a `str` to `repr`.
(On py2, unexpected result case is exist: https://github.com/sphinx-doc/sphinx/pull/3584#issuecomment-295736278 )

**Review by shimizukawa — APPROVED** [review]
LGTM!

**Comment by tk0miya** [comment]
Thank you for reviewing carefully :-)

**Pull request merged**
