### PR TITLE
#1719 numfig_format was ignored on latex

### PR DESCRIPTION
**Pull request by tk0miya**
This fixes almost of #1719.
- Change format of caption for figures and tables
- Add prefix to linkname of `:numref:`

but I do not have a solution to change format of caption for code-blocks.
Anyone can help me?

### CODE REVIEW

**Comment by shimizukawa** [comment]
Thanks @tk0miya,
I've found a issue on this PR.

conf.py:

```
numfig = True
numfig_format = {
    'figure': '## Fig. ## %s ##',
    'table': '## Table ## %s ##',
    'code-block': '## Listing ## %s ##',
}
```

index.rst:

```
1719
====

.. figure:: img.png

   HELLO-FIGURE

.. table:: HELLO-TABLE

   ==== ===
   1    2
   ==== ===

.. code-block:: python
   :caption: HELLO-LISTING

   import this
```

1752.pdf:
pasted_image_at_2015_03_05_12_23_am

It seems some `##` are not appeared on PDF.

**Comment by tk0miya** [comment]
@shimizukawa thank you for reviewing.
I've overlooked that. I tested only on `make latexpdfja`.
I'll fix it tomorrow.

**Comment by tk0miya** [comment]
@shimizukawa I just fixed the problem. it is caused from `babel` feature on LaTeX.
In my environment, I set `language` as `ja` at conf.py. It disables `babel` feature. so I missed it.

Could you try this again?

**Comment by shimizukawa** [comment]
@tk0miya it's better, but `Listing` still lacks 3rd `##`. I guess it's a "format of caption for code-blocks" you mentioned.

image

Otherwise, looks good.

**Comment by tk0miya** [comment]
@shimizukawa You're right. I can't find how to change it.

BTW, I found this settings breaks label of `:numref:`.
`#` symbol in `numfig_format` is replaced by fignums.


It is caused from difference of special character between `numfig_format` (`%s`) and `:numref:` (`#`).
I want to change them to `%s`.
What do you think?

**Comment by shimizukawa** [comment]
Agreed. However, it would be better by another PR or a direct commit.

**Comment by tk0miya** [comment]
@shimizukawa  Thank you for reviewing and merging!

**Pull request merged**
