### PR TITLE
IndexRack which is a new indexer instead of IndexEntries.

### LINKED ISSUE #9744: IndexEntries class takes three FAILs of four testcases.
### Describe the bug

When I edit a rst file which has glossary's index_key, I have to use 'make clean' before 'make html'.

This problem depends on IndexEntries class.

- sphinx/envioronment/adapsters/indexentries.py

An other indexentries which I made doesn't have this problem. so, If anyone would consider hiring this indexer, I would like to discuss how to proceed. 

My suggestion is as follows:

1. evaluate two testcases on this issue.
2.  If your sphinx project would have no term with letter '|' or '^', you could use the indexer of a sphinx extention as they are.  
3. prepare a package 'sphinx-indexer'. because the indexer is of the sphinx exetention now.
4. use the package to evaluate.
5. exchange indexentries.py on a day.

related with:

- [About the 'experimental' of 'Changed in version 1.4: Index key for glossary term should be considered experimental'](https://stackoverflow.com/questions/69592462/about-the-experimental-of-changed-in-version-1-4-index-key-for-glossary-term)

note:

- I've only recently registered as a user of both pypi and github.
-  so I may not have a basic understanding of how to proceed.
- If there is any information that I am missing, I would appreciate it if you could let me know.

### How to Reproduce

testcase

```python
#!/usr/bin/python
import unittest
from sphinx.environment.adapters.indexentries import IndexEntries

testcase01i = { 
'doc1': [
    ('single', 'aaa', 'id-111', '', 'clf1'),
    ('single', 'bbb', 'id-112', '', None),
],
'doc2': [
    ('single', 'aaa', 'id-121', '', None),
    ('single', 'bbb', 'id-122', '', 'clf2'),
], }

testcase01o = [
('clf1',
  [('aaa', [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1']), ]
),
('clf2',
  [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None]), ]
),
]

testcase02i = {
'doc1': [
    ('see','hogehoge; foo','id-211','main',None),
    ('seealso','hogehoge; bar','id-212','main',None), ]
}

testcase02o = [
('H',
    [('hogehoge',
        [[],
         [('see also bar', []), ('see foo', [])],
         None
        ])
    ])
]

testcase03i = {
'doc1': [
    ('single','func1() (aaa module)','id-311','',None),
    ('single','func1() (bbb module)','id-312','',None),
    ('single','func1() (ccc module)','id-313','',None),]
}

testcase03o = [
('F',
  [('func1()',
    [[],
     [('(aaa module)', [('', 'doc1.html#id-311')]),
      ('(bbb module)', [('', 'doc1.html#id-312')]),
      ('(ccc module)', [('', 'doc1.html#id-313')])
     ],
     None])])
]


testcase04i = {
'doc1': [
    ('single','func1() (aaa module)','id-411','',None),
    ('single','func1() (bbb module)','id-412','',None),
    ('single','func1() (ccc module)','id-413','main',None), ]
}

testcase04o = [
('F',
  [('func1()',
    [[],
     [('(aaa module)', [('', 'doc1.html#id-411')]),
      ('(bbb module)', [('', 'doc1.html#id-412')]),
      ('(ccc module)', [('main', 'doc1.html#id-413')]), ],
     None])])
]

#-------------------------------------------------------------------

class _domain(object):
    def __init__(self, entries):
        self.entries = entries

class _env(object):
    def __init__(self, domain):
        self.domain = {}
        self.domain['index'] = domain
    def get_domain(self, domain_type):
        return self.domain[domain_type]

class _builder(object):
    def get_relative_uri(self, uri_type, file_name):
        return f'{file_name}.html'

#-------------------------------------------------------------------

bld = _builder()

class TestcaseIndexEntries(unittest.TestCase):
    def test01_classifier(self):
        self.maxDiff = None
        dmn = _domain(testcase01i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase01o, gidx)
    def test02_see_and_seealso(self):
        self.maxDiff = None
        dmn = _domain(testcase02i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase02o, gidx)
    def test03_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase03i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase03o, gidx)
    def test04_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase04i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase04o, gidx)

#-------------------------------------------------------------------

if __name__ == '__main__':
    unittest.main()
```

result

```
F.FF
======================================================================
FAIL: test01_classifier (__main__.TestcaseIndexEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unittest_IndexEntries_so.py", line 103, in test01_classifier
    self.assertEqual(testcase01o, gidx)
AssertionError: Lists differ: [('clf1', [('aaa', [[('', 'doc1.html#id-111'[127 chars]])])] != [('B', [('bbb', [[('', 'doc1.html#id-112'), [124 chars]])])]

First differing element 0:
('clf1', [('aaa', [[('', 'doc1.html#id-111'[39 chars]'])])
('B', [('bbb', [[('', 'doc1.html#id-112'), [34 chars]e])])

+ [('B',
+   [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None])]),
- [('clf1',
? ^

+  ('clf1',
? ^

    [('aaa',
-     [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1'])]),
?                                                                          ^

+     [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1'])])]
?                                                                          ^

-  ('clf2',
-   [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None])])]

======================================================================
FAIL: test03_homonymous_function (__main__.TestcaseIndexEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unittest_IndexEntries_so.py", line 115, in test03_homonymous_function
    self.assertEqual(testcase03o, gidx)
AssertionError: Lists differ: [('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[111 chars]])])] != [('F', [('func1() (aaa module)', [[('', 'doc1.html#id-311'[102 chars]])])]

First differing element 0:
('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[110 chars]e])])
('F', [('func1() (aaa module)', [[('', 'doc1.html#id-311'[101 chars]e])])

  [('F',
+   [('func1() (aaa module)',
-   [('func1()',
-     [[],
-      [('(aaa module)', [('', 'doc1.html#id-311')]),
? -     -----------------                          -

+     [[('', 'doc1.html#id-311')],
-       ('(bbb module)', [('', 'doc1.html#id-312')]),
?      ^

+      [('(bbb module)', [('', 'doc1.html#id-312')]),
?      ^

        ('(ccc module)', [('', 'doc1.html#id-313')])],
       None])])]

======================================================================
FAIL: test04_homonymous_function (__main__.TestcaseIndexEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unittest_IndexEntries_so.py", line 121, in test04_homonymous_function
    self.assertEqual(testcase04o, gidx)
AssertionError: Lists differ: [('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[115 chars]])])] != [('F', [('func1() (aaa module)', [[('', 'doc1.html#id-411'[106 chars]])])]

First differing element 0:
('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[114 chars]e])])
('F', [('func1() (aaa module)', [[('', 'doc1.html#id-411'[105 chars]e])])

  [('F',
+   [('func1() (aaa module)',
-   [('func1()',
-     [[],
-      [('(aaa module)', [('', 'doc1.html#id-411')]),
? -     -----------------                          -

+     [[('', 'doc1.html#id-411')],
-       ('(bbb module)', [('', 'doc1.html#id-412')]),
?      ^

+      [('(bbb module)', [('', 'doc1.html#id-412')]),
?      ^

        ('(ccc module)', [('main', 'doc1.html#id-413')])],
       None])])]

----------------------------------------------------------------------
Ran 4 tests in 0.008s

FAILED (failures=3)
```

### Expected behavior

```
....
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
```

### Your project

https://github.com/KaKkouo/kana_text

### Screenshots

_No response_

### OS

Win

### Python version

3.8.10

### Sphinx version

4.2.0

### Sphinx extensions

sphinx.ext.todo, sphinxcontrib.yt, sphinxcontrib.kana_text, matplotlib.sphinxext.plot_directive

### Extra tools

unittest

### Additional context

testcase which all is passed with.

```python
#!/usr/bin/python
import unittest
from sphinx.environment.adapters.indexentries import IndexEntries

testcase01i = { 
'doc1': [
    ('single', 'aaa', 'id-111', '', 'clf1'),
    ('single', 'bbb', 'id-112', '', None),
],
'doc2': [
    ('single', 'aaa', 'id-121', '', None),
    ('single', 'bbb', 'id-122', '', 'clf2'),
], }

testcase01o = [
('B',
  [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None]), ]),
('clf1',
  [('aaa', [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1']), ]),
]

testcase02i = {
'doc1': [
    ('see','hogehoge; foo','id-211','main',None),
    ('seealso','hogehoge; bar','id-212','main',None), ]
}

testcase02o = [
('H',
    [('hogehoge',
        [[],
         [('see also bar', []), ('see foo', [])],
         None
        ])
    ])
]

testcase03i = {
'doc1': [
    ('single','func1() (aaa module)','id-311','',None),
    ('single','func1() (bbb module)','id-312','',None),
    ('single','func1() (ccc module)','id-313','',None),]
}

testcase03o = [
('F',
  [('func1() (aaa module)',
    [[('', 'doc1.html#id-311')],
     [('(bbb module)', [('', 'doc1.html#id-312')]),
      ('(ccc module)', [('', 'doc1.html#id-313')])],
     None])])
]


testcase04i = {
'doc1': [
    ('single','func1() (aaa module)','id-411','',None),
    ('single','func1() (bbb module)','id-412','',None),
    ('single','func1() (ccc module)','id-413','main',None), ]
}

testcase04o = [
('F',
  [('func1() (aaa module)',
    [[('', 'doc1.html#id-411')],
     [('(bbb module)', [('', 'doc1.html#id-412')]),
      ('(ccc module)', [('main', 'doc1.html#id-413')])],
     None])])
]

#-------------------------------------------------------------------

class _domain(object):
    def __init__(self, entries):
        self.entries = entries

class _env(object):
    def __init__(self, domain):
        self.domain = {}
        self.domain['index'] = domain
    def get_domain(self, domain_type):
        return self.domain[domain_type]

class _builder(object):
    def get_relative_uri(self, uri_type, file_name):
        return f'{file_name}.html'

#-------------------------------------------------------------------

bld = _builder()

class TestcaseIndexEntries(unittest.TestCase):
    def test01_classifier(self):
        self.maxDiff = None
        dmn = _domain(testcase01i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase01o, gidx)
    def test02_see_and_seealso(self):
        self.maxDiff = None
        dmn = _domain(testcase02i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase02o, gidx)
    def test03_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase03i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase03o, gidx)
    def test04_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase04i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase04o, gidx)

#-------------------------------------------------------------------

if __name__ == '__main__':
    unittest.main()
```

### PR DESCRIPTION
**Pull request by KaKkouo**
Subject: IndexRack which is a new indexer instead of IndexEntries.

 Before posting a pull request, please choose a appropriate branch:

- Others: 4.x

### Feature or Bugfix

- Feature, Bugfix and Refactoring

### Purpose
- #9744 
  - (Bugfix) Provide an indexer that doesn't depend on whether "make clean" is used or not.
  - (Bugfix) Improved display of functions with the same name, related to group_entries and _fixre.
  - (Feature) Improved the display position of see/seealso.
- (Feature) Preliminary preparations for extensibility to create an index page that supports Japanese.
  - see: https://pypi.org/project/sphinxcontrib.kana-text/
- (Feature) Improved ease of extension related to genindex.html.
- (other) It's hoped that the following instructions will be updated.
  - `Changed in version 1.4: Index key for glossary term should be considered experimental.`
    - https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

### Detail
- IndexRack resolves #9744.
- On the branch of a forked Sphinx repository in my environment, all test is passed with circleci.

### Relates
- #9744 
- #9791
  -  If this issue triggers a change in the behavior of get_relative_uri, it needs to be addressed.
- https://github.com/KaKkouo/sphindexer
  - The following file has no differences other than the last modification and the comments.
    - sphinx/environment/adapters/indexrack.py
    - sphindexer/src/rack.py（0.5.2）
  - Current coverage: 97%.

```
Name              Stmts   Miss  Cover   Missing
-----------------------------------------------
src/__init__.py      63     34    46%   48, 51-69, 82, 85-110, 118, 126-128, 138-139
src/rack.py         317      8    97%   289-292, 499-500, 555-556
-----------------------------------------------
TOTAL               380     42    89%
```

### CODE REVIEW

**Comment by KaKkouo** [comment]
### docs/readthedocs.org:sphinx — Read the Docs build failed!

The error message is the following:

```
AssertionError: IndexRack: subterm is not null
```

I put a code for fix.

**Comment by KaKkouo** [comment]
### docs/readthedocs.org:sphinx

I found the cause of the error and fixed it.

### ci/circleci: build

I found the cause of the error and fixed it.

### any questions

Any of these will be accepted.

- this issue. (English)
- https://ja.stackoverflow.com (Japanese)
- https://github.com/KaKkouo/sphindexer/issues (English or Japanese)

If it's going to be complicated, I prefer Japanese.

**Comment by KaKkouo** [comment]
Two fails have been found. 
I apologize for the inconvenience, but please wait until it is fixed.

**Comment by tk0miya** [comment]
Thank you for your contribution. Before reviewing, please let me know why you choose the replacement strategy. Is it difficult to modify IndexEntries?

**Comment by KaKkouo** [comment]
This English sentence is written with the help of translation software. Please let me know if there are any parts that are difficult to understand. I will fix it.

### Answer

Yes, it's difficult for me to modify IndexEntries class. 

I confess, it's not that it's difficult, I don't know. But I know what kind of result we need for what kind of input. I intend to. 

p.s.
Added "Algorithm Considerations".

### Algorithm Replacement

The reason is that I couldn't think of a way to solve the "problem of index_key contents disappearing depending on whether make clean is used or not" without this algorithm. The other bugfixes and fetures are just a bonus.

- Once the gist of it would be understood , the IndexRack algorithm might be thought to be easy to add functionality to.
- The gist are as follows
  - What IndexEnty.make_index_units is doing.
  - An overview of what IndexRack is doing.
    - It is described in the IndexRack docstring.
  - How IndexRack uses IndexEntry and IndexUnit.
    1. IndexEntry is responsible for capturing the data.
    2. The IndexEntry creates the IndexUnit and passes it to the IndexRack.
    3. IndexRack processes the received IndexUnit in a good way.
    4. Finally, it creates and returns genindex data.

Originally, it was difficult to understand the process using "object.sort(key=lamba x: func(x))". At first, I didn't want to work on it, but when I compared the input and output data of IndexEntries to study unittest, I thought I understood what I wanted to do, so I worked on it. 

I am not using a database, but what I am imagining is SQL: IndexRack.__init__ and append is an insert statement, and update_units to sort_units is a select statement. The tables corresponding to IndexEntry and IndexUnit exist in my mind. I tried to use sqlite3 once, but the performance was visibly worse, so I stopped.

### Class Names

There are four classes involved in this process, and I decided to consider the relationship between the four.

- docutils.nodes.Text
- sphinx.environment.additions.indexrack.IndexEntry
  - Class corresponding to domain.entries.
- sphinx.environment.adapters.indexrack.IndexUnit
  - Class for displaying genindex.html.
- sphinx.environment.adapters.indexrack.IndexRack
  - The class that organizes IndexUnit and handles sorting.

IndexRack is named with the following points in mind.

- IndexEntry is the same as indexentries.py and the variable names used in the fetching process.
- Since we are using singular and plural variable names in the process, we want to use singular names for all class names.
   - Entry, entries, unit, units, and rack are used. They have become my favorites because they have fewer letters and are relatively close in length.
- The relationship between UNIT and RACK is not confusing because the words are familiar to those who know them.
  - There are only a few English words that I know, so it is possible that there are words that are more familiar to native speakers.

Turning IndexRack into IndexEntries is not difficult in itself; if we turn it into IndexEntries, we need to think of appropriate names for IndexEntry and IndexUnit as well. In addition, I think it is better to adjust the variable names to avoid confusion later. Of course, if there are other candidates, that's fine too.

In any case, I am not familiar with the uniformity of Sphinx as a whole. I would like to check the reasoning behind the names, but I will abide by the decision. I don't have a problem with being asked to rename a variable, for example. Consistency throughout Sphinx is important, right? But please give me some time to deal with it.

### Devices for Scalability

The following variables and method are tricks for extensibility, so it might be difficult to understand the intentions by looking at indexrack.py alone.

- textclass, entryclass, entryclass, unitclass
- get_word

In the future, I would like to implement "add_textnode" as follows.

```python
app.add_textnode(KanaText, html=(visit_kana, depart_kana))
```

* ’Kana' means kata-Kana or hira-Kana.

I need to look into how to implement add_textnode, but I think I have a good idea of the term of glossary directives. I actually created the KanaTex class, but when I try to use it in glossary, it doesn't work because TextElement redefines it by the nodes.Text class. So, I have to replace it in visit_term.

On all object of Text class,  I can't say for sure because I don't know everything that the Text class is used for.

### Additional info

I have figured out the cause of the two FAILs. It looks like the same "ёлка", but the character code was different. I know where I'm changing the character encoding, so I'm going to identify it and adjust it.

It seems to take time because I am not used to the character code like "ёлка".

### Notes

There is not much information yet, but I will try to write it in this document.

- https://sphindexer.readthedocs.io/en/latest/

**Comment by KaKkouo** [comment]
I didn't replace the files because I thought it would be easier to compare them on the same plate. It may be better to replace them in the end. If you don't mind,  I will take a git commiti/git push with the replaced files.

Also, I've changed the way the arguments are passed.

- IndexEntries(self.env).create_index(self)
- IndexRack(self).create_index()

If there is a reason for the current way of passing arguments, it is easy to change it.

**Comment by KaKkouo** [comment]
(about "ёлка")
The number of FAILs has been increased from 2 to 11...
I apologize for the inconvenience, but please be so patient.

If the only problem we need to solve is the "ёлка", you can check the rest of the behavior with "pip install sphindexer", "vi conf.py" and "make idxr".

**Comment by KaKkouo** [comment]
The test case now passes, so I'll add the test case for #9744 for now.

After that, I'll register the test cases made by unittest as needed, so it would be helpful if you check them later.

**Comment by KaKkouo** [comment]
### About Review
The following points might be useful to check.

- testcases for indexrack.py
  - the coverage of the forked sphinx
    - https://codecov.io/gh/KaKkouo/sphinx/tree/indexrack/sphinx/environment/adapters
    - It covers everything except for statements that are not executed unless you intentionally add code to them.
  - test/test_environment_indexrack.py
    - It covers all input/output as I understand it.
    - If there are any test cases that are missing, let me know and I'll add them.
  - [data structure](https://sphindexer.readthedocs.io/en/latest/structure.html)
    - The first half of the page is an input/output document.
  - IndexRack.sort_units
    -  The sort order is known by this method.
- Processing Overview
  - [sequence diagram](https://sphindexer.readthedocs.io/en/latest/seqdiag.html)
  - [action diagram](https://sphindexer.readthedocs.io/en/latest/actdiag.html)
- othres
  - I've named the methods so that you can understand what I'm doing, but it depends on my English skills.
  - The distinction between public and private method and variable names has not yet been sorted out.
  - IndexEntry and IndexUnit may need to be defined in sphinx.util.nodes.py.

My view is as follows.

- The "IndexEntries" should be expressed at least in the singular. I think "IndexEntry" is an appropriate class name for data entry processing.
  - My current favorite is "IndexRack", but given its function, "IndexManager" or "IndexControler" might be better. 
  - "IndexUnit" is the only one I can think of at the moment. It is also convenient that the variable name is short, "unit".
- If it's simply a matter of name, I think we can wrap it as "class IndexEntries(IndexRack)". In this case, the question is whether the arguments should match the current ones or not.
  - The original "IndexEntries(env).create_index(self)" was not clear, but the test case "IndexEntries(app.env).create_index(buidler)" is somewhat clear. 
  - However, even in this case, I think it would be better to use "IndexEntries(app.env, builder).create_index()" .
  - If the information in Builer is also consistent, then the current "IndexRack(builder).create_index ()" now.
- I found out that the current "IndexEntires" class is not used as a class. Aside from the name, it would be more convenient to use classes for the data input section, the data display section, and the control section of the displayed data.
- And here's the important thing.
  - The above is just a statement from someone who does not know the whole picture of Sphinx. 
  - If you can tell me what I'm missing, I think we won't have a big difference of opinion.
  -  In the first place, it has not been decided whether the proposal will be adopted or not.

Thanks for reading so far.

**Comment by KaKkouo** [comment]
### About commits

sphinx/environment/adapters/indexrack.py

- Most of the changes are intended to improve readability, so it would be good if the latest version was focused on and checked.

test/test_environment_indexrack.py

- The main change is in the display of __repr__.
- Other things, like adding test cases that I had overlooked.
- Basically, it would be good if the latest version is also confirmed here.

If you have a word before starting the review, I will restrain myself from updating it afterwards. These are basically readability improvements, not feature additions.

**Comment by KaKkouo** [comment]
# Algorithm Considerations

### IndexRack
The core of the system is the sort_units method. To make sure that this is sorted nicely, there is an update_units method. Then, the append method is used to collect the information needed by the update_units, and by checking all the data in append, the appropriate updates are made in the update_units.

### IndexEntries
It would be believed that the reason for the difficulty in processing is that we have not separated "sorting", "updates required for sorting", and "information gathering required for updating".

I haven't scrutinized the code carefully, but I think the problem of "I need to start over from `make clean` when I update the glossary containing index_key" can be handled by sorting the categroy_key in reverse order while processing. However, since "sorting", "updating", and "information gathering" are not separated, it makes it difficult to add new logic.

With IndexRack's algorithm, it is possible to add the process of "adjusting the same ideographs to have the same reading". see/seealso can be separated from other terms.

Also, regarding "When functions with the same name exist in different modules" and the first function is not split with the module name. I expect this is due to the fact that "Sort", "Update", and "Gather Information" are not split. This makes it impossible to determine if there are other functions with the same name when displaying the first function. This should not be fixable with the current algorithm.

**Comment by KaKkouo** [comment]
### about indexdomain_entries.py
I was going to use restructruedtext.parse, but I couldn't figure out how to use it. Iｔ's needed test cases that assume multiple rst files, but restructuredtext.parse does not give me the situation I expected.

Instead, I created a module that directly prepares the data that restructedtext.parse is supposed to create.

**Comment by AA-Turner** [comment]
I don't understand the reasoning behind adding this new indexer class rather than updating IndexEntries progressively--I am happy to take improvements to the indexing machinery but please make them in smaller chunks.

A

**Pull request closed without merging**
