### PR TITLE
Fix #1574: paragraphs in table cell doesn't work in Latex output

### LINKED ISSUE #1574: Paragraphs in table cell doesn't work in Latex output
A table cell containing paragraphs like this:

```
+--------------+----------+-----------+-----------+
| row 1, col 1 | column 2 | column 3  | column 4  |
+--------------+----------+-----------+-----------+
| row 2        | one                              |
| row 2        |                                  |
| row 2        | two                              |
| row 2        |                                  |
| row 2        | three                            |
+--------------+----------+-----------+-----------+
| row 3        |          |           |           |
+--------------+----------+-----------+-----------+
```

Works fine in HTML output, but doesn't work in Latex output.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1574
- Originally reported by: Peter Suter
- Originally created at: 2014-09-19T11:30:27.980

### PR DESCRIPTION
**Pull request by tk0miya**
This avoids some errors around merged cells (related with #1574).
It still has problems below:
- got cell overflow when using `\multirow`

1d975f04-aa42-11e5-8609-f430b97f6be7 
- some elements raises error (cf. `\itemize`)

But, it can reduce errors. I believe this is better way at this moment.

### CODE REVIEW

**Comment by shirou** [comment]
I confirmed following table can be passed by this PR.

```
+--------------+----------+-----------+-----------+
| row 1, col 1 | column 2 | column 3  | column 4  |
+--------------+----------+-----------+-----------+
| row 2        | one                              |
| row 2        |                                  |
| row 2        | two                              |
| row 2        |                                  |
| row 2        | three                            |
+--------------+----------+-----------+-----------+
| row 3        |          |           |           |
+--------------+----------+-----------+-----------+
```

**Comment by jj1bdx** [comment]
:+1: for this patch. No adversary effect found in compiling this case: https://github.com/jj1bdx/sphinx-latex-table-test

**Comment by tk0miya** [comment]
@shirou @jj1bdx Thank you for reviewing. I'll merge this (tonight or tomorrow)

**Comment by jfbu** [comment]
This has been fixed again in a different way at 74b4650 (PR #3435, Sphinx 1.6).

**Pull request merged**
