### PR TITLE
DOC: Add favicon

### PR DESCRIPTION
**Pull request by mgeier**
I think the Sphinx docs should have their own favicon.

### CODE REVIEW

**Comment by mgeier** [comment]
If you would switch on the "Build pull requests for this project" on RTD (under "Admin" -> "Advanced Settings"), we could have a preview.

**Review by tk0miya — APPROVED** [review]
LGTM!! Before merging, please let me know where this favicon comes from? I'd like to know the license and copyright of this file.

**Comment by tk0miya** [comment]
>If you would switch on the "Build pull requests for this project" on RTD (under "Admin" -> "Advanced Settings"), we could have a preview.

Note: I enabled the feature now. So it will be invoked from the next PR. I looked the favicon at your repository directly:
https://github.com/mgeier/sphinx/blob/doc-favicon/doc/_static/favicon.svg

**Comment by mgeier** [comment]
> please let me know where this favicon comes from?

I've created it myself with [Inkscape](https://inkscape.org/) by auto-tracing the image from the Sphinx website: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png and then hand-editing it a bit.

> I'd like to know the license and copyright of this file.

Same as any of my contributions.

> > [...] "Build pull requests for this project" [...]
> 
> Note: I enabled the feature now.

Thanks!

> So it will be invoked from the next PR.

I tried forcing it by closing and re-opening this PR, but it didn't work ...

> I looked the favicon at your repository directly:
> https://github.com/mgeier/sphinx/blob/doc-favicon/doc/_static/favicon.svg

It's important to look at the scaled-down version that the browser actually shows.
If the lines are too close to each other, they appear fused together, that's why I used such a big space below the upper line.

Probably some more fine-tuning would be possible, but I think it already looks recognizable now.

**Comment by tk0miya** [comment]
Thank you for confirmation. I also need to modify the setting of webhook. And it seems working now.

**Comment by tk0miya** [comment]
>I've created it myself with Inkscape by auto-tracing the image from the Sphinx website: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png and then hand-editing it a bit.

Perfectly understand. Good work!

**Comment by mgeier** [comment]
Thanks, now it works: https://sphinx--8334.org.readthedocs.build/en/8334/

**Comment by tk0miya** [comment]
🎉

**Comment by tk0miya** [comment]
Just merged. Thank you for your cool work

**Pull request merged**
