### PR TITLE
refactor: linkcheck: Skip queuing ignored URIs

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Refactoring

### Purpose
- To make checker-thread simpler, this checkes the URI is ignored before
queueing.
- This is an alternative of #8774

### CODE REVIEW

**Review by francoisfreitag — DISMISSED** [review]
Thanks! I was seeing the post transform as the place to perform the triage, but since the builder outputs the result, best keep the triage logic in the builder.

---
Nit in commit message, checkes -> checks.

**Comment by francoisfreitag** [comment]
How does this change relate to #8806? If the checker is extracted, I believe the ignore list should be part of the checker and not the builder?

**Comment by tk0miya** [comment]
Thank you for reviewing.

>If the checker is extracted, I believe the ignore list should be part of the checker and not the builder?

Yes, it will be moved into the checker after merging this.

**Comment by tk0miya** [comment]
Just updated > commit message.

**Review by francoisfreitag — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for reviewing!

**Pull request merged**
