### PR TITLE
update Sphinx Simplified Chinese translation

### PR DESCRIPTION
**Pull request by dpy013**
> Subject: Update Simplified Chinese translation (but can't use Transifex)
> 
> ### Feature
> Have 100% Simplified Chinese translated strings.
> 
> ### Purpose
> This PR adds missing string, homogenize translations and fix typos, orthographic issues and changes some words to good ones.
> 
> I know translations must be done by Transifex, but Transifex does not allow blind people tu use their services. So I can't use this way.
thanks

### CODE REVIEW

**Comment by tk0miya** [comment]
Thank you for your contribution. Could you post this into the sphinx-users group and ask for help, please?
Thanks,

**Comment by dpy013** [comment]
> Thank you for your contribution. Could you post this into the sphinx-users group and ask for help, please?
> Thanks,

hi
Can the address of the sphinx-users group be sent?
thanks

**Comment by tk0miya** [comment]
Here is our groups :-)
https://groups.google.com/forum/#!forum/sphinx-users

**Comment by dpy013** [comment]
[update Sphinx Simplified Chinese](https://groups.google.com/forum/#!topic/sphinx-users/hpJqE7FhpwQ)

**Comment by dpy013** [comment]
@tk0miya 
Can the current PR be reviewed?
thanks

**Comment by tk0miya** [comment]
Unfortunately, I can't merge this because we manage all translations on transifex.com. So we need to update translations on transifex instead of GitHub.

**Pull request closed without merging**
