### PR TITLE
Fix duplicated toc in epub3 output

### PR DESCRIPTION
**Pull request by shibukawa**

### CODE REVIEW

**Comment by tk0miya** [comment]
Sorry, I can't evaluate this PR.
Could you tell me what this PR changes, or the specifications related with this?
Then, I'll take a look.

**Comment by shibukawa** [comment]
- http://www.idpf.org/accessibility/guidelines/content/xhtml/toc.php

`toc.xhtml` contains "table of contents".  epub3 spec says,  `toc.xhtml` is optional in spine elements(this list specifies page order). The following document recommended getting rid of `toc.xhtml` from spine elements.
- http://www.darkcurrant.com/ebook/epub_template_howto_epub3.html#06e (Japanese)

Sphinx generates toc at `toctree` directive. So adding `toc.xhtml` to spine elements generates duplicated toc.

**Comment by tk0miya** [comment]
Thank you for information. I understand what this PR does. LGTM!

Note:
The `nav.xhtml` is still distributed as a part of EPUB document, because it is included in `<manifest>` tag.
The file is used for "EPUB Navigation Document". In epub3 spec, it is required resource.
ref: http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-item-property-values

**Comment by tk0miya** [comment]
@takuan-osho do you have any comments? If none, I will merge this.

**Comment by takuan-osho** [comment]
@tk0miya This PR is reasonable and LGTM too.

**Comment by tk0miya** [comment]
Okay. I will merge this after the conflict is resolved.

**Comment by tk0miya** [comment]
Merged! Thank you always :-)

**Pull request merged**
