### PR TITLE
Remove future imports

### PR DESCRIPTION
**Pull request by stephenfin**
These are not necessary in Python 3.

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
LGTM, but travis raises an error.
Could you check it please?

**Comment by stephenfin** [comment]
> LGTM, but travis raises an error.
> Could you check it please?

I can't figure out what's happening here. I've simply inserted a TODO to investigate this in the future.

**Comment by tk0miya** [comment]
OMG, I found the reason. We've used mypy under py2 mode because it typeshed contains broken typehints for docutils. As a result, it does not support `file` parameter for `print()` function.

BTW, I feel `f.write()` is better to write data to a file. How about replace `print()` calls by it?

**Comment by stephenfin** [comment]
> OMG, I found the reason. We've used mypy under py2 mode because it typeshed contains broken typehints for docutils. As a result, it does not support `file` parameter for `print()` function.
> 
> BTW, I feel `f.write()` is better to write data to a file. How about replace `print()` calls by it?

Yes, that's one problem and I can fix this. There is another problem in `tests/roots/test-ext-viewcode-find/not_a_package/__init__.py` though.

https://github.com/sphinx-doc/sphinx/blob/e781747f618e25a533da20185374640720e6ee72/tests/roots/test-ext-viewcode-find/not_a_package/__init__.py#L1-L2

Do you have any idea why this is failing?

**Comment by jdufresne** [comment]
Now that mypy is running with Python3, this could be rebased and completed.

**Comment by stephenfin** [comment]
> Now that mypy is running with Python3, this could be rebased and completed.

Done. I still don't know why I need to keep the future import in that one test case, but it's otherwise working as expected.

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for update. Let's go ahead. And I'll take a look about last piece later.

**Comment by tk0miya** [comment]
I post #5824 for it.

**Pull request merged**
