### PR TITLE
Fix #4186: LaTeX: Support upLaTeX as a new latex_engine (experimental)

### LINKED ISSUE #4186: Feature Request: support ``upLaTeX`` for PDF builds of Japanese projects
Many projects will use Unicode characters. Sphinx uses ``pLaTeX`` for Japanese documents but ``pLaTeX`` is not Unicode aware. 

It appears [upLaTeX](http://www.t-lab.opal.ne.jp/tex/uptex_en.html) adds Unicode support and can help handling problems with stray Unicode characters: in particular using `\usepackage[utf8]{inputenc}` and `babel` is possible  with `upLaTeX`. From the little I understand it is easier with ``upLaTeX`` to have mixed languages documents, for example with parts in English and others in Japanese.

Currently one can induce Sphinx into using ``upLaTeX`` via this ``latexmkjarc`` file in the repertory of the project

```
$latex = 'uplatex ' . $ENV{'LATEXOPTS'} . ' %O %S';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'rm -f %D; upmendex -f -d %B.dic -s python.ist %S || echo "upmendex exited with error code $? (ignoring)" && : >> %D';
add_cus_dep( "glo", "gls", 0, "makeglo" );
sub makeglo {
 return system( "upmendex -s gglo.ist -o '$_[0].gls' '$_[0].glo'" );
}
```

and an ``latex_additional_files = ['latexmkjarc']`` line in ``conf.py``. I am not sure the options to  ``uplatex`` and ``upmendex`` above are optimal. I just took the current file which uses ``platex`` and ``mendex`` and dropped options not existing for  ``uplatex/upmendex``.

But we also need extra ``uplatex`` option in document class in case of ``'manual'`` type (which uses ``jsbook.cls``). 

This option does not work for ``'howto'`` documents and one must use ``ujreport.cls`` as replacement for ``jreport.cls``. Currently this setting appears to require some monkey-patch by user of sphinx.builders.latex's ``default_latex_docclass``. (see https://github.com/sphinx-doc/sphinx/issues/4136#issuecomment-338802296)

Perhaps ``hyperref`` options for the encoding of PDF strings (particularly, bookmarks) is perhaps not good with ``upLaTeX``. Currently ``sphinx.sty`` contains this logic:

```
% to make pdf with correct encoded bookmarks in Japanese
% this should precede the hyperref package
\ifx\kanjiskip\undefined
% for non-Japanese: make sure bookmarks are ok also with lualatex
  \PassOptionsToPackage{pdfencoding=unicode}{hyperref}
\else
  \RequirePackage{atbegshi}
  \ifx\ucs\undefined
    \ifnum 42146=\euc"A4A2
      \AtBeginShipoutFirst{\special{pdf:tounicode EUC-UCS2}}
    \else
      \AtBeginShipoutFirst{\special{pdf:tounicode 90ms-RKSJ-UCS2}}
    \fi
  \else
    \AtBeginShipoutFirst{\special{pdf:tounicode UTF8-UCS2}}
  \fi
\fi
```

I don't know if this is the good thing to do for `upLaTeX`. (I don't even know if it is so good for `pLaTeX`,  for example I noticed there are problems with EN DASH).

Adding ``upLaTeX`` support could be good in particular for localization to Japanese of documents when localization is only partial. The CPython docs is an example.

### Relates

the discussion at #4136

### Environment info

- Sphinx version: 1.6.5

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Feature

### Purpose
- refs: #4186 
- I'm not familiar with LaTeX and Japanese LaTeX. So I don't know this is appropriate settings. But it seems working fine to me.

### CODE REVIEW

**Review by jfbu — COMMENTED** [review]
Unfortunately I know nothing about uplatex and Japanese language... what about using [upmendex](https://ctan.org/pkg/upmendex) as indexing tool?

but +1 anyway as best way to test is to at least add this new possibility for `latex_engine`...

**Comment by tk0miya** [comment]
Unfortunately, ubuntu LTS does not contain upmendex (since TeXLive 2016). So it is better to switch to it in another time.
https://packages.ubuntu.com/search?suite=xenial&arch=any&mode=exactfilename&searchon=contents&keywords=upmendex

**Review by jfbu — APPROVED** [review]
LGTM! thanks for Ubuntu xenial link. Indeed I had not checked.

**Comment by tk0miya** [comment]
Now I'm merging this. I still don't know this fix is enough or not. But we can improve this even after shipping :-)

**Pull request merged**
