### PR TITLE
Make Config and BuildEnvironment pickable

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Refactoring

### Purpose
- Add `__getstate__()` and `__setstate__()` helper to make `Config` and `BuildEnvironment` pickable
- It makes them simple and easy to understand

### CODE REVIEW

**Review by shimizukawa — APPROVED** [review]
LGTM ;)

Using `__getstate__` and `__setstate__` for pickling is in favor. It's also good to deprecate the `frompickle` class method.
I'm a little worried that the process of pickle/unpickle environment object has been distributed to `application.py` and `builders/__init__.py`, but I think that is not a problem.

**Comment by tk0miya** [comment]
Thank you for reviewing.
Certainly pickling and unpickling methods are placed both in app and in builder. I agree that is asymmetrical and not a good design. Is it better to add methods for storing and restoring?
Then nobody have to know how to serialize the environment object.
I know the pickle library is standard, so I might not worry so much.

**Comment by shimizukawa** [comment]
I might not worry so much, too.

**Comment by tk0miya** [comment]
Okay, let's go with this.
Thank you for comment!

**Pull request merged**
