### PR TITLE
autodoc_mock_imports vs suppressing import warnings

### PR DESCRIPTION
**Pull request by peterjc**
Documentation improvement to address #4182 (see discussion there).

### CODE REVIEW

**Comment by tk0miya** [comment]
I feel a bit strange. All warnings from Sphinx indicates something goes wrong. The warnings from autodoc you'd seen is one of them. So I feel this update is not needed.

**Comment by peterjc** [comment]
Sometimes you expect an import to fail, so it might (at first) seem correct to silence this warning. e.g. My code code uses library A under Python 2, but library B under Python 3. Here it seems using mock is the best solution.

**Comment by tk0miya** [comment]
I know some warnings are intended as you said. So I feel suppressing is enough worthy for us, so I will implement it in nearly days.

BTW, what I meant is all of warning are as same as important. I don't feel autodoc's one is especially important. so it is not needed to mention here.

In addition, autodoc is not related with `suppress_warnings` at this moment.

**Comment by tk0miya** [comment]
I'm closing this now because there are no reason to give a special treatment for autodoc in `suppress_warnings` configuration.
Thanks,

**Pull request closed without merging**
