### PR TITLE
Document workaround for "RuntimeError: maximum recursion depth exceeded"

### PR DESCRIPTION
**Pull request by timgraham**
As suggested in https://groups.google.com/d/topic/sphinx-dev/MtRf64eGtv4/discussion.

If there's a better spot in the docs to put this, let me know.

### CODE REVIEW

**Comment by birkenfeld** [comment]
Why not emit this hint as a message when we catch the exception at runtime?

**Comment by timgraham** [comment]
It could be done. I'm not sure it affects enough projects that it's a high priority given the complexity of that solution though.

**Comment by birkenfeld** [comment]
I don't mind how many cases it actually affects (at least two) - interpreting the exception is easy and a good way to be more user friendly.

**Comment by timgraham** [comment]
All right, I'll close this then. At least it can be found by search engines for now.

**Comment by birkenfeld** [comment]
I was hoping you'd update the patch :)

**Pull request closed without merging**
