### PR TITLE
Add CONTRIBUTING file

### PR DESCRIPTION
**Pull request by mgeier**
This way, it should appear on Github as "guidelines for contributing".

### CODE REVIEW

**Comment by tk0miya** [comment]
Did you update `CONTRIBUTING.rst`? Only renaming?

**Comment by jfbu** [comment]
the old devguide appears as symlink on my checkout of the branch: is this compatible with all systems (windows?)

**Comment by jfbu** [comment]
you can add 

```
[remote "jfbu"]
	url = https://github.com/jfbu/sphinx.git
	fetch = +refs/heads/contributing_nosymlink:refs/remotes/jfbu/contributing_nosymlink
```
to your `.git/config` to fetch my branch (if @tk0miya approves this is the way to go).

**Comment by jfbu** [comment]
https://github.com/jfbu/sphinx/commit/10da061a9ad72314d034acaf418add27dc8aafde is on top of your PR. I also included a fix typo commit which was merged into stable after you did your PR, and which is needed to test building of docs.

see https://github.com/jfbu/sphinx/commits/contributing_nosymlink, which you can fetch and merge (perhaps).

**Comment by jfbu** [comment]
by the way, README.rst also contains the info about `stable` versus `master`.

and this is what one sees at bottom of https://github.com/sphinx-doc/sphinx

**Comment by jfbu** [comment]
I am neither pro nor con but as `README.rst` already has a small Contributing section (which is reproduced as a section of `devguide.rst` actually), an alternative would be to add to `README.rst` something like

    For more info about contributing, refer to doc/devguide.rst

with possibly an html link to online documentation.

**Comment by mgeier** [comment]
I've just renamed the file and created a symlink. The Github diff viewer doesn't really show that.

I've read that symbolic links are supported since Windows Vista, but I don't know if that's true.

If you prefer the `include` directive, feel free to use your commits.
Or do you want me to include this here?

IMHO, both `README.rst` and `devguide.rst` are the wrong place for this, it should be in `CONTRIBUTING.rst` (in the main directory).

**Comment by jfbu** [comment]
already AUTHORS, CHANGES, and EXAMPLES are included in documentation using ``.. include::`` directive. I trust CONTRIBUTING should follow suit, if the contents of `devguide.rst` are moved to it. By the way perhaps a `:tocdepth: 2` should be there to, but not sure, time for me to read Sphinx docs ;-).

Yes I was meaning that you could fetch from my repo, then you merge into in your branch and push to this PR. Only a suggestion, but I am somewhat expecting symlinks should be avoided.

**Comment by tk0miya** [comment]
I see. +1 for merging.
To use symlink or not to use, I'd like to hear advice from @shimizukawa . Because he uses windows.

**Comment by tk0miya** [comment]
refs: #3222

**Review by shimizukawa — APPROVED** [review]
+1

**Comment by jfbu** [comment]
@shimizukawa then we should perhaps reduce the bottom of README.rst (about testing and contributing) in order not to have to maintain same info at different locations. Something like, 

    Developers: see CONTRIBUTING file.

**Comment by shimizukawa** [comment]
@jfbu yeah, I think so too. I'll do it.

**Comment by shimizukawa** [comment]
Done: https://github.com/sphinx-doc/sphinx/tree/stable

**Comment by jfbu** [comment]
+1 merged into master

**Comment by jfbu** [comment]
for the record, after this PR #3252 was merged the symlink was ultimately removed and replaced by use of include directive at d876b11.

**Comment by shimizukawa** [comment]
I'm sorry, I replaced it. I thought symlink would be nice, but in Windows environment I encountered an incomprehensible error when building the document.

**Pull request merged**
