### PR TITLE
Fix #5291: autodoc crashed by ForwardRef types

### LINKED ISSUE #5291: WARNING: error while formatting arguments for xxx.XXX: 'ForwardRef' object has no attribute '__origin__' on python 3.7
Subject: WARNING: error while formatting arguments for xxx.XXX: 'ForwardRef' object has no attribute `'__origin__'` on python 3.7

### Problem
- This warning is raised on python3.7 with autodoc of the below code and type hints does not made in output.

```python
from typing import Optional

class Node(object):
    """Node class."""

    def __init__(self, parent_node: Optional['Node']) -> None:
        self._parent = parent_node
```

#### Procedure to reproduce the problem
```
git clone https://github.com/miyakogi/sphinx_py37
cd sphinx_py37
(make new venv and install sphinx if needed)
cd docs
make html
```

#### Error logs / results

Output:

```
WARNING: error while formatting arguments for sphinx_py37.Node: 'ForwardRef' object has no attribute '__origin__'
```

And type hints are not exist in the output HTML.

#### Expected results

No warning and type hints in the result.

### Reproducible project / your project
- https://github.com/miyakogi/sphinx_py37

### Environment info
- OS: Linux (Arch Linux) and Windows 10 home
- Python version: 3.7.0
- Sphinx version: 1.7.6 and 1.8.0.dev20180813

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #5291

### CODE REVIEW

**Comment by terrisgit** [comment]
I'm getting this error in 1.8.0b1 (in both python 3.6 and 3.7) whereas 1.7.7 works fine. Thus concludes my experiment with 1.8.0 beta.

**Comment by tk0miya** [comment]
@terrisgit Really? I also received bug reports both in 1.7.7 and 1.8.0b1 (see #5322). But I've never hear the trouble only 1.8.0b1.
I'd like to know about your case in detail. Could you file an issue please?

**Comment by terrisgit** [comment]
My code is not open source and therefore I might not be able to submit any bug reports. I know it is frustrating to get vague reports. Please ignore this. I am posting for the benefit of people searching for such issues who might be able to submit a real bug report.

*Bug 1*

Sphinx 1.8.0b1, Python 3.6.6 and Python 3.7.0 when using make latexpdf and make html:

```
WARNING: error while formatting arguments for edcexport.controller.ravesender.RaveSender.send: '_Any' object has no attribute '__origin__' 
```

This function is defined as:

async def send(cls, message: Message, results: Dict[str, Any]) -> None:

*Bug 2*

This bug does not appear in Python 3.6.6 and instead the above warning appears when using make html.

Sphinx 1.80b1, Python 3.7.0 when using make html --

```
File "/.venv/lib/python3.7/site-packages/docutils/writers/_html_base.py", line 399, in set_class_on_child child['classes'].append(class_) TypeError: string indices must be integers
```

There is a traceback:

```
# Sphinx version: 1.8.0b1
# Python version: 3.7.0 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   writing output... [ 36%] api/edcexport.controller.edcexceptions
#
#   writing output... [ 39%] api/edcexport.controller.notifier
#
#   writing output... [ 41%] api/edcexport.controller.ravesender
#
#   writing output... [ 43%] api/edcexport.controller.taskmanager
#
#   writing output... [ 46%] api/edcexport.controller.workflow
#
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.0b1) from /Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.11) from /Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.0b1) from /Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (1.8.0b1) from /Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
Traceback (most recent call last):
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 350, in build_update
    len(to_build))
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 415, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 596, in write
    self._write_serial(sorted(docnames))
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 607, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/builders/html.py", line 730, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/sphinx/writers/html.py", line 58, in translate
    self.document.walkabout(visitor)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 4 more times]
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/writers/html4css1/__init__.py", line 402, in visit_field_body
    self.set_class_on_child(node, 'first', 0)
  File "/Users/terris//edc-export-service/.venv/lib/python3.7/site-packages/docutils/writers/_html_base.py", line 399, in set_class_on_child
    child['classes'].append(class_)
TypeError: string indices must be integers
```

**Comment by terrisgit** [comment]
Bug 1 went away in the final 1.8.0 release. Bug 2 is Napoleon related - #5426

**Pull request merged**
