### PR TITLE
Fix #5335: quickstart: escape sequence has been displayed with MacPorts' python

### LINKED ISSUE #5335: quickstart: escape sequence has been displayed with MacPorts' python
### Problem
- quickstart: escape sequence has been displayed with MacPorts' python
- reported by @cocoatomo 

```
(venv) [tomohiko@Luna prompt]$ sphinx-quickstart 
Welcome to the Sphinx 1.7.6 quickstart utility.
Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).
Selected root path: .
You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
[35m> Separate source and build directories (y/n) [n]: [39;49;00m
[Interrupted.]
```

#### Procedure to reproduce the problem
Invoke `sphinx-quickstart` simply.

#### Expected results
All questions are colored.

### Environment info
- OS: Mac
- Python version: 3.7.0 (installed with MacPorts)
- Sphinx version: 1.7.6

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #5335

### CODE REVIEW

**Comment by tk0miya** [comment]
@cocoatomo Could you check this please?

**Comment by cocoatomo** [comment]
I have tried installing Sphinx and execute `sphinx-quickstart` command, but there is no improvement.

```
[tomohiko@Luna sphinx]$ git remote add tk0miya https://github.com/tk0miya/sphinx.git
[tomohiko@Luna sphinx]$ git fetch --all
[tomohiko@Luna sphinx]$ git checkout -t tk0miya/5335_quickstart_for_libedit
Branch '5335_quickstart_for_libedit' set up to track remote branch '5335_quickstart_for_libedit' from 'tk0miya'.
Switched to a new branch '5335_quickstart_for_libedit'
[tomohiko@Luna sphinx]$ python3.7 -m venv venv
[tomohiko@Luna sphinx]$ . venv/bin/activate
(venv) [tomohiko@Luna sphinx]$ python setup.py install
...
Using /Users/tomohiko/MyRepos/Python/sphinx/venv/lib/python3.7/site-packages
Finished processing dependencies for Sphinx==1.7.8.dev20180823
...
(venv) [tomohiko@Luna esc]$ sphinx-quickstart 
Welcome to the Sphinx 1.7.8+ quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
[35m> Separate source and build directories (y/n) [n]: [39;49;00m
[Interrupted.]
```

```
(venv) [tomohiko@Luna sphinx]$ python
Python 3.7.0 (default, Jun 28 2018, 05:55:06) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
>>> input('\x01\x1b[35m\x02Hello world\x01\x1b[39;49;00m\x02')
[35mHello world[39;49;00m
''
>>> readline.__doc__
'Importing this module enables command line editing using libedit readline.'
```

**Comment by tk0miya** [comment]
Oh, sorry. I found this error came from the combination of libedit's `input()` function and escape sequence.
I just updated this PR not to color prompt on these environment.
Could you try this again please?

**Comment by cocoatomo** [comment]
I just tried and found different result as following.

```
[tomohiko@Luna sphinx]$ git checkout -t tk0miya/5335_quickstart_for_libedit
Branch '5335_quickstart_for_libedit' set up to track remote branch '5335_quickstart_for_libedit' from 'tk0miya'.
Switched to a new branch '5335_quickstart_for_libedit'
[tomohiko@Luna sphinx]$ python3.7 -m venv venv
[tomohiko@Luna sphinx]$ . venv/bin/activate
(venv) [tomohiko@Luna sphinx]$ python setup.py install
...
Finished processing dependencies for Sphinx==1.7.8.dev20180825
(venv) [tomohiko@Luna sphinx]$ cd /tmp/
(venv) [tomohiko@Luna tmp]$ mkdir sample
(venv) [tomohiko@Luna tmp]$ cd sample/
(venv) [tomohiko@Luna sample]$ sphinx-quickstart 
Welcome to the Sphinx 1.7.8+ quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: 

Inside the root directory, two more directories will be created; "_templates"
for custom HTML templates and "_static" for custom stylesheets and other static
files. You can enter another prefix (such as ".") to replace the underscore.
> Name prefix for templates and static dir [_]: 

The project name will occur in several places in the built documentation.
> Project name: sample
> Author name(s): cocoatomo
> Project release []: 0.0.0

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
http://sphinx-doc.org/config.html#confval-language.
> Project language [en]: 

The file name suffix for source files. Commonly, this is either ".txt"
or ".rst".  Only files with this suffix are considered documents.
> Source file suffix [.rst]: 

One document is special in that it is considered the top node of the
"contents tree", that is, it is the root of the hierarchical structure
of the documents. Normally, this is "index", but if your "index"
document is a custom template, you can also set this to another filename.
> Name of your master document (without suffix) [index]: 

Sphinx can also add configuration for epub output:
> Do you want to use the epub builder (y/n) [n]: 
Indicate which of the following Sphinx extensions should be enabled:
> autodoc: automatically insert docstrings from modules (y/n) [n]: 
> doctest: automatically test code snippets in doctest blocks (y/n) [n]: 
> intersphinx: link between Sphinx documentation of different projects (y/n) [n]: 
> todo: write "todo" entries that can be shown or hidden on build (y/n) [n]: 
> coverage: checks for documentation coverage (y/n) [n]: 
> imgmath: include math, rendered as PNG or SVG images (y/n) [n]: 
> mathjax: include math, rendered in the browser by MathJax (y/n) [n]: 
> ifconfig: conditional inclusion of content based on config values (y/n) [n]: 
> viewcode: include links to the source code of documented Python objects (y/n) [n]: 
> githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]: 

A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build
directly.
> Create Makefile? (y/n) [y]: 
> Create Windows command file? (y/n) [y]: 

Creating file ./conf.py.
Creating file ./index.rst.
Creating file ./Makefile.
Creating file ./make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file ./index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.
```
screen shot 2018-08-25 at 15 02 59
screen shot 2018-08-25 at 15 03 35

```
(venv) [tomohiko@Luna sample]$ python
Python 3.7.0 (default, Jun 28 2018, 05:55:06) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
>>> input('\x01\x1b[35m\x02Hello world\x01\x1b[39;49;00m\x02')
[35mHello world[39;49;00m
''
>>> readline.__doc__
'Importing this module enables command line editing using libedit readline.'
```

Of course, the behaviour of "Ctrl+U" is not changed.

**Comment by tk0miya** [comment]
Thank you for confirmation!
Merged.

**Pull request merged**
