### PR TITLE
Fix #8099: autodoc: NameError is raised when script uses TYPE_CHECKING

### LINKED ISSUE #8099: sphinx 3.2.0: trouble with `typing.get_type_hints`
Since 3.2.0, I cannot apply sphinx on my project (neither on Travis-CI nor locally):

```
Exception occurred:
  File "<string>", line 1, in <module>
NameError: name 'typingtools' is not defined
```
`typingtools` is module only required for typing purposes. Hence, I import it as follows:

```
if TYPE_CHECKING:
    from hydpy.core import typingtools
```

The problem starts in method `AttributeDocumenter.add_directive_header()` in line ```annotations = get_type_hints(self.parent)```.

If I apply the following manually, I get the same error:

```
import typing
from hydpy.models.arma.arma_control import Responses
typing.get_type_hints(Responses)
```

When I add module `typingtools` to the local variables, everything seems to work:

```
import typing
from hydpy.core import typingtools
from hydpy.models.arma.arma_control import Responses
typing.get_type_hints(Responses, localns={'typingtools': typingtools})
```

My project: https://github.com/hydpy-dev/hydpy/tree/develop.

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #8099 
- `typing.get_type_hints()` raises NameError when the target object
contains unresolavable type annotation (ex. TYPE_CHECKING).  This
handles the exception and use unresolved annotations for type hints.

### CODE REVIEW

**Comment by rudolfbyker** [comment]
Is there any way to get resolved annotations with `TYPE_CHECKING`?

**Comment by tk0miya** [comment]
Please post your super cool patch!

**Comment by rudolfbyker** [comment]
Is that another way of saying "No, but we could if you implemented it"? If not, I don't understand your last message.

**Comment by tk0miya** [comment]
Yes. I don't have the knowledge to implement it. So somebody's help is needed to realize it.

**Pull request merged**
