### PR TITLE
Migrate registry

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Refactor

### Purpose
- Make application class simple
- Do not store components to global (or class variables)

### Relates
- #4259

### CODE REVIEW

**Comment by stephenfin** [comment]
There isn't enough information in the pull request or commit messages for me to understand and review this properly, but it looks OK from a high level?

**Comment by tk0miya** [comment]
As I commented in other PR, migrating component stores to registry reduces to use class variables and global variables.
In this PR, a large change is a code around translators. So far, sphinx transplants methods to classes directly on adding nodes. With this PR, it transplants methods on instantiation. So class are not modified.

Note: I have to update this PR. because travis fails...

**Comment by tk0miya** [comment]
I just reverted last commit because of trouble. I'll work it in another PR.

**Comment by tk0miya** [comment]
All errors are fixed now. I will merge this soon if no objection.

**Pull request merged**
