### PR TITLE
Pre-compile more regular expressions

### PR DESCRIPTION
**Pull request by AA-Turner**

### CODE REVIEW

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
Wait don't do this, python already caches regex compilation

**Comment by chrisjsewell** [comment]
You should literally do the opposite, this just makes sphinx start slower 😅

**Comment by chrisjsewell** [comment]
see: https://github.com/python/cpython/blob/ef10110cd781afe8ddd3e65a54dc2b5ed2cb3187/Lib/re/__init__.py#L321-L328

**Comment by AA-Turner** [comment]
> Wait don't do this, python already caches regex compilation

But only up to a limit (100ish from memory), and we use a lot of regexes.
Full transparency: I haven't profiled this, so entirely possible the cache is doing its job.

A

**Comment by chrisjsewell** [comment]
> Full transparency: I haven't profiled this, so entirely possible the cache is doing its job.

512, thats= quote a lot, but thats what I would suggest, at least lazy compile; compiling 100s of regexes just to import sphinx I don't think is any better

**Comment by timhoffm** [comment]
FYI the python regex cache is a LRU cache (*) so that the least used expressions will be dropped first. As long as you don't have > 512 regexps that are used multiple times, there's no benefit in precompiling. And even beyond that, the delay will only set in slowly, because you'll only recomile the least used regexps.

I agree with @chrisjsewell that the danger of loosing performance due to precompiling expressions that are not needed for that run is substantial and likely outweighs a performance gain. In the end, only closer inverstigation could tell. OTOH since this PR only precompiles 10 regexps, it should not make a substantial difference either way.

(*) technically it's a two-stage cache with a 256-element FIFO first stage, which is faster, and a second 512-element LRU stage to keep hit rate up.

**Pull request closed without merging**
