### PR TITLE
quickstart: Simplify generated conf.py (for texinfo)

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Feature

### Purpose
- refs: #4256
- This removes texinfo_documents
- This is another version of #5384

### CODE REVIEW

**Comment by tk0miya** [comment]
any comment? if nothing, I'll merge this.

**Review by jfbu — APPROVED** [review]
LGTM, but disclaimer: I am not too familiar with texinfo usage at all!

**Comment by tk0miya** [comment]
ping @shimizukawa. Would you like to add a hyperlink to the our document also?

**Comment by tk0miya** [comment]
@jfbu Thank you for comment. I'm also not familiar with texinfo.
My large concern is that it's okay or not to remove `*_documents` variable from conf.py by default.

**Comment by tk0miya** [comment]
Okay, go ahead :-)

**Pull request merged**
