### PR TITLE
Fixes upper characters problem in German HTML search

### PR DESCRIPTION
**Pull request by derdennis**
### Feature or Bugfix
- Bugfix

### Purpose

We noticed some HTML search glitches in our internal documentation when searching for uppercase parameters like `PAR_APP_TITLE` or `FOO_BAR`. Searching for these returned no results while the words were clearly visible on the pages. 

We found PR #4396 (Grâce à la France!) and applied the same fix to the German stemmer, regenerated the `de.pyc` file and everything started to work as expected after the next `build html`.  

### Detail

Please see the attached [index.txt](https://github.com/sphinx-doc/sphinx/files/1931054/index.txt) for a minimal example when used with a freshly created `sphinx-quickstart` German language (de) project. To reproduce please rename to `index.rst`, GitHub would not let me upload `.rst`-files...

Maybe this also applies to more languages than French and German? Is it possible to catch this behaviour via unit tests?

Please apply this PR to the following versions of this fantastic documentation system.

Thank you everybody for your great work.

Dennis
  
### Relates
- Issue #1922 
- PR #4396

### CODE REVIEW

**Comment by derdennis** [comment]
Please excuse me, it seems I included *a lot* commits from other people in this PR. 

The actual fix for the German HTML search is only in [this commit](https://github.com/sphinx-doc/sphinx/pull/4867/commits/4e32df4e96010c6cfe725fe4d39f0ee59f8925db).

Is it possible to get this seperated? Can I help with that or does this need a maintaner?

Sorry for the trouble.

Dennis

**Review by tk0miya — CHANGES_REQUESTED** [review]
Unfortunately, this PR contains many other changes.
It seems you made this PR from master branch, not 1.7 branch.
Could you update this please?

**Comment by derdennis** [comment]
It seems I can't figure out how to fix this PR. Sorry. Will close and create new one from the correct branch.

**Comment by derdennis** [comment]
Created PR #4871, sorry for the mess.

**Pull request closed without merging**
