### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by plaindocs**
Subject: Add intersphinx requirement

### Feature or Bugfix

- Bugfix

### Purpose

Looks like you need intersphinx to use sphinx-intl

### CODE REVIEW

**Comment by plaindocs** [comment]
Sorry about the extra commit noise. I'm only referring to 22e7920

**Comment by tk0miya** [comment]
Really? If my understanding correct, sphinx-intl does not depend on intersphinx. Please let me know what happened in your environment in detail.

**Comment by plaindocs** [comment]
Thanks for the speedy reply! 

I'm investigating the possibility of translating some of the WTD website (https://github.com/writethedocs/www/issues/1155) and following the [Quick Guide](http://www.sphinx-doc.org/en/master/usage/advanced/intl.html)

Running `make gettext` gives me:

```
Traceback (most recent call last):
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/builders/gettext.py", line 263, in build
    I18nBuilder.build(self, docnames, summary, method)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/docutils/transforms/__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/transforms/__init__.py", line 408, in apply
    self.app.emit('doctree-read', self.document)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/ablog/post.py", line 355, in process_posts
    stdlabel = env.intersphinx_inventory.setdefault('std:label', {})
AttributeError: 'BuildEnvironment' object has no attribute 'intersphinx_inventory'
```

BUT if I add intersphinx to the extensions, we get a different error (which I expected and haven't figured out how to fix yet:

```
Exception occurred:
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinxcontrib/datatemplates/directive.py", line 26, in _load_data
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/samuel/Repositories/WTD/www/docs/_data/{{year}}.{{shortcode}}.speakers.yaml'
```

**Comment by tk0miya** [comment]
It seems first error was caused inside ablog. It means ablog depends on intersphinx, not sphinx-intl.
```
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/ablog/post.py", line 355, in process_posts
    stdlabel = env.intersphinx_inventory.setdefault('std:label', {})
AttributeError: 'BuildEnvironment' object has no attribute 'intersphinx_inventory'
```

And another one was caused inside sphinxcontrib-datatemplates. It is not also related with sphinx-intl.
```
Exception occurred:
  File "/home/samuel/Repositories/WTD/www/venv/lib/python3.5/site-packages/sphinxcontrib/datatemplates/directive.py", line 26, in _load_data
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/samuel/Repositories/WTD/www/docs/_data/{{year}}.{{shortcode}}.speakers.yaml'
```

Thanks,

**Comment by plaindocs** [comment]
Thanks!

**Pull request closed without merging**
