### PR TITLE
LaTeX: separate terms from their definitions by a CR (close #9985)

### LINKED ISSUE #9985: Latex: terms are not separated by a newline
### Describe the bug

I use simple indentations for terms and their explanation:

Example:
```rst
Listing:

:samp:`{file}.cc` :samp:`{file}.cp` :samp:`{file}.cxx` :samp:`{file}.cpp` :samp:`{file}.CPP` :samp:`{file}.c++` :samp:`{file}.C`
  C++ source code that must be preprocessed.  Note that in :samp:`.cxx`,
  the last two letters must both be literally :samp:`x`.  Likewise,
  :samp:`.C` refers to a literal capital C.

:samp:`{file}.mm` :samp:`{file}.M`
  Objective-C++ source code that must be preprocessed.

:samp:`{file}.mii`
  Objective-C++ source code that should not be preprocessed.

:samp:`{file}.hh` :samp:`{file}.H` :samp:`{file}.hp` :samp:`{file}.hxx` :samp:`{file}.hpp` :samp:`{file}.HPP` :samp:`{file}.h++` :samp:`{file}.tcc`
  C++ header file to be turned into a precompiled header or Ada spec
```

Which results in the following HTML output:

Alabaster:

Screenshot from 2021-12-17 12-49-36

RTD theme:

Screenshot from 2021-12-17 12-49-50

While xelatex output does not contain a new line:

Screenshot from 2021-12-17 12-50-53

@jfbu

### How to Reproduce

Build the snippet.

### Expected behavior

_No response_

### Your project

Build the snippet

### Screenshots

_No response_

### OS

Linux

### Python version

3.8

### Sphinx version

4.3.0

### Sphinx extensions

_No response_

### Extra tools

_No response_

### Additional context

_No response_

### LINKED ISSUE #10000: LaTeX: glossary terms with common definition are rendered with too much vertical whitespace
### Describe the bug

as in title

### How to Reproduce

```
.. glossary::
   :sorted:

   boson
      Particle with integer spin.

   *fermion*
      Particle with half-integer spin.

   tauon
   myon
   electron
      Examples for fermions.

   über
      Gewisse

```

and `make latexpdf`

### Expected behavior

_No response_

### Your project

see code snippet

### Screenshots

Capture d’écran 2021-12-20 à 12 09 48

### OS

Mac

### Python version

3.8.0

### Sphinx version

4.3.2

### PR DESCRIPTION
**Pull request by jfbu**
Close #9985 

Also, in passing, this adds better rendering of glossary terms with a common definition (less vertical whitespace):
Fix #10000 

Hence both Bugfix (too much whitespace between glossary terms sharing common definitionà) and New feature (separate terms from defintions by  a CR in pdf output).

As far as I tested briefly, this does not cause breakage if used with numpy's hack into LaTeX description lists, but the hack of their project should be removed entirely, as it causes bad extraneous vertical whitespace.

Related #9988

### CODE REVIEW

**Comment by jfbu** [comment]
I used this test:

```rest

Listing:

:samp:`{file}.cc` :samp:`{file}.cp` :samp:`{file}.cxx` :samp:`{file}.cpp` :samp:`{file}.CPP` :samp:`{file}.c++` :samp:`{file}.C`
  C++ source code that must be preprocessed.  Note that in :samp:`.cxx`,
  the last two letters must both be literally :samp:`x`.  Likewise,
  :samp:`.C` refers to a literal capital C.

:samp:`{file}.mm` :samp:`{file}.M`
  case1:
    Objective-C++ source code that must be preprocessed.
  case2:
    Objective-C++ source code that must be preprocessed.


:samp:`{file}.mii`
  Objective-C++ source code that should not be preprocessed.

:samp:`{file}.hh` :samp:`{file}.H` :samp:`{file}.hp` :samp:`{file}.hxx` :samp:`{file}.hpp` :samp:`{file}.HPP` :samp:`{file}.h++` :samp:`{file}.tcc`
  C++ header file to be turned into a precompiled header or Ada spec

test
  hello
    again

  hello
    again


indented

  more test
    hello
      again

    hello [1]_
      again

    hello
      again

      :samp:`{file}.cc` :samp:`{file}.cp` :samp:`{file}.cxx` :samp:`{file}.cpp` :samp:`{file}.CPP` :samp:`{file}.c++` :samp:`{file}.C`
        C++ source code that must be preprocessed.  Note that in :samp:`.cxx`,
        the last two letters must both be literally :samp:`x`.  Likewise,
        :samp:`.C` refers to a literal capital C.

      :samp:`{file}.mm` :samp:`{file}.M`
        case1:
          Objective-C++ source code that must be preprocessed.
        case2:
          Objective-C++ source code that must be preprocessed.

See :term:`boson` and :term:`über` and :term:`myon`.

.. comment :term:`ähnlich`.

.. [1] coucou

test-glossary
=============

.. glossary::
   :sorted:

   boson
      Particle with integer spin.

   *fermion*
      Particle with half-integer spin.

   tauon
   myon
   electron
      Examples for fermions.

   über
      Gewisse

   .. änhlich
       Dinge
```

and obtain this output in pdf:

Capture d’écran 2021-12-20 à 18 59 37

Capture d’écran 2021-12-20 à 19 00 11


The current PR has a potential limitation if a term has a footnote. But in fact, adding a footnote to a term in a glossary causes a problem, the term is not indexed properly.  Anyway, the alternative approach is currently available at https://github.com/jfbu/sphinx/tree/9985_latex_on_master_v2 (test files not updated). It is cleaner approach perhaps, with less LaTeX macro definitions, and more mark-up output from Sphinx latex writer.

**Comment by jfbu** [comment]
Probably the  `fulllineitems` environment with `\pysigline` for object signatures and description should be refactored to use similar `parbox` dimensions as here. The approach of https://github.com/jfbu/sphinx/tree/9985_latex_on_master_v2 shows how perhaps a refactoring of support for multi-line signatures should be done, in a somewhat cleaner way than current approach in `sphinxlatexobjects.sty` which has too complicated TeX macros.

But I am delaying that to perhaps another PR which could replace this one with the https://github.com/jfbu/sphinx/tree/9985_latex_on_master_v2 approach and at the same time unify with handling of object descriptions.

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for your work, as always :-)
LGTM!

**Comment by jfbu** [comment]
`mypy` test fails after merging master branch into this one, but this regards files unrelated to this PR: https://github.com/sphinx-doc/sphinx/runs/4610549456?check_suite_focus=true

**Comment by tk0miya** [comment]
I fixed the warnings from mypy on the HEAD of master branch now. So please merge it to your branch.

**Comment by jfbu** [comment]
@tk0miya tests pass after merging master, now merging into master, thanks

**Pull request merged**
