### PR TITLE
DOC: Move general project description to main page

### PR DESCRIPTION
**Pull request by timhoffm**
These paragraphs are a high-level project description ("What is the project about?"). As such, they belong on the main page, not in "Getting started". I've condensed them into one paragraph to make it more compact. Most of the omitted information is contained in the nicely formatted feature list right below.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
No sorry, you are just repeating everything that is already in the features section, I don't want a wall of text on the landing page.

**Comment by timhoffm** [comment]
Can we then just delete the paragraphs from "Get started"? - The landing page should clarify what the project is about. I'm fine if the listed features are sufficient for that. When going to "Get started", I expect to get hands on, not read a lengthy intro repeating features.

**Comment by chrisjsewell** [comment]
> When going to "Get started", I expect to get hands on, not read a lengthy intro repeating features.

Oh yeh, the whole of https://www.sphinx-doc.org/en/master/usage/quickstart.html and https://www.sphinx-doc.org/en/master/tutorial/index.html need improving

**Comment by timhoffm** [comment]
I have started to streamline "Getting started" (PR pending). The goal is to get the user to the rendered result quickly (within the first screen). This gives a user the capability to fundamentally work on their own (if they don't want to read long docs), and it should be motivating to have a first result quickly. As part of this, I'd like to remove the two general paragraphs, which I believe are out of scope for "getting started". Do you agree with that?

This PR was an attempt of factoring out the removal of this out-of-scope information. There'll be enough to be discussed on shifting around the information actually belonging to "getting started".

**Pull request closed without merging**
