### PR TITLE
Fix #2162: Add Sphinx.add_source_parser() to add source_suffix and source_parsers from extension

### LINKED ISSUE #2162: Changing source_suffix in an extension's setup() function?
I'm writing [an extension](http://nbsphinx.readthedocs.org/) which provides a custom source parser for `*.ipynb` files.

I'm trying to append `'.ipynb'` to `app.config.source_suffix` within my extension's `setup()` function, to make it easier for my users. This way, they don't have to specify `source_suffix` explicitly in their `conf.py`.

This worked perfectly until I tried to actually specify `source_suffix` in `conf.py`. As soon as `source_suffix` is defined there, my appending `'.ipynb'` ceases to work, and my `*.ipynb` files are not found raising a warning like this:

```
.../doc/index.rst:6: WARNING: toctree contains reference to nonexisting document 'example'
```

If I remove the assignment to `source_suffix` from `conf.py`, it works again.

Any idea what's going wrong here?

Is there anything I can do to make this work?

### PR DESCRIPTION
**Pull request by tk0miya**
This makes adding source_parsers more simple for extension users.
I think this is a little hacky, because I used `config.overrides` to change config variables from extensions.
So I'll update my pull request if any good ways to do that.

(related with #2162)

### CODE REVIEW

**Comment by mgeier** [comment]
Thanks a lot, @tk0miya!
This works (after rebasing onto master), but I would prefer to have a slightly different behavior: I would like the user to be able to override (in `conf.py`) the settings from the extension.
In other words, the extension (in its `setup()` function) should only add to the `source_parsers` dict if the given file name extension was not yet specified in `conf.py`.

Is this somehow possible?

Strangely, within the extension's `setup()` function, `app.config.source_parsers` does _not_ contain the settings from `conf.py`!

Is this intended behavior or a bug?

**Comment by mgeier** [comment]
I had a look at the source code and it looks like this is indeed intended behavior.

For some reason the values from `conf.py` are stored temporarily in `app.config._raw_config` while the `setup()` functions of the extensions are called.
Only afterwards the values are assigned to their proper attributes of `app.config`.

I found an ugly solution to my problem (https://github.com/sphinx-doc/sphinx/issues/2162#issuecomment-168493550) but I still hope there is a better way ...

**Comment by tk0miya** [comment]
Thank you for reviewing.
It is not my intention that user settings are ignored.
I refine the pull request and it enables for users to override the settings from the extension.
I think new one is less hacky.

**Comment by mgeier** [comment]
Thanks for the changes, @tk0miya, now it works perfectly for me!

**Comment by shimizukawa** [comment]
LGTM. @tk0miya please merge it and update CHANGES.

**Comment by tk0miya** [comment]
Thank you for reviewing. I merged it.

**Pull request merged**
