### PR TITLE
[tests] deprecate ``html5lib`` in favor of ``lxml.html``

### LINKED ISSUE #12150: RFE: move away from deprecated `html5lib`
**This ticket is about `sphinx` and `sphinxcontrib-htmlhelp`.**

**Is your feature request related to a problem? Please describe.**
It would be nice tu cut tail of some legacy modules decencies.
One of those modules is `html5lib`.

**Describe the solution you'd like**
it wold be good to remove use of the html5lib deprecated  `html5lib` like it has been  done with pip ~2 years ago.
https://github.com/pypa/pip/pull/11259

**Describe alternatives you've considered**

**Additional context**
`html5lib` depends on `six` which is on list of deprecated modules even longer implanting this RFE would make easier kill two birds using one stone 😋

### PR DESCRIPTION
**Pull request by picnixz**
Closes #12150.

Note that we still need to use ``lxml.html`` because some HTML documents are not XML-compliant. For instance, `search.html` contains `<script src="..." defer />`. While it is correct in HTML, it is not in XML to have an attribute without a value (namely `defer` raises a parser error).

There was a subtle bug in

```
('markup.html', ".//table[@class='hlist']/tr/td/ul/li/p", '^This$'),
```

where the xpath was ``.//table[@class='hlist']/tbody/tr/td/ul/li/p`` (i.e., contained a ``tbody`` additional node). Apparently ``html5lib`` ignored it and directly jumped to ``tr`` (i.e., it was meant to be "implicit") but technically speaking it's incorrect since the HTML content is `<table class="hlist"><tr><td>...`.

### CODE REVIEW

**Comment by picnixz** [comment]
Great, another moment Python 3.13 and Windows. I'll try to fix it now otherwise in some days

**Comment by jayaddison** [comment]
Note: Python3.13 remains available -- there was a temporary Ubuntu PPA infrastructure maintenance window yesterday.

The problem that occurred here was with installation of the `lxml` dependency.  I don't know why that is, because it is also a dependency of `html5lib`.

**Comment by picnixz** [comment]
html5lib is not fully dependent on it actually. You can choose which implementation to use and I don't think it uses `lxml` by default. The reason why it failed is because of Cython that is needed on Windows (I think) and for 3.13 it's because cython is not supported yet on that version (I think).

**Comment by picnixz** [comment]
EDIT: for 3.13, you also need libxml2 and libsxlt as dev packages.

**Comment by picnixz** [comment]
Aaand for Windows it appears that the parser failed.

**Comment by jayaddison** [comment]
> html5lib is not fully dependent on it actually. You can choose which implementation to use and I don't think it uses `lxml` by default. The reason why it failed is because of Cython that is needed on Windows (I think) and for 3.13 it's because cython is not supported yet on that version (I think).

> EDIT: for 3.13, you also need libxml2 and libxslt as dev packages.

To explain those: it's often because `lxml` doesn't yet have a precompiled binary wheel available on PyPi for the relevant Python version (happens much more often with recent/dev releases, because the wheel would have to be re-compiled and uploaded).

When that's the case, installing the dependency requires the `libxml2-dev` and `libxslt-dev` packages you mention so that it can compile the C portions within `lxml`.

(maybe pedantic, but trying to help explain in case this happens again)

**Comment by picnixz** [comment]
Yes, that's how I fixed the 3.13 build. I'm trying to fix the Windows one now.

**Comment by picnixz** [comment]
19 MINUTES BUILD ?????? Ok, we need to wait for cython to be present on 3.13 otherwise those tests will never end.

**Comment by picnixz** [comment]
So I managed to fix Windows. But now what to do with Python 3.13...?

**Comment by picnixz** [comment]
So everything works properly. BUT it's too long on python 3.13. I don't have a better idea so for now keeping it as a draft.

**Comment by jayaddison** [comment]
> > It did require one small tweak to the search.html output we produce to make it valid XML
> 
> The issue is that it's not an XML document, it's an HTML one. So I don't want to have something that could break more in the future. Other possibility is to implement a lightweight `HTMLParser` based on the built-in one.

True - but it's only a dependency for our own unit test suite.

**Comment by jayaddison** [comment]
> > > It did require one small tweak to the search.html output we produce to make it valid XML
> > 
> > 
> > The issue is that it's not an XML document, it's an HTML one. So I don't want to have something that could break more in the future. Other possibility is to implement a lightweight `HTMLParser` based on the built-in one.
> 
> True - but it's only a dependency for our own unit test suite.

(even so, [`defusedxml`](https://pypi.org/project/defusedxml/) may be a better choice than other parsers.  doing some more experimentation)

**Comment by picnixz** [comment]
The thing is:

- If I could find a way to make it work with the native API I'd be happy. But since it uses C implementation when possible I cannot patch whatever method I need to (nor debug it ... and there's no doc...)
- defusedxml is meant for protecting against attacks; what we want is something *unsecure* (because it's faster) and because we are using contents that *we* generate

**Comment by picnixz** [comment]
Waiting for #12168 so that the themes are XML compliant and then switching to native `etree` instead.

**Pull request closed without merging**
