### PR TITLE
Close #3210: emit latex warning if buggy titlesec.

### LINKED ISSUE #3210: latex/xelatex: Section numbers are missing from section titles
html works as expected, but pdf doesn't have section numbers.
1.5 version with xelatex
The code: https://github.com/open-psa/mef

### PR DESCRIPTION
**Pull request by jfbu**

### CODE REVIEW

**Comment by jfbu** [comment]
Now produces this on  `make latexpdf` if `titlesec.sty 2.10.1`:

```bash
(./temp.ind)

Package sphinx Warning: 
******** ERROR !! PLEASE UPDATE titlesec.sty !!********
******** THIS VERSION SWALLOWS SECTION NUMBERS.********.

[1{/usr/local/texlive/2016/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./temp.aux) ){/usr/local/texlive/2016/texmf-dist/fonts/enc/dvips/base/8r.enc}<
/usr/local/texlive/2016/texmf-dist/fonts/type1/urw/helvetic/uhvb8a.pfb></usr/lo
cal/texlive/2016/texmf-dist/fonts/type1/urw/helvetic/uhvbo8a.pfb></usr/local/te
xlive/2016/texmf-dist/fonts/type1/urw/times/utmr8a.pfb>
Output written on temp.pdf (1 page, 25308 bytes).
Transcript written on temp.log.
make[1] : on quitte le répertoire « /Users/XXXX/YYYY/3210-titlesec/_build/latex »
```

**Comment by tk0miya** [comment]
LGTM!

**Comment by jfbu** [comment]
merged in stable for 1.5.2. Thanks!

**Comment by jfbu** [comment]
I have fixed it again at efb5448. Now, in case titlesec is at version 2.10.1, Sphinx prints to the console output:

```
 Package Sphinx Info: 
 **** titlesec 2.10.1 successfully patched for bugfix ****
```

in case it succeeded to load `etoolbox` and to patch according to [here](https://tex.stackexchange.com/questions/299969/titlesec-loss-of-section-numbering-with-the-new-update-2016-03-15/300259#300259). If the package has already been patched Sphinx issues a message like this:

```
Package sphinx Warning: 
******** titlesec 2.10.1 has a bug, (section numbers disappear) ......|
******** and Sphinx could not patch it, perhaps because your local ...|
******** copy is already fixed without a changed release date. .......|
******** If not, you must update titlesec! ...........................|.
```

This extra change was motivated by a message at [sphinx-users](https://groups.google.com/d/msg/sphinx-users/4OIOfA1tQRM/Wve69nMnAQAJ)

**Pull request merged**
