### PR TITLE
fix HTTP BasicAuth for intersphinx mappings

### PR DESCRIPTION
**Pull request by mathiasertl**
request.build_opener requires *args, not a list of handlers as first argument. This fixes basic authentication for me (see also: #2088).

### CODE REVIEW

**Comment by tk0miya** [comment]
LGTM. It works fine!
I think this is a bug fix, so it should be merge into stable branch.
Could you rebase this to stable branch?

**Comment by mathiasertl** [comment]
I'm not sure that is what you wanted?

**Comment by tk0miya** [comment]
Sorry for confusing. I wanted to merge this into stable branch only.
I merged this into it manually just now.

Thank you for contribution!

**Comment by mathiasertl** [comment]
@tk0miya sorry for the confusion on my side as well - great that it's merged, thank you! Sometimes my git-foo could be better :/

**Pull request closed without merging**
