### PR TITLE
Fix #3633: misdetect unreferenced citations

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #3633

I wonder if I should merge this into 1.6 or not. This certainly fix the problem of #3633, but it also brings new interface to sphinx-events and domains. I think this is both bug-fix and new feature.

In addition, I feel we should consider carefully to add new interface to sphinx-core. I think the idea of `env-check-consistency` is not so bad. But there are no reason to add `env-updated` event instead (I only need to hook before saving environment object. either is fine to me).

Note: the original issue #3558 mentioned only to footnotes, not citations. At this moment, nobody want to warn about unreferenced citations. So I'm okay to remove this feature from 1.6 release.

@shimizukawa What do you think?

### CODE REVIEW

**Comment by jschueller** [comment]
great! thanks! needs a rebase though.

**Comment by tk0miya** [comment]
As somebody says "done is better than perfect", there are no reason to postpone this to 1.7 release.
I think it is better to merge this with marking interfaces as experimental.
Is this approach too aggressive?

**Review by jschueller — APPROVED** [review]

**Review by shimizukawa — APPROVED** [review]
LGTM~

**Comment by tk0miya** [comment]
Merged. Thank you for reviewing!

**Comment by jschueller** [comment]
I thought this was going to master branch ?

**Comment by tk0miya** [comment]
Before merging this, 1.6-release branch contains buggy citation warning feature. So this is a fix for it. So I merged this into 1.6-release.

**Comment by jschueller** [comment]
Ok, thanks, I thought I still got the same issue but it was a numpydoc bug.

**Pull request merged**
