### PR TITLE
Apply tls_verify and tls_cacerts config to ImageDownloader (#11715)

### PR DESCRIPTION
**Pull request by ntouran**
Subject: Apply tls_verify and tls_cacerts config to ImageDownloader

### Feature or Bugfix

- Bugfix

### Purpose
- Apply existing requests configuration to a request where it is needed in some cases.
- To fully test, you need a self-signed certificate to put remote images on via URL.

### Detail
- Fixes the issue defined in #11715

### Relates
- #11715

### CODE REVIEW

**Comment by picnixz** [comment]
If possible, can you check where other `tls_verify` and `tls_cacerets` values are not applied? Like, are there other places where the same issue could happen?

**Comment by ntouran** [comment]
> If possible, can you check where other `tls_verify` and `tls_cacerets` values are not applied? Like, are there other places where the same issue could happen?

I looked around to see if there were any more obvious cases at first but will double check. Good idea. 

Ok:

```bash
$ git grep 'from sphinx.util import' | grep requests
sphinx/builders/linkcheck.py:from sphinx.util import encode_uri, logging, requests
sphinx/ext/intersphinx.py:from sphinx.util import logging, requests
sphinx/transforms/post_transforms/images.py:from sphinx.util import logging, requests
tests/test_build_linkcheck.py:from sphinx.util import requests
```

The 3 clients of the requests util here are:

- [x] linkcheck   -- yes, does use this config correctly in HEAD and GET requests
- [x] intersphinx -- yes, does use proper config already
- [x] ImageDownloader -- now does correct usage applied by this PR

So I think we're good!

**Comment by picnixz** [comment]
Good then! Could you add a CHANGES entry please? 

@AA-Turner I think we're good unless you want to wrap small PRs for the day when 7.3.0 is planned to be released.

**Comment by ntouran** [comment]
> Could you add a CHANGES entry please?

Done!

**Comment by picnixz** [comment]
Perfect! In the future, if you want to contribute again, don't force push commits since it makes incremental review harder (we squash them at the end anyway).

**Comment by ntouran** [comment]
> Perfect! In the future, if you want to contribute again, don't force push commits since it makes incremental review harder (we squash them at the end anyway).

Ok sorry. The 2nd commit on the followup had the wrong username so I only force pushed an update to the username/email to that one, but I see what you're saying, and can understand that.

**Pull request merged**
