### PR TITLE
Add ``content_offset`` parameter to ``nested_parse_with_titles``

### PR DESCRIPTION
**Pull request by jbms**
### Feature or Bugfix

- Bugfix

### Purpose
Previously, `nested_parse_with_titles` always passed `0` as the input offset when invoking `nested_parse`.  When parsing the content of a directive, as is a common use case for `nested_parse_with_titles`, this leads to incorrect source file/line number information, as it does not take into account the directive's `content_offset`, which is always non-zero.

This issue affects *all* object descriptions due to #10887.  It also affects the `ifconfig` extension.

The `py:module` and `js:module` directives employed a workaround for this issue, by wrapping the calls to `nested_parse_with_title` with `switch_source_input`.  That worked, but was more complicated (and likely less efficient) than necessary.

This commit adds an optional `content_offset` parameter to `nested_parse_with_titles`, and fixes callers to pass the appropriate content offset when needed.

This commit eliminates the now-unnecessary calls to `switch_source_input` and instead specifies the correct `content_offset`.

### CODE REVIEW

**Comment by jbms** [comment]
Note: An alternative fix would be to modify `nested_parse_with_titles` to always invoke `switch_source_input`.  That would avoid the need for the `content_offset` parameter and any changes to callers of this function.  But it would introduce at least some unnecessary added overhead from constructing a new StateMachine object.

**Comment by jfbu** [comment]
merging latest master update into this, for CI checks

**Comment by jbms** [comment]
After the merge, CI seems to pass.

**Comment by jbms** [comment]
@jfbu It would be great if this fix can be merged soon.  What do you think?

**Comment by jfbu** [comment]
> @jfbu It would be great if this fix can be merged soon. What do you think?

@jbms it looks good to me but I am the LaTeX contractor here so pinging @AA-Turner

**Comment by jbms** [comment]
> > @jfbu It would be great if this fix can be merged soon. What do you think?
> 
> @jbms it looks good to me but I am the LaTeX contractor here so pinging @AA-Turner

Oh, I see.  Unfortunately he said he was out until Easter: https://github.com/sphinx-doc/sphinx/issues/11116#issuecomment-1375688482

**Pull request merged**
