### PR TITLE
Restore 'noindex' support for JS, Python domains

### LINKED ISSUE #12843: `no-index` ignored for `:py:module:`
### Describe the bug

The `noindex` flag allows you to avoid creating an index entry for a directive. This is useful where e.g. a module is documented twice. It looks like the long-term plan is to deprecate `noindex` in favour of `no-index` and in #12620 we made changes to that effect. However, that PR has completely removed the ability to set the `noindex` property on these directives, introducing a regression. I suspect the author assumed inheritance, but we don't call `super()` from `PyObject.run`.

### How to Reproduce

See https://github.com/stephenfin/sphinx-issue-12843

### Environment Information

```text
n/a (occurs with any commit from e439c6f33f to ce0d1791d6 (`HEAD` of `master` at time of writing)
```

### Sphinx extensions

```python
[]
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stephenfin**
### Feature or Bugfix

- Bugfix

### Purpose

Fixes: e439c6f33f (Ensure that old-style object description options are respected (#12620))
Closes: #12843

### Detail
- #12843

> **Note**
> Ideally this should be backport to the 7.x branch, but it appears we don't maintain stable branches any more?

### Relates

None.

### CODE REVIEW

**Comment by picnixz** [comment]
>  Ideally this should be backport to the 7.x branch, but it appears we don't maintain stable branches any more?

Nope, we don't have backports (too much work and not enough hands...)

**Review by picnixz — COMMENTED** [review]
Are these the only parts in the code base that require this? and could you perhaps add a test for that?

**Comment by stephenfin** [comment]
> Are these the only parts in the code base that require this? and could you perhaps add a test for that?

I could, but I'm away for the next week and a bit so I'll be a while. I also don't know if this is essential given this is effectively continuing what was done in https://github.com/sphinx-doc/sphinx/commit/e439c6f33f8d8e7bc06b4f6f25dadfda74869ee0 through to completion, is for a feature that will be deprecated soon, and I have a reproducer linked in the bug that proves this fixes the issue. So maybe we can skirt around without one here and just get this in?

**Review by AA-Turner — APPROVED** [review]
I'll try and add a test later today, but I'm on a flight at some point so may not be that productive.

A

**Pull request merged**
