### PR TITLE
text builder: resolve an ordering conflict between two section-number-related tests

### LINKED ISSUE #12120: [tests] ToC: ordering condition involving title generation.
### Describe the bug

When running text-builder tests from the suite from commit bf0bec3b4b8c019acad4a77a9e228de4e65b538b using `pytest tests/test_builders/test_build_text.py`, the [`test_nonascii_title_line` test case](https://github.com/sphinx-doc/sphinx/blob/bf0bec3b4b8c019acad4a77a9e228de4e65b538b/tests/test_builders/test_build_text.py#L56-L62) fails when `test_secnums` is evaluated before `test_nonascii_title_line`.

### How to Reproduce

From a checkout of 23eb54538781f63b5878f6b456296f0b6a97a6bc and using `pytest==8.1.1`:

```sh
$ pytest -vv tests/test_builders/test_build_text.py tests/test_builders/test_build_text.py -k 'secnum or nonascii_title'
```

(

### Environment Information

```text
Platform:              linux; (Linux-6.6.15-rt-amd64-x86_64-with-glibc2.37)
Python version:        3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0])
Python implementation: CPython
Sphinx version:        7.3.0+/23eb54538
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Sphinx extensions

```python
N/A
```

### Additional context

Relates to #11285.

### PR DESCRIPTION
**Pull request by jayaddison**
### Feature or Bugfix
- Bugfix

### Purpose
- Removes a test suite runtime order conflict between `test_build_text.test_secnums` and `test_build_text.test_nonascii_title_line`.

### Detail
- The `test_nonascii_title_line` test needs a two-character `text_add_secnumbers` configuration to pass successfully.  The `test_secnums` test can interfere with this if it runs first, because it modifies that configuration setting, and by default Sphinx `env` does not reload configuration values in-process after a build has already taken place.

### Relates
- Resolves #12120.
- Relates to #12191.

Edit(s): various attempts to improve the clarity of this pull request's description.

### CODE REVIEW

**Comment by picnixz** [comment]
Hum, why do we have this mypy failure?

**Comment by jayaddison** [comment]
> Hum, why do we have this mypy failure?

That's due to the issue reported in #12864, I think.

**Review by picnixz — APPROVED** [review]
Since I didn't integrate the xdist feature yet, I'm ok with this.

**Comment by picnixz** [comment]
Thank you Jay!

**Comment by jayaddison** [comment]
Thanks @picnixz!  That also reminds me to re-read your test framework pull requests again soon (I think they'll make more sense to me now with some improved understanding of the codebase).

**Comment by picnixz** [comment]
>  That also reminds me to re-read your test framework pull requests again soon 

It's not really pressing. It's nice for the CI because we would make it run under a minute but we could hit other issues when used in production. But thank you for the suggestion! I will need to fix the conflicts before you review it again though.

**Pull request merged**
