### PR TITLE
[C++] Ensure consistent non-specialization template argument representation, rebased and updated

### PR DESCRIPTION
**Pull request by jakobandersen**
Rebased and updated version of #10257.
In addition the parameter pack parsing is fixed for one of the noted cases, while the other case is not valid C++ code anyway.

### CODE REVIEW

**Comment by jbms** [comment]
Thanks!

**Comment by jbms** [comment]
Per the TODO entry in my original PR you added support for parsing:

'int (X::*)(bool)...'

However, that does not appear to be valid C++ syntax.  I believe the correct syntax is:

`int (X::*... x)(bool)`


https://godbolt.org/z/r34v5r6vK

**Comment by jakobandersen** [comment]
It depends on which location. In the test it was as a non-type template parameter:
```c++
struct X {};

template<int (X::*)(bool)...>
void f() {}
```
i.e., a pack of member function pointers. The addition was to make that parse in Sphinx.
The case of ``int (X::*... x)(bool)`` already works as a function parameter in Sphinx.

**Comment by jbms** [comment]
Ah, thanks for the clarification.

**Pull request merged**
