### PR TITLE
4315 toplevel sectioning

### LINKED ISSUE #4315: For PDF 'howto' documents, ``latex_toplevel_sectioning='part'`` generates ``\chapter`` commands
#### Procedure to reproduce the problem

Put this in conf.py:

    latex_toplevel_sectioning = 'part'

and use ``'howto'``

```
latex_documents = [
    (master_doc, 'FOO.tex', 'FOO Documentation',
     'JFB', 'howto'),
]
```

Then ``make latex`` with ``index.rst`` being like this (or with a toctree)

```rst
===============================
Welcome to FOO's documentation!
===============================

This is first part
==================

This is a section
-----------------

Hello

This is a section
-----------------

Hello
```

#### Error logs / results

The generate file ``FOO.tex`` looks like this

```
\part{This is first part}
\label{\detokenize{index:welcome-to-foo-s-documentation}}\label{\detokenize{index:this-is-first-part}}

\chapter{This is a section}
\label{\detokenize{index:this-is-a-section}}
Hello


\chapter{This is a section}
\label{\detokenize{index:id1}}
Hello
```

But usage of `\chapter` is wrong in article class.

It does not generate an error because one of the loaded packages (not Sphinx [1]) has the effect of setting `\chapter` to `\relax` which means at least PDF build is not broken, but the output is of course completely wrong as the titles are printed as plain text with no numbering and no entries in the table of contents.

[1] I determined the (first) culprit to be package `titlesec`, line 1179 of `titlesec.sty v2.10.2`. The problem is that because of that the Sphinx bug is not seen, unless people check visually the PDF and realize too late that the output is wrong. 

#### Expected results

Use `\part` and `\section`,  but not `\chapter`.

### Environment info
- OS: Mac
- Python version: 3.6.3
- Sphinx version: 1.6.3 and current master

### PR DESCRIPTION
**Pull request by jfbu**
Fixes #4315

### CODE REVIEW

**Review by jfbu — COMMENTED** [review]
I notice only now there were already some tests for toplevel sectioning. But they failed to catch the ``'howto'`` issue. Should I modify those tests or keep my added one?

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
>Should I modify those tests or keep my added one?

I think tests should be updated when bugs found. So please update them if needed.

**Comment by jfbu** [comment]
Thanks for reviewing @tk0miya ! I will merge after testing completes.

**Comment by jfbu** [comment]
@tk0miya when AppVeyor takes time it often happens than clicking on Details I am told

> Build not found or access denied.

Just to report.

**Comment by jfbu** [comment]
It might be because I need to login on AppVeyor with my github data, however I find it very boring to again and again and again have to login to sites such as those only to get some data. (sorry, bad day)

**Comment by jfbu** [comment]
Actually, it is find once AppVeyor completes. Well, I made noise for not much. But then the Details should be grayed out or whatever, because I find message misleading.

**Pull request merged**
