### PR TITLE
Fix #2671: image directive may lead to inconsistent spacing in pdf

### LINKED ISSUE #2671: image directive may lead to inconsistent vertical (and horizontal) spacing in pdf output
currently, latex re-defines `\includegraphics` to check if image fits in line width, and if it is too large, use `width=\linewidth` option so that it fits perfectly. But the code in that case uses `\hbox` which does not initiate a new paragraph, contrarily to original `\includegraphics`. This means that no parskip glue is inserted. Also if user has set non-zero parindent it is not obeyed. Thus inclusion of images which fit in line width does not have same behaviour than inclusion of images which exceed the line width (even by only 0.01mm for example).

``` rst
Hello
=====


.. image:: sphinxwide.png

.. image:: sphinxwide.png

.. image:: sphinxnarrow.png

.. image:: sphinxwide.png

.. raw:: latex

   \parindent 20pt
   \par % for next material to not be considered in same paragraph, once this issue will be fixed

.. image:: sphinxnarrow.png

.. image:: sphinxwide.png

```

produces 
capture d ecran 2016-06-13 a 09 56 28

Observe the blank space above narrow image. And the fact that it obeys parindent, but not the image which was originally wider than line-width.

The behaviour should be consistent. It is normal that `\includegraphics` starts a paragraph because that's default LaTeX (notice that in a table cell or start of minipage no extra vertical space will be added on top). This behaviour should be applied in all cases. And a \noindent should be used, else full width images will extend into right margin in case of positive parindent (currently images with 0.01mm more than full width do not because they are wrapped in a `\hbox`; once this is improved the `\noindent` will apply to them to).

I used following images:

sphinxwide
sphinxnarrow

### PR DESCRIPTION
**Pull request by jfbu**

### CODE REVIEW

**Comment by jfbu** [comment]
See #2671 for issue description.
- this fix maintains the current situation where sphinx.sty redefines `\includegraphics` command. It would be better to rather wrap it in a `\sphinxincludegraphics`. 
- the fix re-establishes consistent behaviour. It uses `\noindent` in all cases. The other approach is rather to always use `\hbox` wrapper. But this is not LaTeX's philosophy.

I need to examine current status of image directive versus alignement options for pdf output.

**Comment by tk0miya** [comment]
LGTM.

> It would be better to rather wrap it in a \sphinxincludegraphics.

+1 for `\sphinxincludegraphics`.
It would be nice if custom `\includegraphics` will be deprecated in future version (in v2.0?).
How about copying custom `\includegraphics` to `\sphinxincludegraphics` and use it?

**Comment by jfbu** [comment]
I need to check about the extension you mentioned at https://github.com/sphinx-doc/sphinx/pull/2669#issuecomment-226375380 which uses sphinx customized `\includegraphics`.

About your question, copying custom `\includegraphics` to `\sphinxincludegraphics` is actually what PR#2669 does. It does modify the current custom meaning because it is not consistent. A choice must be made:
- either always wrap `\includegraphics` inside `\hbox`. 
- or always use `\noindent` before it.

First possibility has advantage that image inclusion does not initiate a paragraph, it is more like a `<div>` element. No parskip space is added. No parindent either. Hence full width image, or larger than full-width after rescaling, fit exactly in line, and have no extra vertical spacing (only `\lineskip` which is usually `1pt`)

Second possibility is lile LaTeX default (apart from killing indentation, which is already zero in Sphinx as it sets parindent=0pt). It is like a bit like  `<p><span>..</span></p>` hence parskip glue is added. However this never shows in `figure` environment because LaTeX resets both parskip and parindent to zero values there. A `.. image::` directive will then have the effect of parskip space above the image even if it is alone. Theoretically it could be continued (if small) by some text on same line, but it seems Sphinx always add blank line, hence it creates paragraph of its own.

I don't know what is better for `\sphinxincludegraphics`. But surely `\includegraphics` original should not be modified, else, compatibility problems with user added packages may appear. (I know that nobody complains so far... perhaps because few people add LaTeX packages to what Sphinx does by default ?)

**Comment by tk0miya** [comment]
At first, about `\sphinxincludegraphics`:

> About your question, copying custom \includegraphics to \sphinxincludegraphics is actually what PR#2669 does.

I meant sphinx should provides both customized `\includegraphics` and `\sphinxincludegraphics`.
The customized `\includegraphics` is provided for 3rd party extensions to keep compatibility. In my idea, it will be deprecated in future version.
On the other hands, the `\sphinxincludegraphics` is used as new standards for including graphics.

So, IMO, it is better to improve `\includegraphics` macro and define `\sphinxincludegraphics` as a copy of `\includegraphics` like following::

```
\renewcommand\includegraphics[2][\@empty]{%
  % keep includegraphics customized
}
% define sphinxincludegraphics as a copy of includegraphics
\let\sphinxincludegraphics\includegraphics
```

Secondly, about spacing of `\includegraphics`.
I need to apologize you about my wrong reviewing. this fix is not good for sphinx.

In reST spec, `.. image::` directive represents inline images.
http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

We can embed an image using substitute syntax:

```
.. |logo| image:: sphinx.png

Hello |logo| world!
```

It is rendered as:

```
Hello \includegraphics{{logo}.jpg} world!
```

So I think it is better to output `\noindent` by LaTeX writer if the image node is alone in paragraph.

**Comment by jfbu** [comment]
@tk0miya first let me thank you for all the help. I did not explain clearly that in case of 

```
Hello \includegraphics{{logo}.jpg} world!
```

it doesn't matter which one of the two possibilities I discussed is realized:
1. as we are already in horizontal mode, using a `\hbox` or not round the `\includegraphics` original macro changes nothing (it would change the `depth` but by default `\includegraphics`` creates a LaTeX box with no depth)
2. and the `\noindent` is a no-op at this location too.

Does this make it clearer ?

**Comment by jfbu** [comment]
On the `\includegraphics/\sphinxincludegraphics` I now understand what you mean. We can provide the two macros with same meaning and mention that at a certain future release only `\sphinxincludegraphics` will keep that meaning and `\includegraphics` will be again the original non-customized one: that sounds perfect too me.

Only question now is whether we want `.. image`` directive for full width image insert parskip vertical space above it. The current situation is that:
- no vertical space (only 1pt)  is added in case the original width was  `>` the line-width
- parskip vertical space is added if original width was `<=` the line-width OR the width was specified as option to the directive.

hence current behaviour is not consistent and it is not obvious which consistent behaviour to choose.

**Comment by tk0miya** [comment]
Of course, the image can be placed at top of paragraph.

```
% |logo| Hello world!
\includegraphics{{logo}.jpg} Hello world!
```

In this case, `\noindent` is not good.

I can't determine the `\hbox` is good for these case.
The `\includegraphics` macro is used in several situation. It is used in `\scalebox`, `\raisebox` `\begin{sphinxfigure-in-table}`, `\begin{wrapfigure}`, `\begin{flushleft}`, `\begin{flushright}` and `\begin{figure}`.
(sorry I don't have a time for investigation...)

**Comment by jfbu** [comment]
Good point @tk0miya ! and `\hbox` is not good in that case in the sense that it will separate the image from the text: first the image will appear (without indent and without vertical separation by parskip from prior material), then the first word after image will create a new paragraph, thus will appear underneath image. 

For this the correct is `\leavevmode` which is what LaTeX original `\includegraphics` does. However we don't want that as general rule, because there is the case of image is full-line width.

Currently default of Sphinx is that  `\parindent` is zero. But imagine a user sets a positive value. Isn't it actually better if an image comes first in a paragraph that it creates no indent ? After all, indent is to visibly signal the start of paragraph. But if image is at start this is already typographically well visible.

This is why rather than `\leavevmode` I used `\noindent` because it handles full width images and did not seem too bad for start of paragraphs. Note: `\indent` command exists but is very bad because it inserts indentation even in the middle of a paragraph if encountered there.

**Comment by tk0miya** [comment]
I think the spacing problem of fulll-width images is unexpected behavior.
I guess the author of the customized `\includegraphics` was not aware of the problem.
So it should be fixed.

> Currently default of Sphinx is that \parindent is zero. But imagine a user sets a positive value. Isn't it actually better if an image comes first in a paragraph that it creates no indent ? After all, indent is to visibly signal the start of paragraph. But if image is at start this is already typographically well visible.

I think it should be indented. The image is a part of paragraph if it is marked up as **inline**.
On the other hand, in my understanding, the images which is not marked up as **inline** should behaves like a block level element. so it does not needs any indent.

Actually, single `.. image::` directive creates a simple image node which is not wrapped in paragraph node in logical structure of docutils (you can see it with `make pseudoxml`).

```
.. image:: sphinx.png
# => <image uri="sphinx.png" />

.. |logo| image:: sphinx.png

Hello |logo| world!
# => <paragraph>Hello <image uri="sphinx.png" /> world!</paragraph>
```

So it is better to change the macros to represent it whether the image node is inline or not.
For example, the following patch adds `\noindent` before `\includegraphics` if it is placed on top level.
This works fine in very simple case.

```
diff --git a/sphinx/writers/latex.py b/sphinx/writers/latex.py
index 524e035..eb2d373 100644
--- a/sphinx/writers/latex.py
+++ b/sphinx/writers/latex.py
@@ -1407,8 +1407,12 @@ class LaTeXTranslator(nodes.NodeVisitor):
             except KeyError:
                 pass
         if not is_inline:
+            if isinstance(node.parent, nodes.section):
-            pre.append('\n')
-            post.append('\n')
+                pre.append('\n\\noindent')
+                post.append('\n')
+            else:
+                pre.append('\n')
+                post.append('\n')
         pre.reverse()
         if node['uri'] in self.builder.images:
             uri = self.builder.images[node['uri']]
```

**Comment by jfbu** [comment]
I am so used to think in LaTeX terms, I didn't look into latex.py and didn't know about `is_inline` boolean... 

it looks good with your patch if custom `\includegraphics` has `\leavevmode` like LaTeX's original (as it is needed if an inline image is first in a text paragraph, in order to obey indentation) and your patch adds `\noindent` in case of top level non-inline image (we don't want indentation then, especially when the image is full-width from added option `width=\linewidth`.)

Also, if image is inside a `figure` node, it does not matter that `\noindent` is not used, because LaTeX's figure environment sets `\parindent` to  `0pt` (and also `\parskip`) (hence inside a `figure` it is possible to stack multiple images one below the other with only `\lineskip=1pt` vertical separation, but if at top level such situation will add `\parskip` extra white space between stacked images)

I am not familiar enough with html authoring to know if top level `` tag should generate vertical distinction, like LaTeX does with `\parskip` vertical space which it adds each time it starts a paragraph (for example if `\noindent` is encountered while in vertical mode).

If top level image is in a `\hbox` with neither `\leavevmode` nor `\noindent` and there is blank line in the source to separate it from previous text, then LaTeX will put it immediately below lowest letters of previous paragraph with only 1pt separation, and _following_ paragraph of text will be separated from bottom of image by `\parskip`, hence image appears glued to previous paragraph. With your patch which adds the `\noindent` the image between two text paragraphs in the source appears equilibrated in pdf output at more similar distance from each.

All together this looks good to me. I will update PR soon to reflect our discussion so far.

**Comment by jfbu** [comment]
I have incorporated changes and rebased.

I have an issue with 

``` rst
.. topic:: CONTENTS


   .. raw:: latex

      \parindent 30pt\relax

   A paragraph, then inclusion of an image larger than the (box) linewidth.

   .. image:: sphinx.png

   Again, but with a noindent.

   .. raw:: latex

      \par\noindent

   .. image:: sphinx.png

   After image inclusion.
```

using the logo `sphinx.png` in `doc/_static/` which is initially wider than line-width. I wonder if `if isinstance(node.parent, nodes.section):` test is really needed and whether we should always do `\noindent` for non-inline images.

**Comment by tk0miya** [comment]
I'm afraid to break a layout by unnecessary `\noindent`. It's okay to remove the condition if putting `\noindent` always does not cause any problems.

Note:

> The `\includegraphics` macro is used in several situation. It is used in `\scalebox`, `\raisebox` `\begin{sphinxfigure-in-table}`, `\begin{wrapfigure}`, `\begin{flushleft}`, `\begin{flushright}` and `\begin{figure}`.

**Comment by jfbu** [comment]
> The `\includegraphics` macro is used in several situation. It is used in `\scalebox`, `\raisebox`, `\begin{sphinxfigure-in-table}`, `\begin{wrapfigure}`, `\begin{flushleft}`, `\begin{flushright}` and `\begin{figure}`.
- `\scalebox`, `\raisebox`: a `\noindent` is a no-op therein.
- `\begin{sphinxfigure-in-table}` uses a `minipage` and inside  `minipage`, the `\parindent` is set to zero.
- `wrapfigure`, `flushleft`, `flushright`, `figure` all set the `\parindent` to zero.
- further, `\centering` macro also sets `\parindent` to zero.

Thus if a non-inline image directive ends up in one of those environments, using `\noindent` rather then (or in addition to) `\leavevmode` should not cause problems. But to be honest I am familiar with only one or two Sphinx projects, the first is the one which brought me to use Sphinx, and the second is the documentation of Sphinx itself ;-)

Anyhow, by default Sphinx sets globally `\parindent=0pt`, and I guess most projects do not modify it.

The main impact of this PR is because Sphinx has positive `\parskip` by default. The `\parskip` becomes again zero in `figure` or `wrapfigure` but not in `flushleft`, `flushright`, `center` environments. So far the Sphinx `\includegraphics` is broken and there is a discontinuity in handling of images without width spec depending on whether they are wider or not than available width. The PR fixes this, but will as a result put `\parskip` space above isolated images, like it was the case earlier only for images with `width` spec, or images without but shorter than available space.

**Comment by jfbu** [comment]
I want to draw attention to a subtle aspect of minipage that few people are aware of. This is relevant to sphinx because of `sphinxfigure-in-table` which uses a minipage. Consider this

``` latex
\documentclass[a4paper]{article}

\newenvironment{foo}{}{}
\begin{document}
A

\begin{foo}
\noindent\begin{minipage}{1.0\linewidth}
Hello.    
\end{minipage}
\end{foo}

A

\noindent\begin{minipage}{1.0\linewidth}
Hello.    
\end{minipage}

A

\end{document}
```

which gives
capture d ecran 2016-06-19 a 10 35 17

Notice the extra blank line after the foo environment. This is very subtle TeX/LaTeX effect which can be prevented by using `\end{minipage}%` or `\end{minipage}\relax`. For this reason in next commit I replace

```
            self.context.append(ids + '\\end{sphinxfigure-in-table}\n')
```

by 

```
            self.context.append(ids + '\\end{sphinxfigure-in-table}\\relax\n')
```

just in improbable case that the environment (which ends with `\end{minipage}` internally) ends up inside another LaTeX environment like in the example above.

**Comment by jfbu** [comment]
Due to some merge conflict in CHANGES I do not update it yet. I propose to add

```
Release 1.4.5 (in development)
==============================

Incompatible changes
--------------------

* latex inclusion of images, outside of text paragraphs and of figure
  directives, created differing top vertical space, depending on original
  image width; behaviour is now consistent, but by necessity differs from
  earlier one in some cases.
* latex ``\includegraphics`` as customized by Sphinx to handle wide images
  will revert to original LaTeX meaning in future release. Custom (new) code
  is and will remain available as ``\sphinxincludegraphics``.

```

**Comment by jfbu** [comment]
merging now (so people who test stable branch can report issues) and will update CHANGES next. Thanks a lot @tk0miya  for in-depth discussion.

**Comment by jfbu** [comment]
for the record: this merged PR also fixed bad positioning of images when they were re-dimensioned to `\linewidth` from inside lists or quoted blocks. The earlier code would not let the image obey current indentation.

**Pull request merged**
