### PR TITLE
Allow `:ref:` role to be used with definitions and fields

### PR DESCRIPTION
**Pull request by jbms**
### Feature or Bugfix

- Feature

### Purpose
Since these nodes have a natural title, there is no reason not to
support the :ref: role.

### CODE REVIEW

**Comment by jbms** [comment]
@AA-Turner Do you think you might have chance to review this?

**Comment by AA-Turner** [comment]
Please add a CHANGES entry, I will review shortly.

A

**Comment by jbms** [comment]
> Please add a CHANGES entry, I will review shortly.
> 
> A

Done.

**Review by AA-Turner — APPROVED** [review]

**Comment by AA-Turner** [comment]
Thanks!

A

**Comment by vincentkfu** [comment]
I believe this patch triggers `duplicate label` warnings that were not present before this patch was merged.

With 5.1.1 our docs built with no warnings: https://github.com/axboe/fio/actions/runs/3106980788/jobs/5034529793
But with 5.2.1 we now see warnings: https://github.com/axboe/fio/actions/runs/3129974184/jobs/5079696775

```
/Users/runner/work/fio/fio/HOWTO.rst:: WARNING: duplicate label int, other instance in /Users/runner/work/fio/fio/doc/fio_doc.rst
looking for now-outdated files... none found
/Users/runner/work/fio/fio/HOWTO.rst:: WARNING: duplicate label bool, other instance in /Users/runner/work/fio/fio/doc/fio_doc.rst
/Users/runner/work/fio/fio/HOWTO.rst:: WARNING: duplicate label irange, other instance in /Users/runner/work/fio/fio/doc/fio_doc.rst
```

We have `fio_doc.rst` and `fio_man.rst` both include `../HOWTO.rst` which defines the labels `int`, `bool`, and `irange`.

Is there a work-around to eliminate the warnings?

**Comment by AA-Turner** [comment]
@vincentkfu please open a new issue with a minimal reproducer (ideally a single `.rst` source file if possible) and tag me and Jeremy.

A

**Comment by jbms** [comment]
I think the best solution would be to restructure your documentation to avoid defining duplicate labels.  Even before this patch, you still had duplicate labels, there was just no warning.

Potentially you could just suppress the warning, e.g. using the `suppress_warnings` config option.

I don't know if it was intentional that Sphinx does not warn on duplicate labels without titles, or if that was just accidental.

**Pull request merged**
