### PR TITLE
Generate PEP 740 attestations for PyPI

### PR DESCRIPTION
**Pull request by AA-Turner**
[PEP 740](https://peps.python.org/pep-0740/)

### CODE REVIEW

**Comment by AA-Turner** [comment]
Output from https://github.com/AA-Turner/sphinx/actions/runs/11203683364/job/31141226284:

```text
python -m pypi_attestations sign dist/*
python -m pypi_attestations inspect dist/*.publish.attestation
Warning: The information displayed below are not verified, they are only displayed. Use the verify command to verify them.
File: dist/sphinx-8.1.0-py3-none-any.whl.publish.attestation
Version: 1
Statement:
    Type: https://in-toto.io/Statement/v1
    Subject:
        sphinx-8.1.0-py3-none-any.whl (digest: b657d540a03ced0c94c27d5d3c3639710c5b205ae42d5e48daef957dd5b35f06)
    Predicate type: https://docs.pypi.org/attestations/publish/v1
    Predicate: None
Certificate:
    Subjects: ['https://github.com/AA-Turner/sphinx/.github/workflows/create-release.yml@refs/heads/attestations']
    Issuer: CN=sigstore-intermediate,O=sigstore.dev
    Validity: 2024-10-06 17:16:58+00:00
Transparency Log (1 entries):
    Log Index: 137444982
Warning: The information displayed below are not verified, they are only displayed. Use the verify command to verify them.
File: dist/sphinx-8.1.0.tar.gz.publish.attestation
Version: 1
Statement:
    Type: https://in-toto.io/Statement/v1
    Subject:
        sphinx-8.1.0.tar.gz (digest: 78ddd883f3dabdd56919e7f91f7c168a4c219dd92170828beeec8a7f0e3c3e7c)
    Predicate type: https://docs.pypi.org/attestations/publish/v1
    Predicate: None
Certificate:
    Subjects: ['https://github.com/AA-Turner/sphinx/.github/workflows/create-release.yml@refs/heads/attestations']
    Issuer: CN=sigstore-intermediate,O=sigstore.dev
    Validity: 2024-10-06 17:16:58+00:00
Transparency Log (1 entries):
    Log Index: 137444983
python -m pypi_attestations verify dist/*.whl --identity https://github.com/AA-Turner/sphinx/.github/workflows/create-release.yml@refs/heads/attestations
OK: dist/sphinx-8.1.0-py3-none-any.whl.publish.attestation
python -m pypi_attestations verify dist/*.tar.gz --identity https://github.com/AA-Turner/sphinx/.github/workflows/create-release.yml@refs/heads/attestations
OK: dist/sphinx-8.1.0.tar.gz.publish.attestation
```

A

**Comment by jayaddison** [comment]
A question / observation: the attestation doesn't appear to provide a reference back to the original source code revision (git commit, in this case) that the attested artifact was built from.  As a consumer of provenance data, I'd like in future to be able to navigate back to the source material (perhaps from an archive, if necessary), and then precisely locate the build revision, and compare/inspect/rebuild/etc from there.

Note: I did briefly wonder whether the certificate subject (SAN?) would be the place to expect that information -- but the current value, that reflects the build process (the GitHub Action, in this case) I _think_ is intentional per-design according to [PEP-740](https://github.com/python/peps/blob/8f0f87e300ac888fccdd963a302de77597cc767b/peps/pep-0740.rst?plain=1#L503-L505):

> * ``verification_material.certificate`` identifies an appropriate signing
  subject, such as the machine identity of the Trusted Publisher that published
  the package.

(that seems to describe what the SAN should contain - but I might have misunderstood.  I realize mentioning that field may seem slightly off-topic, but I want to figure out whether it's the expected location for an unambiguous source revision reference)

**Comment by AA-Turner** [comment]
I didn't follow the discussions around PEP 740, but yes is appears that there's no link to the SCM. This may have been intentional though, perhaps @woodruffw would know more.

A

**Comment by AA-Turner** [comment]
The new `actions/attest` approach also records sigstore attestations in the repo, e.g.:

* https://github.com/AA-Turner/sphinx/attestations/2374209
* https://github.com/AA-Turner/sphinx/attestations/2374232

A

**Comment by woodruffw** [comment]
> I didn't follow the discussions around PEP 740, but yes it appears that there's no link to the SCM.

There is one, but it's at a lower layer in the format: the X.509 certificate contains extensions corresponding to the machine identity/workflow identity of the CI job that ran the attestation step, and one of those extensions is the commit SHA.

The full set of extensions and how they map to individual CI providers (like GHA) is here: https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md

**Comment by jayaddison** [comment]
Thank you, @woodruffw!

**Comment by jayaddison** [comment]
> A question / observation: the attestation doesn't appear to provide a reference back to the original source code revision (git commit, in this case) that the attested artifact was built from. As a consumer of provenance data, I'd like in future to be able to navigate back to the source material (perhaps from an archive, if necessary), and then precisely locate the build revision, and compare/inspect/rebuild/etc from there.

Commenting here for future reference / to complete the thread: in fact the [attestation _does_ already include](https://github.com/sphinx-doc/sphinx/pull/12989#issuecomment-2399592956) these details; my observation was based only on the output of `pypi_attestations inspect`, and that is a partial view of the attestation's contents.

**Pull request merged**
