### PR TITLE
i18n: Fix loading custom template translations for en

### LINKED ISSUE #12214: Template translations (sphinx.po) are not used for English language
### Describe the bug

When using custom template overrides as described in https://www.sphinx-doc.org/en/master/development/templating.html

If the template contains translated strings, for instance:

```jinja
{% extends "!layout.html" %}
{% block document %}
    {{ _('coucou') }}
    {{ super() }}
{% endblock %}
```

The strings are correctly extracted with the gettext builder (`make gettext`), but when the base language is not English, and the translated language is English, the translation catalog is not used. It works as expected when translating in another language than English (for example from French to German).

### How to Reproduce

I made a reproducer in this git repo: https://github.com/n-peugnet/sphinx-template-en-translation-bug or this zip: 
[sphinx-template-en-translation-bug-main.zip](https://github.com/sphinx-doc/sphinx/files/14875583/sphinx-template-en-translation-bug-main.zip)

```
git clone https://github.com/n-peugnet/sphinx-template-en-translation-bug
cd sphinx-template-en-translation-bug
make html O=-Dlanguage=en
```

Then check the content of `_build/html/index.html`

### Environment Information

```text
Platform:              linux; (Linux-6.6.15-amd64-x86_64-with-glibc2.37)
Python version:        3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0])
Python implementation: CPython
Sphinx version:        7.3.0
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

Sphinx is latest git version: `v7.2.6-318-gd5baa46d8`

### Sphinx extensions

_No response_

### Additional context

Notice that running `make html O=-Dlanguage=de` produces the expected result.

### PR DESCRIPTION
**Pull request by n-peugnet**
The English language was hardcoded to load empty translations for templates as part of https://github.com/sphinx-doc/sphinx/pull/10067, but the rest of the code is already capable of handling missing translations just fine, so we can simply drop the first if block.

This allows to use translations for English in custom templates, as for all the other languages.

Fixes sphinx-doc/sphinx#12214

(the diff is better looked at when hiding whitespace changes)

### CODE REVIEW

**Comment by picnixz** [comment]
Should I understand that, currently, we just assumed that `locale.init` would automatically handle everything while it was not the case? Like, it would work with Sphinx only because we are using our own internal templates & localizations, but would not for external ones because they could have other localized strings that we do not know about?

**Comment by n-peugnet** [comment]
What I understand is that before https://github.com/sphinx-doc/sphinx/pull/10067, the translator was initiated with an empty set when the language was set to `None` which was the default at that time. I this pull request, the default changed to `en`, and [this if block was updated to reflect that](https://github.com/sphinx-doc/sphinx/pull/10067/files#diff-6a68650d5fb140af74d5977d1d1c09d8828eacf973ca56c525451d0bfbd01506), but without accounting for the custom templates, when the base language is not English. IMO this if can simply be dropped as I don't see why English should have a special exception, since it is not always the base language of a documentation.

**Comment by picnixz** [comment]
I see. What I would like to avoid however is to load all the catalogs (which could be expensive) if there is no reason to do that. Is there a way to known whether template localization or not? if so, it would be good to check whether the translator needs to be initialized or not.

**Comment by n-peugnet** [comment]
I'm not sure what you mean about "all the catalogs", this would only load le catalogs of the current language, if there are .po files for it. This change only remove an exception for the English language, and treats it as all the other ones.
As I understand it, if no user catalogs are defined for English, then there is no difference with the previous behaviour.

Here is an example build in a test project without any .po files for English:

```
Removing everything under '_build'...
Running Sphinx v7.3.0+/d5baa46d8
loading translations [en]... not available for built-in messages
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] index
generating indices... genindex done
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
```

We can the this message:

    loading translations [en]... not available for built-in messages

And if a .po file exists for English, then it is most likely there for being used than for nothing.

**Comment by picnixz** [comment]
Ah, I'm sorry by saying "all catalogs". Actually, since I never used localization, I'm just wondering this could make the build much slower or not (maybe I should just have said that I was worried about the complexity overhead). If the build time does not increase, I think this PR is fine (but I would like someone else to review it since I'm not well-versed in this topic).

**Comment by n-peugnet** [comment]
I just added a commit that always show "done" for English language, as the "not available for built-in messages" message could be misleading. Now the only diff in the log is the addition of the message "loading translations [en]... done":

```diff
--- before	2024-04-04 19:37:35.143948516 +0200
+++ after	2024-04-04 19:37:44.851948130 +0200
@@ -1,4 +1,5 @@
-Running Sphinx v7.2.6
+Running Sphinx v7.3.0+/bc127a0bf
+loading translations [en]... done
 making output directory... done
 building [mo]: targets for 0 po files that are out of date
 writing output... 
```

This should not change anything for most of the users, Sphinx will simply look for English translations which most of the time will not be existing. So it will load an empty translation catalog.
But this allows to load user defined English translations, if present, which in turn fixes #12214

**Comment by picnixz** [comment]
> This should not change anything for most of the users, Sphinx will simply look for English translations which most of the time will not be existing. So it will load an empty translation catalog.

If you want to be even more precise, you could also check whether the catalog is empty or not (is it even possible?) and say that the catalog is empty. But this would be just nitpicking and I think people just don't care about that.

**Review by picnixz — APPROVED** [review]

**Comment by n-peugnet** [comment]
I just fixed the merge conflict.

**Review by chrisjsewell — APPROVED** [review]
yep looks good to me cheers

**Pull request merged**
