### PR TITLE
Fix broken changelog

### PR DESCRIPTION
**Pull request by ewjoachim**
Subject: I believe the Changelog is currently broken with 2 `5.0.1` sections (one above and one below the 5.0.2)

### Feature or Bugfix
Neither

### CODE REVIEW

**Comment by ewjoachim** [comment]
See https://github.com/sphinx-doc/sphinx/pull/10515/files#diff-aac07aefec754086f5c344e2c233862f6a611c739b5647fd456c1b77d3577c79L45

**Review by AA-Turner — APPROVED** [review]

**Comment by tk0miya** [comment]
We have 3 branches for developing Sphinx.

* `master` ... for the next major release. At present for 6.0.0
* `5.x` ... for the next minor release. At present for 5.1.0
* `5.0.x` ... for the next bugfix release. At present for 5.0.2.

So this is not broken.

**Comment by AA-Turner** [comment]
Oops, yes I confused `5.0.1` and `5.1.0` -- I rescind my approval.

A

**Comment by ewjoachim** [comment]
Oooh I see, sorry for the noise!

**Pull request closed without merging**
