### PR TITLE
Add an option for displaying short ``Literal`` types

### LINKED ISSUE #9643: sphinx.domains.python._parse_annotation should improve formatting of Union, Optional, Literal, constants
This is a sub-issue of #9523 split off here.

When displayed normally, `Union`, `Optional`, and `Literal` add a lot of noise to the type signature and obscure the important information.  Instead, it is much cleaner to display them using the PEP 604 (https://www.python.org/dev/peps/pep-0604/) syntax:

`Union[X, Y, Z]` -> `X | Y | Z`
`Optional[X]` -> `X | None`

Additionally, for `Literal` it is cleaner to strip the text "Literal" and just display the literal value with normal Python syntax highlighting:

`Literal["X"]` -> `"X"`

This is implemented in the tensorstore documentation via an ast transformation:

https://github.com/google/tensorstore/blob/1a59fcb310bc1feb13569f03f7134b4c3a5fa5f4/docs/tensorstore_sphinx_ext/autodoc.py#L259

This should be supported in Sphinx via a config option.  The other improvement, of using syntax highlighting for constants, should also be integrated.

### PR DESCRIPTION
**Pull request by AA-Turner**
Closes #9643

cc: @jbms 

A

### CODE REVIEW

**Comment by jbms** [comment]
Thanks for implementing this.

I think just the Python domain changes are needed, and the autodoc changes should be skipped, since I think it introduces an ambiguity with string literals and it is not clear to me what purpose it serves.  I think it is better to always pass valid Python syntax to the Python domain directives, and just do this transformation when converting to docutils nodes.

**Comment by AA-Turner** [comment]
@jbms how's this update?

**Comment by AA-Turner** [comment]
@jbms How's this much simpler implementation?

A

**Comment by jbms** [comment]
Looks good to me, thanks!

**Pull request merged**
