### PR TITLE
HTML: Fix search unnecessarily requiring source files

### PR DESCRIPTION
**Pull request by Blendify**
Subject: Fixes search summeries not showing when `html_copy_source = False`

### Purpose
This seems to have been a mistake with #4022 the ajax call functions correctly without the source files being included in the build (they are never used).

I have tested this out on several themes and now everything works correctly with `html_copy_source = False`

### Relates

#4022

### CODE REVIEW

**Comment by Blendify** [comment]
I am not sure how to rebase this for 4.0.x but it would be nice if this could go into 4.0.x

**Comment by tk0miya** [comment]
LGTM. Could you rebase this into the 4.x branch?

**Comment by tk0miya** [comment]
Merged manually.

>I am not sure how to rebase this for 4.0.x but it would be nice if this could go into 4.0.x

You can do it with `git rebase` command. In this case, you can do it with `git rebase HEAD~1 --onto 4.x` (This rebases the last commit (`~1` means one commit) to the `4.x` branch.

**Comment by tk0miya** [comment]
Thank you for your contribution as always :-)

**Pull request closed without merging**
