### PR TITLE
CI: fix coverage job

### PR DESCRIPTION
**Pull request by AA-Turner**
#10361 

A

### CODE REVIEW

**Comment by tk0miya** [comment]
Okay, I'll merge this after CI pased. Let's see what will be happened after merging.

**Comment by AA-Turner** [comment]
> Okay, I'll merge this after CI pased. Let's see what will be happened after merging.

CI has passed. Hopefully it'll work! The issue was I forgot the `--site-packages` option from Tox.

A

**Comment by AA-Turner** [comment]
[Coverage passed](https://github.com/sphinx-doc/sphinx/runs/6261489287)!

A

**Comment by tk0miya** [comment]
Good work!

**Pull request merged**
