### PR TITLE
Add post transform

### PR DESCRIPTION
**Pull request by tk0miya**
To make post-processing extensible, I propose to add post transform mechanism.
This is based on Transform component of docutils (it's not reinvent of wheel!).

Now we are doing three post-processing on resolving phase:

* resolve cross references
* process only nodes
* emit doctree-resolved event (and invoke the handlers)

The first two are hard coded to env module. It makes BuildEnvironment too big and monolithic class. To keep maintainable our software, it would be better to follow Single Responsibility Principle (SRP).
On the other hand, for third one, it is hard to change the order of event handlers. It is determined by the order of registration hooks (usually equals to order of extensions loaded).

The advantage of this PR is:

* Make BuildEnvironment simple
* less coupling
* Allow to order the post processing (through `Transform.default_priority`)

Also there are disadvantages:

* Make sphinx difficult (a little?)
* Hard to understand how it works from source code (because it's already big framework!)

I'd like to hear your opinions to merge this.

Thanks,

### CODE REVIEW

**Comment by tk0miya** [comment]
In addition, I'd like to implement image conversion feature (like #2859) using post-transform.
It needs to process multi-stage:
* download remote images
* convert application specific images to standard format
* convert standard images to the images which builders support
* other processing (triming, resizing, ...)

**Review by shimizukawa — APPROVED** [review]
LGTM.

BTW, we should describe this transform process on our doc. I think  `Build Phases` is better location of that:
http://www.sphinx-doc.org/en/stable/extdev/tutorial.html#build-phases

**Comment by tk0miya** [comment]
Merged. Thank you for quick reviewing!

**Comment by jfbu** [comment]
@tk0miya It seems the merge of this into master broke build of Sphinx own latexpdf docs. Here is the error log

```
# Sphinx version: 1.6
# Python version: 3.5.3 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:

# Loaded extensions:
#   sphinx.environment.collectors.dependencies (unknown version) from /Users/sphinxrepo/sphinx/environment/collectors/dependencies.py
#   sphinx.environment.collectors.title (unknown version) from /Users/sphinxrepo/sphinx/environment/collectors/title.py
#   sphinx.environment.collectors.indexentries (unknown version) from /Users/sphinxrepo/sphinx/environment/collectors/indexentries.py
#   sphinx.ext.autosummary (1.6) from /Users/sphinxrepo/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.viewcode (1.6) from /Users/sphinxrepo/sphinx/ext/viewcode.py
#   sphinx.ext.todo (1.6) from /Users/sphinxrepo/sphinx/ext/todo.py
#   alabaster (0.7.10) from /opt/miniconda3/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6) from /Users/sphinxrepo/sphinx/ext/autodoc.py
#   sphinx.ext.extlinks (1.6) from /Users/sphinxrepo/sphinx/ext/extlinks.py
#   sphinx.environment.collectors.asset (unknown version) from /Users/sphinxrepo/sphinx/environment/collectors/asset.py
#   sphinx.environment.collectors.toctree (unknown version) from /Users/sphinxrepo/sphinx/environment/collectors/toctree.py
#   sphinx.environment.collectors.metadata (unknown version) from /Users/sphinxrepo/sphinx/environment/collectors/metadata.py
#   sphinx.ext.doctest (1.6) from /Users/sphinxrepo/sphinx/ext/doctest.py
Traceback (most recent call last):
  File "/Users/sphinxrepo/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/sphinxrepo/sphinx/application.py", line 361, in build
    self.builder.build_update()
  File "/Users/sphinxrepo/sphinx/builders/__init__.py", line 274, in build_update
    self.build(['__all__'], to_build)
  File "/Users/sphinxrepo/sphinx/builders/__init__.py", line 346, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/sphinxrepo/sphinx/builders/latex.py", line 139, in write
    appendices=((docclass != 'howto') and self.config.latex_appendices or []))
  File "/Users/sphinxrepo/sphinx/builders/latex.py", line 189, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "/Users/sphinxrepo/sphinx/environment/__init__.py", line 924, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/Users/sphinxrepo/sphinx/environment/__init__.py", line 935, in apply_post_transforms
    transformer.apply_transforms()
  File "/Users/sphinxrepo/sphinx/transforms/__init__.py", line 88, in apply_transforms
    Transformer.apply_transforms(self)
  File "/opt/miniconda3/lib/python3.5/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/Users/sphinxrepo/sphinx/transforms/post_transforms.py", line 45, in apply
    refdoc = node.get('refdoc', self.env.docname)
  File "/Users/sphinxrepo/sphinx/transforms/__init__.py", line 65, in env
    return self.document.settings.env
AttributeError: 'Values' object has no attribute 'env'
```

tested on a checkout of dbffb05. The previous merge at df68d3d is OK.

**Comment by tk0miya** [comment]
Fixed, thanks

**Pull request merged**
