### PR TITLE
Fix/agogo

### PR DESCRIPTION
**Pull request by gvimont**
Subject: <short purpose of this pull request>

### Feature or Bugfix

- Bugfix

### Purpose
This improves the display of the sidebar of the agogo theme

### Relates
 #10715

### CODE REVIEW

**Comment by tk0miya** [comment]
@mgeier Could you check this please?

**Comment by mgeier** [comment]
This doesn't fully restore the CSS from before https://github.com/sphinx-doc/sphinx/pull/10520/files (e.g. the `rightsidebar` option is ignored).

I don't think the `pagewidth = 100%` change is good, because it removes the left/right margin of the page and the text touches the edge of the window.

The `sidebar` directive is still not properly styled, but I guess no `agogo` user uses that.

I'm not sure it's worth trying to fix `agogo`. Maybe it's best to revert #10520 and accept that it is broken?

Just out of curiosity: @gvimont Do you actually use the `agogo` theme? Or how did you notice the problem?

**Comment by gvimont** [comment]
Yes, I'm actually using it (but I could probably use another theme).
I could change `pagewidth` to a better value.
As you said, another solution is to revert #10520, and the theme could be marked as deprecated if it is not maintained anymore.

**Comment by mgeier** [comment]
I've created an alternative PR which reverts my previous change: #10787

**Comment by AA-Turner** [comment]
I'll accept the revert commit.

A

**Pull request closed without merging**
