### PR TITLE
Remove ``sphinx.util.inspect.isNewType``

### PR DESCRIPTION
**Pull request by AA-Turner**

### CODE REVIEW

**Comment by kiwifb** [comment]
Is there a matching documentation? I cannot see anything about this at https://www.sphinx-doc.org/en/master/extdev/deprecated.html Is there anywhere where we can find why it did not go through deprecation and directly to undocumented removal? I just bumped into this while trying to build sagemath documentation with 8.0.0_rc1 after checking that all the documented as removed in 8.0 API are gone from the code.

**Comment by AA-Turner** [comment]
Hi François, from our perspective this is a purely internal API, note that we don't document it in https://www.sphinx-doc.org/en/master/extdev/index.html. I can add a note to the changelog if useful, perhaps?

A

**Comment by kiwifb** [comment]
Thanks for the kind answer. It makes sense if it is supposed to be an internal API. sagemath has clearly been using something they should not. To be fair we have been trying to get rid of the old copy of autodoc.py shipped into sagemath and that needs to be changed every major release of sphinx or so.
That'll give me something to do.

**Comment by AA-Turner** [comment]
See b0485f932309e910c8c9961dcd7177a7c661085a for a migration note. 

The full old definition of the function (if you need to vendor it) was:

```python
def isNewType(obj: Any) -> bool:
    """Check the if object is a kind of :class:`~typing.NewType`."""
    if sys.version_info[:2] >= (3, 10):
        return isinstance(obj, typing.NewType)
    __module__ = safe_getattr(obj, '__module__', None)
    __qualname__ = safe_getattr(obj, '__qualname__', None)
    return __module__ == 'typing' and __qualname__ == 'NewType.<locals>.new_type'
```

**Comment by kiwifb** [comment]
Thanks for all the pointers but I may try something more ambitious (get rid of https://github.com/sagemath/sage/blob/develop/src/sage_docbuild/ext/sage_autodoc.py) and see how hard it is to adapt.

**Pull request merged**
