### PR TITLE
🔧 Remove flake8 (replaced by ruff)

### PR DESCRIPTION
**Pull request by chrisjsewell**
Unless I am missing something, ruff now has full parity with flake8: https://docs.astral.sh/ruff/faq/#how-does-ruffs-linter-compare-to-flake8, and so there is no need to keep using it anymore?

### CODE REVIEW

**Comment by picnixz** [comment]
I don't know much about flake8 so I'll leave it to daniel.

**Comment by danieleades** [comment]
not quite perfect parity yet, see https://github.com/astral-sh/ruff/issues/2402

personally i'm in favour of doing it anyway, but this was recently rejected - https://github.com/sphinx-doc/sphinx/pull/11902

**Review by jayaddison — APPROVED** [review]
Yep, this makes sense to me.  Fewer CI compute resources spent (despite this being a relatively quick-running one), and we can always occasionally run `flake8` locally, or even re-add it later, if there are any concerns.

I grepped for `flake8` in the `doc`, `utils`, `README.rst`, `CONTRIBUTING.rst` -- and found no results.

**Comment by picnixz** [comment]
So we are missing:

> E122 ("continuation line missing indentation or outdented")
E124 ("closing bracket does not match visual indentation")
E125 ("continuation line with same indent as next logical line")
E127 ("continuation line over-indented for visual indent")
E128 ("continuation line under-indented for visual indent")
E129 ("visually indented line with same indent as next logical line")
E131 ("continuation line unaligned for hanging indent")

Nevertheless, I'm wondering if with `ruff format` we would automatically fix them. Thoughs @danieleades ?

**Comment by danieleades** [comment]
> So we are missing:
> 
> > E122 ("continuation line missing indentation or outdented")
> > E124 ("closing bracket does not match visual indentation")
> > E125 ("continuation line with same indent as next logical line")
> > E127 ("continuation line over-indented for visual indent")
> > E128 ("continuation line under-indented for visual indent")
> > E129 ("visually indented line with same indent as next logical line")
> > E131 ("continuation line unaligned for hanging indent")
> 
> Nevertheless, I'm wondering if with `ruff format` we would automatically fix them. Thoughs @danieleades ?

i would guess so, but i don't know for sure

**Comment by picnixz** [comment]
@chrisjsewell I fixed your local conflict (but I forgot to ask you whether it's fine; if not, I won't do it in the future).

**Comment by chrisjsewell** [comment]
> but I forgot to ask you whether it's fine; if not, I won't do it in the future

no problem, thanks for mentioning 😄

**Comment by AA-Turner** [comment]
We can remove flake8 when Ruff implements the remaining rules, or we decide to adopt autoformatting. Neither is yet the case, so closing.

**Pull request closed without merging**
