### PR TITLE
Fix #4214: Two todolist directives break sphinx-1.6.5

### LINKED ISSUE #4214: Two todolist directives break sphinx-1.6.5
### Problem
- Two todolist directives in one document break `make html`

#### Procedure to reproduce the problem
```
1. put `.. todo:: some` on some doc source.
2. put two `.. todolist::` on some doc source.
3. enable todo extension in conf.py
4. do `make html`
```

#### Error logs / results
```
# Sphinx version: 1.6.5
# Python version: 2.7.10 (CPython)
# Docutils version: 0.14-
# Jinja2 version: 2.9.6
# Last messages:
#   writing output... [ 92%] reverse-dict/writing/indexing
#   writing output... [ 92%] reverse-dict/writing/link
#   writing output... [ 93%] reverse-dict/writing/note
#   writing output... [ 93%] reverse-dict/writing/numbering
#   writing output... [ 94%] reverse-dict/writing/only
#   writing output... [ 94%] reverse-dict/writing/refer
#   writing output... [ 95%] reverse-dict/writing/replace
#   writing output... [ 96%] reverse-dict/writing/strike
#   writing output... [ 96%] reverse-dict/writing/today
#   writing output... [ 97%] reverse-dict/writing/todo
# Loaded extensions:
#   japanesesupport (unknown version) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/source/japanesesupport.pyc
#   sphinx.ext.todo (1.6.5) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.10) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinxcontrib.gist (unknown version) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinxcontrib/gist/__init__.pyc
Traceback (most recent call last):
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 434, in write
    self._write_serial(sorted(docnames))
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 441, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 911, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 963, in apply_post_transforms
    self.app.emit('doctree-resolved', doctree, docname)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/ext/todo.py", line 181, in process_todo_nodes
    del todo_entry['targetref']
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/docutils/nodes.py", line 594, in __delitem__
    del self.attributes[key]
KeyError: 'targetref'
```
- https://app.wercker.com/sphinxjp/sphinx-users.jp/runs/build/59f806598e888f0001d5feb0

#### Expected results
no error

### Reproducible project / your project
- https://github.com/sphinxjp/sphinx-users.jp/tree/961cc48f57d30ced4ffbca25783390bfaa850d47

(note that it is not a small project)

### Environment info
- OS: any
- Python version: 2.7.10
- Sphinx version: 1.6.5 (1.6.4 doesn't have this error)

### PR DESCRIPTION
**Pull request by Smattr**
Subject: Fix #4214: Two todolist directives break sphinx-1.6.5

### Feature or Bugfix
- Bugfix

### Purpose
Version 1.6.5 introduced a bug which prevented building documents using the `todolist` admonition twice. This patch series fixes this issue.

### Detail
There's a few suboptimal aspects to these changes:
1. Because of the way the todo extension treats the todo nodes and the nodes in todolists similarly, the logic for dealing with targetref is still a bit peculiar.
2. The test case simply modifies the existing todo test document, which necessitates some changes to another previous test case. It looks like each extension's tests rely on a single document so I've introduced two `todolist` admonitions into the existing todo document. It may be cleaner to create a separate document somewhere to exercise this functionality.

@shimizukawa can you confirm these changes resolve #4214? Thanks.

### Relates

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
LGTM.
BTW could you rebase this to stable branch? because this is a bugfix. Then I will merge this soon.

**Review by shimizukawa — APPROVED** [review]
LGTM (please rebase onto stable)

**Comment by Smattr** [comment]
Rebased and retargeted at stable. Sorry, didn't notice that I'd targeted the pull request at master.

**Review by shimizukawa — APPROVED** [review]
LGTM!

**Comment by Smattr** [comment]
Are there more changes required on this one? There's one CI failure, but it is a version conflict that I don't fully understand. Do you know what this failure is indicating?

```
Exception calling "UpdateBuildDetails" with "10" argument(s): "Build with specified version already exists."
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:41 char:5
+     [Appveyor.BuildAgent.Api.RestBuildServices]::UpdateBuildDetails($ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Exception
```

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Merged.
Thanks a lot!

**Pull request merged**
