### PR TITLE
Remove the custom smartypants code [rebased]

### PR DESCRIPTION
**Pull request by mitya57**
Remove the custom smartypants code, instead rely on docutils’ ‘[smart_quotes](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/utils/smartquotes.py)’ option which is available since docutils 0.10. See #3345 for details.

This adds support for internationalization: our code supported only English quotes, while docutils code supports 27 different languages.

Add tests for English, French and Russian smart quotes.
Remove sphinxquotedblleft and sphinxquotedblright, should be no longer needed.

### CODE REVIEW

**Comment by tk0miya** [comment]
LGTM!

**Comment by jfbu** [comment]
LGTM !

**Comment by tk0miya** [comment]
Merged. Thank you for great work!

@jfbu good reviewing!

**Comment by jfbu** [comment]
@mitya57 thanks for all your efforts, we count upon you to continue backporting docutils fixes if needed ;-)

**Comment by jfbu** [comment]
Hi @mitya57 do you mind if we add your name at https://github.com/sphinx-doc/sphinx/blob/1.6-release/CHANGES#L28 in a "Thanks ... " notice for 1.6 release ?

**Comment by jfbu** [comment]
... and I will ask the same from G. M. at docutils

**Comment by mitya57** [comment]
@jfbu Of course I do not mind.

**Comment by jfbu** [comment]
@mitya57 ok, great! sometimes people prefer anonymity. I will add a thanks to G. M. too !

**Comment by ericholscher** [comment]
Just wanted to note that having Sphinx recommend users use a `docutils.conf` seems like a bad user experience. From what I've seen, a Sphinx user has never had to ever use this config file, and likely shouldn't need to ever use it. Is there a reason not to allow a user to set it in Sphinx and pass that along into docutils, instead of requiring an entirely separate configuration file?

**Comment by mitya57** [comment]
@ericholscher In https://github.com/sphinx-doc/sphinx/pull/3562#discussion_r111664415, I proposed two options: dropping the option completely or making it map to the docutils option. Then @tk0miya voted for removing it.

A regular user would rarely need to use `docutils.conf`: SmartyPants are enabled by default and correspond to the project language. That file should be used either when one wants to disable SmartyPants or choose another set of quotes. The latter was impossible in previous Sphinx versions, so even with an external configuration file it is an improvement rather than a regression.

What is your use case?

**Comment by hynek** [comment]
I think the main pain point here is that the warning seems to imply that we need a global config to have  nice quotes.  Maybe change the wording to “it’s on by default, if you need further configurability refer to…”?

**Comment by mitya57** [comment]
Good idea, done in #3795.

**Comment by tk0miya** [comment]
Sphinx has supports docutils.conf from the past (maybe 1.2 or 1.3). It's not new feature.
So far, docutils provides better default settings. So it is not needed to move the options to sphinx's, I think.

**Pull request merged**
