### PR TITLE
(this pull request was a user error)

### PR DESCRIPTION
**Pull request by Toast063**
Reverts 11105

### CODE REVIEW

**Comment by Toast063** [comment]
Build document / build (pull_request) Successful in 1m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901830/jobs/6594658905)

CI (LaTeX) / Test on LaTeX image (pull_request) Successful in 4m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901829/jobs/6594658895)

CI (node.js) / build (pull_request) Successful in 36s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901832/jobs/6594658892)

CI / Python 3.8 (du18) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594658896)

Lint source code / build (docslint) (pull_request) Successful in 23s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901833/jobs/6594659487)

CI / Python 3.8 (du19) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594658926)

Lint source code / build (flake8) (pull_request) Successful in 31s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901833/jobs/6594659531)

CI / Python 3.8 (du-latest) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594658959)

Lint source code / build (isort) (pull_request) Successful in 25s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901833/jobs/6594659596)

CI / Python 3.9 (du18) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594658986)

Lint source code / build (mypy) (pull_request) Successful in 35s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901833/jobs/6594659635)

CI / Python 3.9 (du19) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659020)

Lint source code / build (twine) (pull_request) Successful in 50s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901833/jobs/6594659680)

CI / Python 3.9 (du-latest) (pull_request) Successful in 4m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659050)

CI / Python 3.10 (du18) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659084)

CI / Python 3.10 (du19) (pull_request) Successful in 4m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659107)

CI / Python 3.10 (du-latest) (pull_request) Successful in 4m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659138)

CI / Python 3.11 (du18) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659170)

CI / Python 3.11 (du19) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659206)

CI / Python 3.11 (du-latest) (pull_request) Successful in 4m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659243)

CI / Python 3.12-dev (du18) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659280)

CI / Python 3.12-dev (du19) (pull_request) Successful in 3m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659322)

CI / Python 3.12-dev (du-latest) (pull_request) Successful in 4m
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659354)

CI / windows (pull_request) In progress — This check has started...
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901831/jobs/6594659386)

Lint source code / ruff (pull_request) Successful in 11s
[Details](https://github.com/sphinx-doc/sphinx/actions/runs/3868901833/jobs/6594659774)

docs/readthedocs.org:sphinx — Read the Docs build succeeded!
[Details](https://sphinx--11114.org.readthedocs.build/en/11114/)
This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.


 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/sphinx-doc/sphinx/blob/e5bdb93788b2f980ff202a635f9e52a2d4442a20/CONTRIBUTING.rst) and [code of conduct](https://github.com/sphinx-doc/sphinx/blob/e5bdb93788b2f980ff202a635f9e52a2d4442a20/CODE_OF_CONDUCT).
 ProTip! Add comments to specific lines under [Files changed](https://github.com/sphinx-doc/sphinx/pull/11114/files).
Reviewers
No reviews
Still in progress? 
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
Successfully merging this pull request may close these issues.

None yet

Notifications
Customize
You’re receiving notifications because you authored the thread.
1 participant

Allow edits by maintainers
Footer
© 2023 GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/en/github/site-policy/github-terms-of-service)
[Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
[Contact GitHub](https://support.github.com/?tags=dotcom-footer)
[Pricing](https://github.com/pricing)
[API](https://docs.github.com/)
[Training](https://services.github.com/)
[Blog](https://github.blog/)
[About](https://github.com/about)

**Comment by jfbu** [comment]
@Toast063 can you explain why you wish to revert #11105?

**Comment by Toast063** [comment]
Just got hooked by help centre for showing up how respiratory work and will likely to learn more...

**Comment by jfbu** [comment]
alright, closing then

**Comment by Toast063** [comment]
Either way I was just trying to install some package

**Pull request closed without merging**
