### PR TITLE
gettext: Use template file to generate message catalog

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Refactoring

### Purpose
- As a preparation of #6781, this replaces string concatenations in gettext builder by template file.

### CODE REVIEW

**Comment by tisonkun** [comment]
Thanks for opening this pull request @tk0miya . Unfortunately I can hardly review the change set without learning how the framework works. But I think I'm able to help with verify the result if you ask for :-)

**Comment by tk0miya** [comment]
@TisonKun Thank you for comment. Don't mind. This is a mere refactoring change. I'll work for your problem in next step. Please help me in that time if needed :-)

**Comment by jfbu** [comment]
@tk0miya It seems `test_gettext_dont_rebuild_mo` test [fails on 2.0 branch](https://ci.appveyor.com/project/sphinxdoc/sphinx/builds/28880047/job/5fuoskuqik2g1yuc) is it related to this changeset?

**Comment by tk0miya** [comment]
No, it is related with this. It might be related with timestamp system of windows.

**Pull request merged**
