### PR TITLE
Convert ``latin_terms`` to a set

### PR DESCRIPTION
**Pull request by AA-Turner**
Towards https://github.com/python/docsbuild-scripts/issues/209.

A

### CODE REVIEW

**Review by jayaddison — COMMENTED** [review]
Nice find! :+1:

**Comment by jayaddison** [comment]
@AA-Turner possibly worth a changelog entry?  (potentially relevant for folks building large and/or many localized projects?)

**Comment by AA-Turner** [comment]
There's one already:

> "Significantly improve performance when building the search index for Chinese languages."

Are you suggesting changes?

A

**Comment by jayaddison** [comment]
Oops, I'm not sure how I missed that; no, that looks fine - thanks!

**Pull request merged**
