### PR TITLE
[tests] skip tests that need remote content if host is offline

### PR DESCRIPTION
**Pull request by picnixz**
Don't forget people who work offline!

### CODE REVIEW

**Comment by jayaddison** [comment]
@picnixz `test_run_epubcheck` unexpectedly fails offline too, and could be worth adding to the list here.

The reason for that is quite obscure: it seems that we write a slightly different output `.epub` file containing 'remote references' if we're unable to download the content locally during the build.  When `epubcheck` checks the (different) resulting output, it isn't happy about those remote references and complains.

I don't know of a way to run GitHub Actions workflows in a way that prevents them from making outbound network connectivity, but such a thing might exist.

**Comment by picnixz** [comment]
I actually don't run it because I don't have epubcheck.. so... I never saw the error.

**Comment by jayaddison** [comment]
Yep, neither had I previously - I'm trying to make the tests behave more similarly offline and online after seeing this change.  In particular: replacing some of the remote image links with content served by our good friend `localhost:7777`.

When I did that, I tried to get as many skipped tests to run as possible (in case I'd missed any other cases), and found that `test_run_epubcheck` failed.. but only when offline!  Weird.

**Comment by jayaddison** [comment]
Filed the details as #12094 - there are some easy-ish small improvements, and it may be low priority, but I'll try to suggest one or two adjustments soon.

**Pull request merged**
