### PR TITLE
CI: Replace broken repo.or.cz with github.com

### PR DESCRIPTION
**Pull request by hugovk**
### Feature or Bugfix

- Bugfix

### Purpose
- Fix the "Docutils HEAD" job on the CI

### Detail

The CI clones docutils from https://repo.or.cz/docutils.git but https://repo.or.cz is down. 

Replace it with the mirror at https://github.com/docutils/docutils.

### Relates
- https://github.com/sphinx-doc/sphinx/pull/11793 for more CI fixes.

### CODE REVIEW

**Comment by picnixz** [comment]
The docutils repo hosted on github is unfortunately not sync'd with the one from sourceforge. I think we need to schedule a job for that on the github repo if possible (but I don't have any permissions for that).

@AA-Turner is there a way to sync whatever you do on docutils side with github directly? 

Otherwise, we need to clone it using svn from https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/

**Comment by hugovk** [comment]
Updated to install from https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/

**Comment by picnixz** [comment]
Once we fixed the weakref issues, I think this one is fine. 

We are currently re-organizing Sphinx internally so we won't merge anything until January 2024 (I am only available for 1 week roughly (probably 4 days actually) until February so I prefer that the easy PRs are done in one go by at least 2 people in case of something happening).

**Comment by hugovk** [comment]
Presumably closed because https://repo.or.cz/docutils.git is back up.

**Comment by AA-Turner** [comment]
Yes, sorry

**Pull request closed without merging**
