### PR TITLE
[doc] Rework "templating" documents

### PR DESCRIPTION
**Pull request by stephenfin**
Make some minor tweaks to what is otherwise an excellent document.

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
LGTM!

**Comment by tk0miya** [comment]
Is there any reason to choose master branch?

**Comment by stephenfin** [comment]
Nope. I just forget about the branching model here every time :see_no_evil: How far out is the 4.0 release, i.e. is it worth rebasing this?

**Comment by tk0miya** [comment]
4.0 will be released in next Spring. My concern is conflicts between 3.x branch. It would be better to rebase if no special reason (other PRs also).

**Comment by stephenfin** [comment]
> 4.0 will be released in next Spring. My concern is conflicts between 3.x branch. It would be better to rebase if no special reason (other PRs also).

Sure. Done.

**Comment by tk0miya** [comment]
Thank you always :-)

**Pull request merged**
