### PR TITLE
Deprecate EpubBuilder.esc() in favor of stdlib html.escape()

### PR DESCRIPTION
**Pull request by jdufresne**
Available since Python 3.2.

https://docs.python.org/3/library/html.html#html.escape

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
+1: Reasonable.

Could you rebase this to 2.0 branch? It would be helpful if you'll add an entry to CHANGES and doc/extdev/deprecation.rst  :-)

**Comment by jdufresne** [comment]
Done in the latest revision.

**Review by tk0miya — APPROVED** [review]
LGTM!

**Comment by tk0miya** [comment]
Merged. Thank you always!

**Pull request merged**
