### PR TITLE
CHANGES: nitpick: credit/attribution fixup for #11431

### PR DESCRIPTION
**Pull request by jayaddison**
### Feature or Bugfix
- Nitpick

### Purpose
- Fixup for an entry in the `CHANGES` file.

### Detail
- See pull request #11431 discussion / commits for context.

### Relates
- #11431

### CODE REVIEW

**Comment by AA-Turner** [comment]
Sorry!

**Comment by jayaddison** [comment]
No problem :)  Thanks for merging!

**Comment by picnixz** [comment]
@jayaddison  Oh, was it my fault? did I messed up when I changed something in vim? Sorry if it were the case !

**Comment by jayaddison** [comment]
Hey @picnixz - it's ok; no idea how it happened, and I'm not planning to check the `blame` logs for it.  The main reason I fixed it was so that anyone looking for info about the recent linkcheck refactor and related bugs could find and ping me.  A secondary reason is accurate crediting, and I'm a little sensitive about that at the moment, but it's less important to me than the ease-of-contact.

**Pull request merged**
