### PR TITLE
fixes #3959 alias/rename support for classes inside inheritence diagrams

### LINKED ISSUE #3959: inheritance diagram should support rename/alias
Often there can be a discrepancy between what's the fully qualified name of a class and how it's exposed. For example, the PyTest module has it's code in _pytest package, but enumerates and exposes stuff in a pytest.py module (which loads the relevant classes from _pytest). Exposing at a different entry point is possible via tools such as autodoc, by just using the appropriate path (so e.g. pytest.Magic instead of _pytest.code.Magic). Autodoc e.g. also generates this aliased links/references for these classes (so the inheritance diagram links will be broken upon using this feature of autodoc). 

In such cases we should offer some kind of way so that the user can build an inheritance without exposing the underlying actual path (so e.g. can set that _pytest.code.Magic is actually pytest.Magic, and _pytest.magic.BaseMagic is pytest.BaseMagic). Classes not overwritten can keep their fully qualified name. 

Does that make sense?

I believe the appropriate aliasing could be done here https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/inheritance_diagram.py#L216 by using a configuration value map to specify what alter to what (allowing the user to define in the conf.py what alias to use for what fully qualified name).

### PR DESCRIPTION
**Pull request by gaborbernat**
as discussed in #3959

### CODE REVIEW

**Comment by gaborbernat** [comment]
@tk0miya can you please advise why the test fails sometimes but succeeds other times?

**Comment by tk0miya** [comment]
It seems `class_info` is values of dict. So it is not ordered. Please use `set` to compare the lists.

**Comment by gaborbernat** [comment]
thanks, @tk0miya now it should be fine, let me know if you need anything else; 1.7 seems also far away though :open_mouth:

**Comment by gaborbernat** [comment]
@tk0miya does this look good, do you need anything else?

**Comment by tk0miya** [comment]
Thank you for update. Merged.
It will be shipped as 1.7 (because this is new feature!).

**Pull request merged**
