### PR TITLE
Disable default smartquotes for zh_CN and zh_TW

### LINKED ISSUE #12874: Inconsistent smart quotes for zh_CN and zh_TW
### Describe the bug

docutils is unable to differentiate between opening and closing quotes in Chinese text, as words in Chinese are written without spaces too.

### How to Reproduce

`index.rst`  
```rst
我喜歡"書"和"音樂"。
```
`conf.py`
```py
language="zh_TW"
```
Build:
```bash
sphinx-build . build
```
`./build/index.html` contains:
```
我喜歡」書」和」音樂」。
```
#### Expected Output:
```
我喜歡「書」和「音樂」。
```
Similar procedure for language=`zh_CN`

### Environment Information

```text
Platform:              linux; (Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.39)
Python version:        3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0])
Python implementation: CPython
Sphinx version:        8.0.2
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

_No response_

### Additional context

Relates to issue #4142.

### Solution
Disable default smartquotes behavior for zh_CN and zh_TW languages too.

### PR DESCRIPTION
**Pull request by khanxmetu**
Subject: Disable default smartquotes for zh_CN and zh_TW

### Feature or Bugfix
- Bugfix

### Purpose
- To disable default smartquotes behavior for zh_CN and zh_TW languages too via `confval:: smart_quotes_excludes`
- Issue #12874
### Relates
- #12874, #4142
- Closes #12874

### CODE REVIEW

**Review by Danysharma00 — APPROVED** [review]

**Review by Danysharma00 — APPROVED** [review]

**Comment by picnixz** [comment]
Merging HEAD into this branch to avoid mypy failures.

**Review by picnixz — APPROVED** [review]
Seems right to me. Are there other languages that suffer from this?

Oh by the way, I think I want a CHANGELOG entry. This is a change in the output being produced so it would be good to indicate that the support has been disabled for those languages.

**Comment by khanxmetu** [comment]
> Seems right to me. Are there other languages that suffer from this?

Not that I'm aware of... The languages affected by the problem of not having word separators are [Scriptio continua](https://en.wikipedia.org/wiki/Scriptio_continua). In modern writing and among those that Sphinx supports only Chinese and Japanese are affected.

> Oh by the way, I think I want a CHANGELOG entry. This is a change in the output being produced so it would be good to indicate that the support has been disabled for those languages.

Added

**Comment by picnixz** [comment]
Once the CI/CD passes, I'll merge it!

**Comment by picnixz** [comment]
Thank you!

**Pull request merged**
