### PR TITLE
Simplify ``Tags``

### PR DESCRIPTION
**Pull request by AA-Turner**
- Use a set to store the list of tags
- Cache evaluated expressions
- Extract locally-defined function into a private method

Only usages of ``Tags.tags`` I've been able to find:

* https://github.com/useblocks/sphinx-collections/blob/37b54c0a78e1772aabe13634ea2e2211749ac865/sphinxcontrib/collections/collections.py#L77-L81
* https://github.com/useblocks/sphinx-needs/blob/1de1a7a047bfc7912ea0aa779ffb187def7a5254/sphinx_needs/directives/need.py#L383
* https://github.com/pybricks/pybricks-api/blob/f35bbe44f5c4738fb18aee7f794722413e82fef9/doc/common/extensions/versionchanged.py#L22
* https://github.com/Arize-ai/phoenix/blob/c4e1d5ff754950d41a9f1a1ca2c7b1efdcabff98/api_reference/source/conf.py#L9-L16
* https://github.com/ManimCommunity/manim/blob/8d70b0e886db0f9447f12723a936c47d83777279/manim/utils/docbuild/manim_directive.py#L174-L179

A

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Thanks @AA-Turner looks all good generally

> Cache evaluated expressions

My only word of warning on caching, is just to watch for cache invalidation and unbounded caches leading to large memory usage.

I see this, having recently ran into issues with the added doctree caching (https://github.com/sphinx-doc/sphinx/pull/12431)

Here though, I don't think its so much of an issue, as I believe the tags are only stored transiently on the `Sphinx` application, and I doubt someone is going to be using 1000s of different tag conditions 😅

**Review by chrisjsewell — APPROVED** [review]

**Comment by AA-Turner** [comment]
I agree and considered the risk, my thinking is that this is a simple string to Boolean map so fairly light on memory, and also the number of unique instances ought be fairly low as when `only` directives are used, the actual underlying conditions are frequently repeated.

Thanks for the quick review!

A

**Comment by AA-Turner** [comment]
(For some context, this PR and #12491 are in preparation for improving the experience with parsing rST to Docutils nodes—I will open that PR shortly)

**Comment by AA-Turner** [comment]
> does [pytest-dev/pytest@`51ee388`/doc/en/conf.py#L36-L43](https://github.com/pytest-dev/pytest/blob/51ee388/doc/en/conf.py?rgh-link-date=2024-07-02T12%3A45%3A12Z#L36-L43) count as one of the uses you were looking for?

That is expected usage, see https://www.sphinx-doc.org/en/master/usage/configuration.html#conf-tags

> There is a special object named `tags` available in the config file. It can be used to query and change the tags (see [Including content based on tags](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#tags)). Use `'tag' in tags` to query, `tags.add('tag')` and `tags.remove('tag')` to change. Only tags set via the `-t` command-line option or via `tags.add('tag')` can be queried using `'tag' in tags`. Note that the current builder tag is not available in `conf.py`, as it is created _after_ the builder is initialized.

The issue is when the internal collection of tag names (unhelpfully named ``Tags.tags``) is used, as that ought be an opaque structure.

A

**Pull request merged**
