### PR TITLE
Fix #2602: URL redirection breaks the hyperlinks generated by `sphinx.ext.intersphinx`

### LINKED ISSUE #2602: autodoc type links broken for Python builtins
I can't be exactly sure if this is the fault of Sphinx or Python itself, but if the latter, then either Sphinx needs changes or documentation examples.

I have quite a number of projects that make use of autodoc to process docstrings like the following:

```
def foo(bar):
    """
    Do something

    :param bar: my variable
    :type bar: list
    """
```

As of May 21st, this was working correctly, though it would link `list` to the [function reference](https://docs.python.org/library/functions.html#list). However, as of today, these automatic links to python builtins (i.e. `:type varname: <list|str|...>`) are failing. I can confirm on one of my projects that hasn't had any code changes at all that the build [worked on May 21st](https://travis-ci.org/jantman/awslimitchecker/jobs/131914533) and [failed when re-run automatically on May 27th](https://travis-ci.org/jantman/awslimitchecker/jobs/133296992). I first discovered this issue on a new, not-yet-released project, but it's happening on other [projects](https://travis-ci.org/jantman/vault-redirector-twisted/jobs/133297815) as well.

```
Warning, treated as error:

/home/travis/build/jantman/vault-redirector-twisted/docs/source/vault_redirector.redirector.rst:2: WARNING: broken link: https://docs.python.org/library/functions.html#str
```

I've been using the same `:type paramname: typename` syntax for years, according to the Sphinx examples. Any idea why this suddenly stopped working, and what the issue is?

### PR DESCRIPTION
**Pull request by tk0miya**
This is fix for #2602.
Could anyone review this please? Because I don't know intersphinx in detail.

### CODE REVIEW

**Comment by jfbu** [comment]
I get following behaviour

```
Running Sphinx v1.4.2+
making output directory...
loading translations [fr]... done
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/scipy/reference/ -> http://docs.scipy.org/doc/scipy/reference
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
intersphinx inventory has moved: http://docs.python.org/3 -> https://docs.python.org/3
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/ -> http://docs.scipy.org/doc/numpy
loading intersphinx inventory from http://matplotlib.sourceforge.net/objects.inv...
intersphinx inventory has moved: http://matplotlib.sourceforge.net/ -> http://matplotlib.org
```

from using your patch with  a project having

```
intersphinx_mapping = {'python': ('http://docs.python.org/3', None),
   'numpy': ('http://docs.scipy.org/doc/numpy/', None),
   'scipy': ('http://docs.scipy.org/doc/scipy/reference/', None),
   'matplotlib': ('http://matplotlib.sourceforge.net/', None)}
```

in its conf.py. The messages about intersphinx repertory having moved are misleading ;-)

**Comment by jfbu** [comment]
but I discover the correct redirection `http://matplotlib.sourceforge.net/ -> http://matplotlib.org/` which I didn't notice so far ;-)

**Comment by jfbu** [comment]
ah sorry, this was reported only on first `make html`. And there is also a seemingly licit 

```
http://docs.python.org/3 -> https://docs.python.org/3
```

redirection.

**Comment by tk0miya** [comment]
Oh, I missed about "/" on tail. I update PR to ignore the case.

Thanks,

**Comment by tk0miya** [comment]
Merged manually.
Thank you for reviewing

**Pull request merged**
