### PR TITLE
Enable some doc comment lints (D*)

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by AA-Turner** [comment]
@danieleades -- please can you avoid force-pushing if possible, it makes reviewing more challenging.

**Comment by danieleades** [comment]
> @danieleades -- please can you avoid force-pushing if possible, it makes reviewing more challenging.

sure thing

**Comment by AA-Turner** [comment]
Dan -- out of interest would you be interested in having commit permissions on Sphinx? The work you've done on mypy/ruff is really appreciated (even if we disagree on autoformatters)

A

**Comment by danieleades** [comment]
> Dan -- out of interest would you be interested in having commit permissions on Sphinx?

I'm flattered that you're offering. I'm inclined to decline however- i'm enjoying tinkering away, but the ability to commit changes myself is not really a blocker for me, since i wouldn't want to commit any changes that hadn't passed consensus *anyway*. Thank you though.

> even if we disagree on autoformatters!

nothing wrong with a bit of healthy, constructive disagreement!

**Comment by AA-Turner** [comment]
Fair enough; do let me know if you reconsider in the future, though. Thanks again for your support for Sphinx!

A

**Pull request merged**
