### PR TITLE
Fix #2593: latex crashes if any figures in the table

### LINKED ISSUE #2593: Using .. list-table:: creates error on generating Latex pdf
To reproduce:

``` rest
Some paragraph text

.. list-table::

  * - .. figure:: /images/testimage01.png

    Test image01

   - .. figure:: /images/testimage02.png

   Test image02

Another paragraph
```

The reason I have set this up in this way is to be able to have 2 images on the same line. Right next to each other. Generating the html works but pdf gives the following error:

`! LaTeX Error: Not in outer par mode.`

`See the LaTeX manual or LaTeX Companion for explanation.`

`l.280 \hline\end{tabulary}`

I am using MikTex also with 1.4.2 of sphinx

### PR DESCRIPTION
**Pull request by tk0miya**
For #2593.

This is based on the macro written by @jfbu .
It allows to specify width using `:figwidth:` option.

I think this is not perfect yet, but it would be better than crash.

### CODE REVIEW

**Comment by jfbu** [comment]
@tk0miya I have cloned your branch and added a commit at https://github.com/jfbu/sphinx/tree/figure-in-table. I wanted to make a PR to your fork but somehow I don't see it listed in the pop-up menu from github when initiating a PR from my branch. I added to `\figcaption` handling of `tabulary` situation. What do you think?

question: I tested that  `:figwidth:` option works. There is already `:width:` option which ends up being used by the `\includegraphics` if present. Can't we use same option for both ? (I am not sure how latex.py recognizes `figwidth` as I see only `if 'width' in node:` in `latex.py`. But it does work.

**Comment by jfbu** [comment]
@tk0miya my question about replacing `:figwidth:` and `:width:` with only one was silly. I see now it is important to have both, for example the first one will delimit caption, and we don't always want caption of same width asi included image.

And I had not yet read the docutils documentation: http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure. I understand now how `figwidth` becomes `width` attributed of `figure` element.

**Comment by tk0miya** [comment]
Okay, I will merge your commit at tonight (in Japanese timezone).
If possible, could let me know about the trick for taburary. I don't understand that.

On the other hand, your understanding about `:figwidth:` is right. It is a part of reST specification.
I think the option is good for a such case.

Thank you for quick review!

**Comment by jfbu** [comment]
- The tabulary environment typesets (exactly) twice its contents.
- As a consequence all `\stepcounter` are evalued twice inside `tabulary`. In particular, as we will allow a figure caption, this means the figure counter will be incremented twice when `\caption` will be executed. To prevent this we need a way to inhibit `\stepcounter`.
- Package `amsmath`, or more precisely its sub-package `amstext`, does a patch to `\stepcounter`. It is now active only if conditional `\iffirstchoice@` evaluates to `\iftrue`.
- Reading the tabulary source I have discovered that it does `\let\equation$` for the first pass. Hence I use `\ifx\equation$` to identify this and then make `\firstchoice@false`.

Memo: currently amsmath package is loaded from default value of `'amsmath'` key in latex.py

```
        'amsmath':         '\\usepackage{amsmath,amssymb,amstext}',
```

but we should load `amstext` unconditionally, because user should have right to redefine `'amsmath'` to empty string. This is also needed in relation to https://github.com/sphinx-doc/sphinx/commit/488ee5279a7b595c2999df9b689514b8b2887b18. We should either document that `'amsmath'` key must at the minimal do `\\usepackage{amstext}`, or add forcibly `\usepackage{amstext}` to preamble, or add `\RequirePackage{amstext}` to sphinx.sty.

**Comment by jfbu** [comment]
Also some parts of `sphinx.sty` since PR #2297 (see commit 9d82cad) use the `\iffirstchoice@` conditional provided by `amstext`. This is other reason why `amstext` should be always loaded, even if user does not want `amsmath`.

I made PR #2619 about this.

**Comment by tk0miya** [comment]
Thank you for clearly explanation. I confirmed figure counter works fine with your additional commits.
Now I updated this PR including your commits.

I will merge this tomorrow if no comments or objections.

Thanks,

**Comment by tk0miya** [comment]
Merged. Thank you for reviewing :-)

**Comment by nmat** [comment]
This does indeed fix it...perfect!

**Pull request merged**
