### PR TITLE
Fix #3558: Emit warnings if footnotes and citations are not referenced

### LINKED ISSUE #3558: Auto numbering of footnote doesn't check missing
Subject: <what happen when you do on which document project>

### Problem

- Sphinx doesn't report footnote mismatch for auto numbering items.

```rst
Too many footnotes
------------------------

test1 [#]_
test2 [#]_

.. [#] footnote 1
.. [#] footnote 2
.. [#] footnote 3   (no warning and no error)
```

```rst
Less footnotes
==================

test1 [#]_
test2 [#]_ (warning)

.. [#] footnote 1
```

#### Expected results

I hope to get warning messages with the first sample. And I'd like to have extra strict mode (produce errors instead of warnings).

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #3558 

@shibukawa could you try this please?

### CODE REVIEW

**Comment by tk0miya** [comment]
ping @shibukawa 
The next weekend is deadline of next major release (It's time to code freeze!). If possible, could you review this please?
If not, I will merge without your reviewing.

**Review by shibukawa — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for reviewing!

**Comment by jschueller** [comment]
This seems to emit a false positive if a citation is referenced outside the current file: ```self.document```
In the documentation it's clearly stated that references/citations are global.

This break our build of openturns: https://circleci.com/gh/openturns/openturns/272?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link as we treat sphinx warnings as errors.

**Comment by kain88-de** [comment]
This change causes the sphinx build of [MDAnalysis](https://github.com/MDAnalysis/mdanalysis) to [fail](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/233939327). I don't see an error in the [rst-file](https://raw.githubusercontent.com/MDAnalysis/mdanalysis/develop/package/doc/sphinx/source/documentation_pages/analysis/encore.rst) as both references at the bottom actually are referenced in the text above.

**Comment by tk0miya** [comment]
@kain88-de did you mean this still does not work fine?
If so, I would like to investigate your case.

**Comment by kain88-de** [comment]
We recently switched our sphinx theme. That somehow fixed it. I can look if I find an old commit again that caused the problem.

**Comment by kain88-de** [comment]
I have a [branch](https://github.com/kain88-de/mdanalysis/tree/doc-build-fix) called `doc-build-fix` on my [fork](https://github.com/kain88-de/mdanalysis). There I exhibit the error that a citation is supposedly not referenced.

**Comment by tk0miya** [comment]
@kain88-de Thanks! I found incorrect warnings if citation labels contains hyphens.
Fixed again at 2f61be8bb.

**Comment by kain88-de** [comment]
Thanks

**Pull request merged**
