### PR TITLE
Add type-check annotations 

### PR DESCRIPTION
**Pull request by tk0miya**
As a trial, I added type-check annotations to Sphinx.
This reduces warnings from mypy (But still remaining) and helps to detect bugs automatically.

Note: This only adds annotations. I do not modify the codes basically.

### CODE REVIEW

**Comment by shimizukawa** [comment]
You've done a great work! LGTM!

**Comment by tk0miya** [comment]
any comments? If none, I'll merge this soon.

**Comment by shimizukawa** [comment]
Please go ahead!

**Comment by tk0miya** [comment]
Merged!

**Comment by tk0miya** [comment]
Our next step is adding type checking to CI process.
To do that, we have to resolve all errors about typing.
Surely it's hard, but I'm interested :-)

**Pull request merged**
