### PR TITLE
Fix #5391: A cross reference in heading is rendered as literal

### LINKED ISSUE #5391: Linked heading has undesirable font in toctree
Subject: Linked heading has undesirable font in toctree

### Problem
I am experimenting with making some of our headings be links. They show up in the TOC sidebar in the font used for the :any: links in our docs. Is there a way to tell sphinx to use the standard font in the sidebar TOC?

## Actual Result

Here's what the TOC looks like:

image

#### Procedure to reproduce the problem
```
test heading with link:

:ref:`Amazon Web Services<monitor-aws>`
-------------------------------------------------------------------

```

#### Expected results

Heading should look like the one right above it in the TOC

### Environment info
- OS: Mac High Sierra
- Python version: 2.7.11
- Sphinx version: 1.7.5

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #5391

### CODE REVIEW

**Comment by barbara-sfx** [comment]
@tk0miya 

 Hello -- I am still seeing this problem using Sphinx 1.8.4. Is there some setting somewhere I need to change?

heading-format

Source file (unable to upload RST format):


[toc-format-problemRST.txt](https://github.com/sphinx-doc/sphinx/files/3075239/toc-format-problemRST.txt)

**Comment by tk0miya** [comment]
This is fixed on 2.0.0. Please upgrade your Sphinx. Thanks,

**Comment by barbara-sfx** [comment]
@tk0miya  What does 2.0.0 refer to? I just ran `pip install -U sphinx` and got 1.8.5. Do I have to use the `--pre` option? I would rather not have to rely on a non-release version for production work.

**Comment by tk0miya** [comment]
@barbara-sfx Could it be that you're using python2? Sphinx-2.0 only supports python 3.5 or later. I guess it might be related in your case.

**Comment by barbara-sfx** [comment]
Ah yes, that is it. OK now I get to research how to upgrade my python version. Last time I tried I broke stuff. :-(   Thanks for your response.

**Pull request merged**
