### PR TITLE
Close #6361: autodoc: Add autodoc_typehints to suppress typehints from signature

### LINKED ISSUE #6361: enable removal of type hints from autodoc
The proposed #6353 solution to #6311 presents an interesting opportunity to consistently _and_ conveniently enable autodoc users to remove type hints.  This can be achieved in one of two ways

1. An autodoc config variable such as `autodoc_remove_type_hints` or something, which globally removes type hints from signatures.  And/or
2. An additional parameter to `"autodoc-process-signature"` event that is the documenter itself.

Type hints are great, but currently some of my signatures become very confused in the docs making it hard to understand.

**Describe the solution you'd like**

If we make the `documenter` available, this becomes quite simple.  A breaking change would be to just tack a `self` on at the end of the event.  I took a look around, but recovering the documenter from the information currently provided to `"autodoc-process-signature"` is not easy to do.

https://github.com/sphinx-doc/sphinx/blob/165897a74951fb03e497d6e05496ce02e897f820/sphinx/ext/autodoc/__init__.py#L406-L408

```diff
--- a/sphinx/ext/autodoc/__init__.py
+++ b/sphinx/ext/autodoc/__init__.py
@@ -413,7 +413,8 @@ class Documenter:
 
         result = self.env.events.emit_firstresult('autodoc-process-signature',
                                                   self.objtype, self.fullname,
-                                                  self.object, self.options, args, retann)
+                                                  self.object, self.options, args, retann,
+                                                  self)
         if result:
             args, retann = result
```

Giving the `documenter` (`self`) directly gives us a very clean way to remove type hints:

```py
# NOTE: only valid with #6353 (added show_annotation ability)
def autodoc_process_signature(app, what, name, obj, options, signature, return_annotation, documenter):
    # We are only modifying functions / methods.  Return None signals no change.
    if what not in {"function", "method"}:
        return None

    try:
        return documenter.format_args(show_annotation=False), return_annotation
    except:
        return None
```

**Considerations**

Adding an additional parameter is a breaking change.

```py
TypeError: autodoc_process_signature() takes 7 positional arguments but 8 were given
```

So the implementation should call with 8 and fallback to calling with 7, issuing a warning that 8 are required now (?).

I'm happy to implement this with some discussion.  For example, with (1) adding a global option, would it be better to do something like

```py
autodoc_remove_type_hints = [
    "function", "method"
]
```

so that it's only done for specific types?  To be honest, I'd be thrilled with just (2) and add documentation showing users how to remove type hints if they want since it's very little code on their part, and trying to autopopulate the proposed **kwargs from #6353 may add a lot of complexity for not very much benefit.

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Feature

### Purpose
- refs: #6361

### CODE REVIEW

**Comment by svenevs** [comment]
Hey just wanted to ping you really quick to let you know I'll be testing this tomorrow. Was out of town for holiday, will have time after work tomorrow :)

**Comment by tk0miya** [comment]
Thank you for comment. Happy holiday!

Note: I'd like to merge this in this weekend because I'll ship next minor release soon :-)

**Comment by svenevs** [comment]
> I'd like to merge this in this weekend because I'll ship next minor release soon :-)

Please do.  As IT WORKS PERFECTLY!!!  Thanks again for hearing me out and fixing it correctly (rather than my hacks...), I think this is a huge improvement :heart:

Sorry again for delayed testing.

**Comment by tk0miya** [comment]
@svenevs Thank you for checking! I'm merging this now!

**Comment by tk0miya** [comment]
@svenevs Thank you for checking! I'm merging this now!

**Pull request merged**
