### PR TITLE
domain: c: fix warning for intersphinx targets

### PR DESCRIPTION
**Pull request by utzig**
Referencing a symbol using <project:symbol>, which is a valid syntax that can be resolved by intersphinx, results in the C-domain parser printing a warning "Unparseable C cross-reference". The resolution still works correctly because it is postponed to intersphinx.

This commit adds a small check for intersphinx target format validity before printing the warning.

/cc @jakobandersen

### CODE REVIEW

**Comment by jakobandersen** [comment]
Hmm, do you have a small example project where this helps?

**Comment by utzig** [comment]
> Hmm, do you have a small example project where this helps?

I just built this little toy project which shows the issue. It has 3 projects, two of them, proj1 and proj2, export a function named "fn". In the "main" project I try to link to "fn". It will always link correctly to one of the "fn" functions, but there is no control over which. If I use "proj1:fn" or "proj2:fn" than it will link to the one I want, but will throw a "Unparseable C cross-reference: bla bla bla" warning on the way.

[inter_warn.tar.gz](https://github.com/sphinx-doc/sphinx/files/5542195/inter_warn.tar.gz)

**Comment by utzig** [comment]
@jakobandersen Have you had a chance to look into this?

**Comment by jakobandersen** [comment]
I find this way of making it work a bit iffy: when you write any kind of role in your input you are requesting a specific handler to be invoked, e.g., for ``:c:func:`` you request lookup in the documented C entities (with intersphinx as backup). But here you are explicitly requesting that the ordinary handler does not do any work.
I therefore suggest that intersphinx should provide a role, say ``inter`` which you can use for this purpose.
For example it could be made possible to write
```rst
:inter:`proj1,c:func,fn`
```
where the three comma-separated components are
1. the project specifier, as intersphinx understands it,
2. the original role, needed by intersphinx for matching,
3. the query symbol as if one would have given it to the original role from (2).

**Comment by tk0miya** [comment]
FYI: Now I just posted a draft version of the `:intersphinx:` role in https://github.com/sphinx-doc/sphinx/pull/9062.

**Pull request closed without merging**
