### PR TITLE
Introducing Sphinx Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Sphinx Guru](https://gurubase.io/g/sphinx) to Gurubase. Sphinx Guru uses the data from this repo and data from the [docs](https://www.sphinx-doc.org/en/master/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Sphinx Guru", which highlights that Sphinx now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Sphinx Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by jayaddison** [comment]
Although I more-or-less understand the motivation to build interest in the product, this doesn't appear to be a bugreport, feature request, or otherwise seem to match my mental model of bugtracker issues that could relate to the Sphinx codebase.  To some extent I could even consider it to be spammy, because it mentions an external product, and is one of perhaps 30+ similar templated issues on other repositories.

Even so, it does seem potentially valid as a discussion topic; others might be interested in it.  As a result, I'd be inclined to transfer this to a GitHub discussion, but will wait a little while to allow for potential feedback from other maintainers before doing that.

**Comment by jayaddison** [comment]
Although in theory I would like to demonstrate some goodwill by attempting to use Gurubase to ask questions about Sphinx, I feel disinclined to do that given some of the conversation threads I've read about it.  It seems unusual to me that a Kubernetes-based application formerley named `ddosify` is making efforts to promote an AI-based product from open source repositories.

This uncertainty and an associated slight sense of unease about what this apparent outreach is attempting to do also makes me think that this does not qualify for a discussion topic, since that could waste the time of potential contributors and developers.

**Comment by jayaddison** [comment]
Sorry @kursataktas, I don't feel comfortable with this contribution.  I would recommend reading the [Sphinx contributing guide](https://www.sphinx-doc.org/en/master/internals/contributing.html) and/or fixing one or two [existing open issues labeled as help-wanted](https://github.com/sphinx-doc/sphinx/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to gain credibility in the community before offering this style of change (to me it seems promotional for a particular product, without any apparent pre-existing evidence of the value of that product to the community).

**Comment by AA-Turner** [comment]
@kursataktas thank you for being up-front about your plans and opening this PR. Whilst we can't stop you using the documentation or etc, it isn't something I'm willing to have us promote. It would also be nice if you contributed to the projects you're using to promote your tool—simply by opening issues promoting your product it takes up many people's time for questionable benefit.

A

**Comment by kursataktas** [comment]
Thanks for your consideration. I wanted to update you that I disabled Sphinx Guru on Gurubase.io, as I felt you were uncomfortable with the idea.

**Comment by jayaddison** [comment]
You're welcome.  To my awareness, none of the maintainers here have expressed discomfort with Gurubase's usage of the public Sphinx documenation, but the separate question of whether we should include a hyperlinked badge to Gurubase from Sphinx's README file is something that we are declining to do at the moment.

**Pull request closed without merging**
