### PR TITLE
Add a label to search input for accessability purposes in search.html

### PR DESCRIPTION
**Pull request by thedrow**
Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature

### Purpose

Seems like I missed a spot when I wrote #6306.
The purpose is exactly the same though.

### Detail

I pointed the ARIA attribute to use the "Search" header as a description for the input.

### Relates
- #6306

### CODE REVIEW

**Comment by thedrow** [comment]
The build failure doesn't look like it has anything to do with me.

**Review by tk0miya — CHANGES_REQUESTED** [review]
Could you rebase this into 2.0 branch please? Then I'll merge this soon.

**Comment by thedrow** [comment]
Done.

**Comment by thedrow** [comment]
It's not very clear to me which branch should be the target of my pull requests.

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Merged. Thank you for your contribution.
I will try to explain our branch model in our docs soon.

**Pull request merged**
