### PR TITLE
#2268: Fix test code to support Pygments 2.0

### PR DESCRIPTION
**Pull request by shibukawa**
Subject: <short purpose of this pull request>

### Feature or Bugfix
- Bugfix

### Purpose
- Fix test code to support Pygments 2.0

### Relates
- #2268

### CODE REVIEW

**Comment by shibukawa** [comment]
I tested with Pygments 2.0, 2.1, 2.2.

**Comment by tk0miya** [comment]
Thank you for PR, but it's not good way. What I'd like to say in #2268 is not support to old pygments on our tests.
Even if this merged, it might be broken in case of pygments will change the structure of HTML.
To be robust, we should not inspect the results of pygments. This is testcases for Sphinx, not for pygments. So we should not be care of the highlighted codes in our tests.
What do you think?

**Comment by shibukawa** [comment]
Pygments' releases are not so fast:

* 2.2: Jan 22, 2017
* 2.1: Jan 17, 2016
* 2.0: Nov 9, 2014
* 1.9: Feb 3, 2013

So I think the risk of adding some Pygments specific test cases is not so high. Resulting of Pygments is just HTML. Matching with a regular expression is enough to support multiple version of Pygments.

**Comment by tk0miya** [comment]
Sure, it's not hurried.

Anyway supporting 2.0 is not important. So I close this.
Thanks,

**Pull request closed without merging**
