### PR TITLE
use consistent capitalisation for 'noqa' statements

### PR DESCRIPTION
**Pull request by danieleades**
all lowercase is the format used in the docs of both flake8 and ruff

right now there's a mixture of the two

### CODE REVIEW

**Comment by AA-Turner** [comment]
If we're going to standardise, please can we use NoQA. It's much more obvious that it means 'no quality assurance'.

A

**Comment by danieleades** [comment]
> If we're going to standardise, please can we use NoQA. It's much more obvious that it means 'no quality assurance'.
> 
> A

just to play devils advocate here, why does it matter what it stands for?

I think sphinx is the only repo i've seen that capitalises the statement this way. Surely community consistency is more important?

that said, it's not a hill i plan to die on, and I would prefer `NoQA` to a mixture of the two

**Comment by electric-coder** [comment]
> If we're going to standardise, please can we use NoQA.
> I think sphinx is the only repo i've seen that capitalises the statement this way.

Not even the Flake8 documentation is completely consistent as there are at least [two capitalized examples mixed with the prevalent lowercase][1].

However, since the majority of uses is lowercase I'd opine for trying to be consistent with the trend of the Flake8 repository.

A good [SO overview thread][2] for reference.

[1]: https://flake8.pycqa.org/en/latest/search.html?q=noqa&check_keywords=yes&area=default
[2]: https://stackoverflow.com/q/45346575

**Comment by picnixz** [comment]
Just my 2 cent before vanishing again: I personally prefer noqa because 1) that's what I see the most 2) I don't have to capitalise anything (so less keys to type).

**Comment by jayaddison** [comment]
I'm fairly ambivalent about it, but I do prefer `NoQA` in Sphinx, following the same reasoning that it's marginally more self-documenting.  I'm sympathetic to the fewer-shift-keypresses argument too though.

**Pull request merged**
