### PR TITLE
spell "GitHub" the right way

### PR DESCRIPTION
**Pull request by NickVolynkin**
Subject: <short purpose of this pull request>

### Feature or Bugfix
- Bugfix

### Purpose
- Fix spelling of "GitHub" in documentation.

### CODE REVIEW

**Comment by shimizukawa** [comment]
Thanks!

**Comment by NickVolynkin** [comment]
@shimizukawa you're welcome! :)

**Comment by NickVolynkin** [comment]
@shimizukawa was it right to open a MR to the `master` branch? If I fix some more typos, shouldn't I open a request to `stable`?

**Comment by shimizukawa** [comment]
stable is for minor version (1.5.x), master is for next major version (1.6).
IMO, typo can be placed in either (maybe stable is better).

FYI: #3586 we will release 1.6b1 soon ;)

**Pull request merged**
