### PR TITLE
Mention conventions in introduction.

### PR DESCRIPTION
**Pull request by jpic**
In the section about sections, this document presents conventions:

> this convention is used which you may follow

This commit makes it clear from the introduction that this document also
presents conventions which developers may use to redact documentation
productively.

### CODE REVIEW

**Comment by benoitbryon** [comment]
Here are my (summarized) humble thoughts about this pull-request:
- I understand the motivation
- I think the implementation doesn't solve the issue: I think the current document `doc/rest.rst` is not about conventions, and that it is good enough as a "reStructuredText primer"
- I'd like to have some third party conventions. I think it would help teams build collaborative documentations. Could be discussed in another thread.
- I'd love to have some rstlint or rst8 tool to validate documents against conventions. Could be discussed in another thread
- do you know style guides or rstlint? What about mentionning them instead of changing `reStructuredText primer` purpose?
- I know 2 projects about style guide and rstling (see below), but they are not mature and they are inactive at the moment... Your are welcome to wake them up!

Detailed thoughts below...

**I think the whole `doc/rest.rst` document is not really about conventions. Isn't its primary purpose about "concepts and syntax"?** Hence the title: "reStructuredText **primer**".
There is actually one convention about headings, but it is (almost?) the only one. It is a very small part of the document.

I think that, if the document's purpose is updated to include conventions, many parts of it should be updated to make a clear difference between what parts are conventions and what parts are just examples.
At the moment, parts are implicitely about syntax. Not about conventions by default, except the little part about headings, which is explicitely tagged as a convention. So **I think the current document is good enough and doesn't need to be changed.**

Notice that I'm in favour of conventions for reStructuredText style. **I do think that a third-party style guide would help teams build collaborative documentations. But I think this `doc/rest.rst` document is not the right place for that.**

Below is a story about style guide. I think it is kind of out the scope of the `doc/rest.rst` document, but I think it is related to the motivation of this pull-request...

As I said, I think a third-party style guide would be useful. I didn't find one, so I started a style-guide at http://documentation-style-guide-sphinx.readthedocs.org/en/latest/. It is getting old and unmaintained.
The reason why I don't maintain it is that it is not easy for writers to check the content against the convention. I mean, I think a style guide is not enough without tools to check it. Think of Python's PEP8 without tools like pylint or flake8: we usually'd better automatically run flake8 as part of the tests than manually check and discuss pep8.
**I think the best option would be some rstlint or rst8 tool.** I didn't find one, so I started [rst2rst](https://github.com/benoitbryon/rst2rst/commits/master) which I planned to use to automatically apply conventions on existing rst documents... but I failed at solving some programming challenges, and I haven't tried again for quite a long time.

Again, all of the thoughts above reflect my personal point of view. I am not a maintainer of Sphinx or docutils. So my understanding of `doc/rest.rst` may be wrong ;)

**Comment by jpic** [comment]
@benoitbryon this PR fixes an inaccuracy in the current documentation as-is.

It seems out of the scope of this PR to go through in-depth changes, wouldn't it be better to open a new ticket for that ?

**Comment by benoitbryon** [comment]
@jpic perhaps you misunderstood my point... As a summary, I see no issue with the current `doc/rest.rst`.

That said, I don't pretend to hold the truth on this topic. Here are my 2 cents. **Let's wait for a review from other Sphinx users and maintainers.**

> this PR fixes an inaccuracy in the current documentation as-is.

I think the current `doc/rest.rst` is accurate enough as a "reStructuredText primer".

If the introduction of `doc/rest.rst` mentioned "conventions" as you propose, then some users may refer to this document as a style guide. Is it a style guide? Is it about syntax or about style? Users may be confused.

The note about headings is the only one which deals with conventions. It is explicitely tagged as a convention. It is a little explicit exception. It doesn't make the document inacurrate.

> It seems out of the scope of this PR to go through in-depth changes, wouldn't it be better to open a new ticket for that ?

I think adding "conventions" in Sphinx's reStructuredText primer would imply much more in-depth changes than you propose at the moment in this pull-request.

First, in `doc/rest.rst`, we would have to distinguish examples from conventions. To me, the tone of the current document sounds good enough for an introduction about "concepts and syntax", whereas it currently doesn't sound like a style guide.

Also, if Sphinx documentation dealt with such conventions or style guide, wouldn't it be consistent that Sphinx documentation actually follows this style guide? As an example, at the moment, reStructuredText in `doc/rest.rst` doesn't follow the heading convention it mentions. And I see no RST style guide in [Sphinx Developer's Guide](http://sphinx-doc.org/devguide.html#coding-guide). So I wonder whether reStructuredText conventions are currently in the scope of Sphinx project itself.

**Comment by jpic** [comment]
This [section of this document](https://github.com/jpic/sphinx/blob/fix/rest_intro_conventions/doc/rest.rst#sections) presents conventions:

>  However, for the Python documentation, this convention is used which you may follow:

The issue that this PR addresses is that it is currently not mentioned in the introduction that this document also contains some conventions. I thought it was clear already.

Removing the part about conventions from this document or making a new convention documents or making better one etc, etc ... are out of the scope of this PR.

This PR addresses an actual problem, not a problem you created while trying to solve another problem.

**Comment by jpic** [comment]
> If the introduction of doc/rest.rst mentioned "conventions" as you propose, then some users may refer to this document as a style guide. Is it a style guide? Is it about syntax or about style? Users may be confused.

I don't think they can be confused by this introduction:

> This section is a brief introduction to reStructuredText (reST) concepts, syntax and conventions

Is is not a guide, reference, it's a **brief introduction**, I think the introduction makes it perfectly clear.

**Comment by RobRuana** [comment]
Just my two cents. The _purpose_ of the section is to introduce concepts and syntax. While the section does incidentally introduce some conventions, the introduction of conventions is not central to the section's intent.

**Comment by lehmannro** [comment]
I love 900-word discussions for single-word changes as much as everyone else, but I'm -1 on this as well.

I'd welcome a conventions or best practices document;  let's not spend any more time on bikeshedding this.

**Comment by jpic** [comment]
Me too I love them thanks for feedback !

**Comment by jpic** [comment]
Thank you Rob for the technical explanations, pretty efficient in itself too.

@lehmannro honnestly I didn't read the docs correctly, and now I'm thinking that a link to Python's Style Guide documentation would help other newbies from falling in the same trap in the beginning.

**Comment by jpic** [comment]
@benoitbryon 
do you want to make a PR for a best practice document ?

**Pull request closed without merging**
