### PR TITLE
Fix #6444: test: replace example.com by existing page

### LINKED ISSUE #6444: Root tests involving non-existing URLs fail (at my locale)
I get testing failures at my locale of this type :

```
sphinx$ make test TEST=tests/test_build_linkcheck.py::test_defaults
============================= test session starts ==============================
platform darwin -- Python 3.6.8, pytest-4.1.1, py-1.7.0, pluggy-0.8.1 -- /Users/johndoe/Downloads/sphinxvenv/bin/python3
cachedir: .pytest_cache
libraries: Sphinx-2.1.1+/3360f2461, docutils-0.14
base tempdir: /var/folders/np/4_9pppfs54xdv9m79m7rwx4w0000gn/T/pytest-of-johndoe/pytest-5
rootdir: /Users/johndoe/_gits/sphinx, inifile: setup.cfg
collected 1 item                                                               

tests/test_build_linkcheck.py::test_defaults FAILED                      [100%]

=================================== FAILURES ===================================
________________________________ test_defaults _________________________________

app = <SphinxTestApp buildername='linkcheck'>
status = <_io.StringIO object at 0x10f3d6ca8>
warning = <_io.StringIO object at 0x10f3d6798>

    @pytest.mark.sphinx('linkcheck', testroot='linkcheck', freshenv=True)
    def test_defaults(app, status, warning):
        app.builder.build_all()
    
        assert (app.outdir / 'output.txt').exists()
        content = (app.outdir / 'output.txt').text()
    
        print(content)
        # looking for '#top' and 'does-not-exist' not found should fail
        assert "Anchor 'top' not found" in content
        assert "Anchor 'does-not-exist' not found" in content
        # looking for non-existent URL should fail
        assert " Max retries exceeded with url: /doesnotexist" in content
        # images should fail
>       assert "Not Found for url: http://example.com/image.png" in content
E       assert 'Not Found for url: http://example.com/image.png' in "links.txt:13: [broken] https://localhost:7777/doesnotexist: HTTPSConnectionPool(host='localhost', port=7777): Max ret...nection.HTTPConnection object at 0x1115850b8>: Failed to establish a new connection: [Errno 65] No route to host',))\n"

tests/test_build_linkcheck.py:28: AssertionError
----------------------------- Captured stdout call -----------------------------
links.txt:13: [broken] https://localhost:7777/doesnotexist: HTTPSConnectionPool(host='localhost', port=7777): Max retries exceeded with url: /doesnotexist (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11145ccc0>: Failed to establish a new connection: [Errno 61] Connection refused',))
links.txt:11: [broken] http://example.com/#top: Anchor 'top' not found
links.txt:16: [broken] http://example.com/image2.png: 404 Client Error: Not Found for url: http://example.com/image2.png
links.txt:12: [broken] http://www.sphinx-doc.org/en/1.7/intro.html#does-not-exist: Anchor 'does-not-exist' not found
links.txt:9: [broken] http://example.com/#!bar: HTTPConnectionPool(host='example.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11145c278>: Failed to establish a new connection: [Errno 65] No route to host',))
links.txt:15: [broken] http://example.com/image.png: HTTPConnectionPool(host='example.com', port=80): Max retries exceeded with url: /image.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1115850b8>: Failed to establish a new connection: [Errno 65] No route to host',))

--------------------------- Captured stdout teardown ---------------------------
# testroot: root
# builder: linkcheck
# srcdir: /private/var/folders/np/4_9pppfs54xdv9m79m7rwx4w0000gn/T/pytest-of-johndoe/pytest-5/linkcheck
# outdir: /private/var/folders/np/4_9pppfs54xdv9m79m7rwx4w0000gn/T/pytest-of-johndoe/pytest-5/linkcheck/_build/linkcheck
# status: 
Running Sphinx v2.1.1+/3360f2461
building [linkcheck]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] links                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] links                                                 
(line   10) ok        http://example.com#!bar
(line   13) broken    https://localhost:7777/doesnotexist - HTTPSConnectionPool(host='localhost', port=7777): Max retries exceeded with url: /doesnotexist (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11145ccc0>: Failed to establish a new connection: [Errno 61] Connection refused',))
(line   11) broken    http://example.com/#top - Anchor 'top' not found
(line    3) ok        https://www.w3.org/TR/2006/REC-xml-names-20060816/#defaulting
(line   16) broken    http://example.com/image2.png - 404 Client Error: Not Found for url: http://example.com/image2.png
(line   12) broken    http://www.sphinx-doc.org/en/1.7/intro.html#does-not-exist - Anchor 'does-not-exist' not found
(line    9) broken    http://example.com/#!bar - HTTPConnectionPool(host='example.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11145c278>: Failed to establish a new connection: [Errno 65] No route to host',))
(line   15) broken    http://example.com/image.png - HTTPConnectionPool(host='example.com', port=80): Max retries exceeded with url: /image.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1115850b8>: Failed to establish a new connection: [Errno 65] No route to host',))


# warning: 
/private/var/folders/np/4_9pppfs54xdv9m79m7rwx4w0000gn/T/pytest-of-johndoe/pytest-5/linkcheck/links.txt:9: WARNING: Duplicate explicit target name: "example bar invalid".
/private/var/folders/np/4_9pppfs54xdv9m79m7rwx4w0000gn/T/pytest-of-johndoe/pytest-5/linkcheck/links.txt:9: WARNING: Duplicate explicit target name: "example bar invalid".
/private/var/folders/np/4_9pppfs54xdv9m79m7rwx4w0000gn/T/pytest-of-johndoe/pytest-5/linkcheck/links.txt:5: WARNING: Unknown target name: "http://www.sphinx-doc.org/en/1.4.8/tutorial.html#install-sphinx".

========================== 1 failed in 75.99 seconds ===========================
make: *** [Makefile:72: test] Error 1
```

Notice the long wait of 76 seconds.

Two other tests for same non-existing URLs reasons:

```
tests/test_build_latex.py::test_latex_images FAILED                      [ 50%]
...
tests/test_build_linkcheck.py::test_defaults FAILED                      [ 51%]
tests/test_build_linkcheck.py::test_anchors_ignored FAILED               [ 51%]
...
```

- Mac OS X 10.9.5
- Python 3.6.8
- Sphinx 2.1.0

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #6444 
- @jfbu could you check this on your environment?

### CODE REVIEW

**Comment by jfbu** [comment]
@tk0miya unfortunately I changed location and can not test my former environment until next Monday (or Sunday evening) i.e. June 10. And at my current location accessing example.com works fine.

Thanks a lot for your patience, I hope I have not wasted your time and unability to access example.com was really permanent problem at my other location.

**Comment by tk0miya** [comment]
Don't mind. I've never thought about example.com. So this is good oppotunity about investigate the domain to me. It's a piece of cake :-)

Please check this again after returning. And feel free to merge or reject this.

**Review by jfbu — APPROVED** [review]
LGTM ! It fixes the test behaviour at the locale where I previously had problems.

**Comment by jfbu** [comment]
Thanks for quick fix and sorry for delay in reporting. Should this get merged into upcoming 2.1.2?

**Comment by tk0miya** [comment]
Merged :-)
Please cherry-pick this into arbitrary branches if you need this.

**Pull request merged**
