### PR TITLE
Add link to Weblate's Sphinx docs in intl documentation

### PR DESCRIPTION
**Pull request by m-aciek**
Subject: Reference Weblate in intl documentation

### Feature or Bugfix

- Feature

### Purpose
- link to docs for setting up Sphinx i18n in Weblate

### Relates
- https://docs.weblate.org/en/latest/devel/sphinx.html

### CODE REVIEW

**Comment by m-aciek** [comment]
Failing checks are unrelated to the PR changes.

**Comment by jfbu** [comment]
> Failing checks are unrelated to the PR changes.

Hi, master branch has resolved the failing checks triggered by pip 23.1, can you update your branch?

**Comment by m-aciek** [comment]
> Hi, master branch has resolved the failing checks triggered by pip 23.1, can you update your branch?

Thank you, it is done now.

**Review by jfbu — APPROVED** [review]
LGTM, thanks

**Pull request merged**
