### PR TITLE
Exclude env/* from flake8

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by lehmannro** [comment]
Where does that directory come from?

**Comment by scop** [comment]
I suspect it is meant to be a dir for a virtualenv. It's already included in `Makefile`'s `DONT_CHECK`.

**Comment by tk0miya** [comment]
I don't know that. I don't use the `env` directory. so I'd prefer to remove it from `DONT_CHECK`.

Note: it was introduced at f82a4a4eab1b45ccf99a0b8c928553d4a59ab80d.

**Comment by lehmannro** [comment]
:+1: to Takeshi's proposal:  Let's remove env/ from everywhere.  If people have their preferred name for virtualenvs they can put it in their personal configurations.  Sphinx puts these into .tox, which is way more reasonable anyways.

**Comment by tk0miya** [comment]
As far as I know, no sphinx developer does not use the directory. At least, I and shimizukawa, lehmanro are.
So I removed `env` from DONT_CHECK.

**Pull request closed without merging**
