### PR TITLE
Make refdoc attribute optional for pending_xref nodes

### PR DESCRIPTION
**Pull request by pfultz2**
The refdoc attribute is optional when resolving citation references, but this makes it optional when resolving any reference. It seems it was that way before [here](https://github.com/sphinx-doc/sphinx/commit/c49c9b288be5878eda0388241396487cf34fc18d), but then when it was refactored [here](https://github.com/sphinx-doc/sphinx/commit/430be0496ad68af31c052cf2367c0c8197a19cd6) it was no longer optional.

### CODE REVIEW

**Comment by pfultz2** [comment]
Can anyone take a look at this?

**Comment by pfultz2** [comment]
@birkenfeld You seemed to have wrote the original commit for this. Any comments?

**Comment by tk0miya** [comment]
What does this PR improve or fix? Is there a specific issue?

Anyway it looks good to me.

**Comment by pfultz2** [comment]
It allows adding the pending_xref node without needing `refdoc`, since it can be resolved with `resolve_references`, already. 

This is useful for me because I am using a fork of recommonmark that adds the reference nodes as `pending_xref` so the references can be resolved using sphinx. However, when adding the node, I don't have access to the docname so by leaving `refdoc` out, sphinx can fill it in for me, since it already has that information.

In addition, it looks like from previous commits it was intended for `refdoc` to be optional, anyways. So this commit will keep it that way.

**Comment by tk0miya** [comment]
Finally, I decide to merge this.
Thank you for suggestion!

**Pull request merged**
