### PR TITLE
Do not emit type arguments twice

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes gh-7567

### Feature or Bugfix

- Bugfix

### CODE REVIEW

**Comment by eric-wieser** [comment]
Ping @tk0miya, CI passes now - sorry for not letting you know I was working on the same thing as you before you spent the time!

**Comment by tk0miya** [comment]
Don't mind. I feel your implementation is much better than mine :-)

**Comment by tk0miya** [comment]
oh, I did not noticed the target branch is 3.0.x.

**Comment by eric-wieser** [comment]
Whoops, sorry about that.

**Comment by tk0miya** [comment]
don't mind! I think this is not a critical, but stable.

**Comment by eric-wieser** [comment]
I assume this will end up in 3.1.0 as well?

**Pull request merged**
