### PR TITLE
[builder] type `Builder` core methods with `@final` and improve docs

### PR DESCRIPTION
**Pull request by chrisjsewell**
The `Builder` essentially covers two phases:

1. The read phase, which should generally be builder agnostic, so that multiple builders can utilize the resultant cached doctree's
2. The write phase, which is more specific to the builder's output format

This PR annotates the `Builder`'s core "read phase" methods, with [`final`](https://docs.python.org/3/library/typing.html#typing.final), to make it clearer that they should really not be altered by any specific builder.

The one exception here is the `gettext` builder, which overrides the `build` method, but this is really a special case (and it does still call `super`)

### CODE REVIEW

**Comment by picnixz** [comment]
I'm not really in favor of this. Since you can have custom builders for custom formats, they should be able to also override those core methods IMO (that are public).

**Comment by chrisjsewell** [comment]
> they should be able to also override those core methods

If they override these methods, then sphinx will not work; this is critical logic.

The builder should ideally be split into two classes; one private, one public, but such is life

**Comment by picnixz** [comment]
> If they override these methods, then sphinx will not work; this is critical logic.

Oh my bad! actually the docs say (I extracted the list):

> These methods are predefined and will be called from the application:
> 
> get_relative_uri, build_all, build_specific, build_update, build

Maybe you could stress that they should *not* be overridden (because they are marked as final) or at least complete the list of methods that are final ? (`read` is not in the list).

**Review by picnixz — APPROVED** [review]
If you want, you could also expand the docs but otherwise I'm ok! (sorry for the misunderstanding).

**Comment by chrisjsewell** [comment]
> If you want, you could also expand the docs but otherwise I'm ok! 

Done, and added a nice new UML graph, which I think makes things so much clearer 😁

https://sphinx--12436.org.readthedocs.build/en/12436/extdev/builderapi.html

**Pull request merged**
