### PR TITLE
#3620: Defer searchindex.js rather than loading it via ajax

### PR DESCRIPTION
**Pull request by ghost**
Subject: Defer searchindex.js rather than loading it via ajax

### Feature or Bugfix
- Bugfix

### Purpose
- Content security policy is insecure when allowing inline scripts. So we need to remove them. However, `searchindex.js` is loaded via AJAX for reasons outlined in [#322](https://github.com/sphinx-doc/sphinx/issues/322). However, the `defer` attribute equally accomplishes this task. Further, the script should be cached just fine even when using this method. Also, I'm not entirely sure what the purpose of `searchindexloader` is, but I was able to test this locally in Chromium and Firefox without issues.

### Relates
- #3620

### CODE REVIEW

**Comment by jumarko** [comment]
I quickly looked at it and it seems there is at least [one other problematic script in search.html](https://github.com/sphinx-doc/sphinx/pull/6091/files#diff-453969dcf47b1378674f807c54aca249R23).

**Comment by ghost** [comment]
@jumarko Thanks. However, that shouldn't be a problem since it gets rendered into a `<noscript>` block in the end.

**Review by tk0miya — CHANGES_REQUESTED** [review]
LGTM. But it would be better to merge this to `2.0` branch. Could you change the target branch of this please?
Note: It seems Opera does not support `defer` keyword. So we have to check Opera works fine with this.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by ghost** [comment]
According to [caniuse](https://caniuse.com/script-defer) Opera supports it. Maybe the MDN page is outdated? Someone with an Opera browser can test this [script](https://raw.githubusercontent.com/phiggins42/has.js/master/detect/script.js#script-defer).

**Review by tk0miya — APPROVED** [review]

**Comment by tk0miya** [comment]
Thank you for quick work. LGTM!

>According to [caniuse](https://caniuse.com/script-defer) Opera supports it.

Sounds good :-)

**Comment by tk0miya** [comment]
@TimKam do you have any comment for this?

**Comment by TimKam** [comment]
I don't see any issue. According to the [entry at caniuse.com](https://caniuse.com/#feat=script-defer) ``defer`` works fine in Opera, but there might be issues with Opera Mini. Let's test this before we merge.

**Review by TimKam — COMMENTED** [review]
I don't see any issues, but think we make sure there are no browser compatibility issues. According to the [entry at caniuse.com](https://caniuse.com/#feat=script-defer) `defer` works fine in Opera, but there might be issues with Opera Mini. Let's test this before we merge.

**Comment by TimKam** [comment]
@remyabel @tk0miya I just tested in the latest versions of Opera and Opera mini and it looks good :-)

**Comment by tk0miya** [comment]
@TimKam thank you for confirming!

@remyabel Thank you for your contribution :-)

**Pull request merged**
