### PR TITLE
Fix AssertionError is raised for custom citation_reference node (refs: #6147)

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- AssertionError is raised when custom ``citation_reference`` node
  having classes attribute refers missing citation (refs: #6147)

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@tk0miya yes perfect ta, definitely makes more sense to be an inline

**Comment by tk0miya** [comment]
@chrisckchang Thank you for quick check!

**Comment by chrisjsewell** [comment]
> @chrisckchang Thank you for quick check!

Not sure who chrisckchang is lol, but no problem

**Comment by tk0miya** [comment]
oh, sorry. Thank you @chrisckchang !

**Comment by tk0miya** [comment]
oh, sorry. Thank you @chrisjsewell !

**Pull request merged**
