### PR TITLE
Don't install flake8 plugin globally

### PR DESCRIPTION
**Pull request by stephenfin**
Resolve issue #4492.

### CODE REVIEW

**Comment by tk0miya** [comment]
Could you check `utils/checks.py` is installed or not? If installed, we have to remove it from packages definition.

**Comment by stephenfin** [comment]
> Could you check utils/checks.py is installed or not? If installed, we have to remove it from packages definition.

It is not, but we don't include the `util` directory in `MANIFEST.in` anyway so I doubt it matters

**Comment by tk0miya** [comment]
It seems utils package is installed.
```
$ virtualenv test
$ ./test/bin/pip install git+https://github.com/sphinx-doc/sphinx
$ ./test/bin/python
Python 3.6.4 (default, Dec 20 2017, 01:09:24)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import utils.checks
>>> utils.checks
<module 'utils.checks' from '/Users/tkomiya/work/issuesgraph/test/lib/python3.6/site-packages/utils/checks.py'>
```

Anyway, this is not related with this PR.

**Comment by tk0miya** [comment]
Merged! thank you always

**Pull request merged**
