### PR TITLE
Fixed a spanish word translation

### PR DESCRIPTION
**Pull request by selobu**
msgid "continues on next page"

must be translated as

msgstr "continúe en la próxima página"

Subject: <short purpose of this pull request>

### Feature or Bugfix
- Translation

### Purpose
- Fixed spanish word translation

### Detail
- changed continué into continúe

### TODO
- [sphinx.mo](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/locale/es/LC_MESSAGES/sphinx.mo) needs to be updated.

### CODE REVIEW

**Comment by AA-Turner** [comment]
We use Transifex (https://www.transifex.com/sphinx-doc/sphinx-1); Spanish is at https://www.transifex.com/sphinx-doc/sphinx-1/language/es_ES (you may need to log in).

A

**Comment by selobu** [comment]
I logged in and then I try to used the second link but it returns 404. https://www.transifex.com/sphinx-doc/sphinx-1/language/es_ES 

So I searched in https://www.transifex.com/sphinx-doc/sphinx-1/translate/#navigation-resources-dropdown and I posted the correct translation as a suggestion. 

The translation must be changed because "continué" can be interpreted as If I did someting and not as an instruction.

**Comment by shimizukawa** [comment]
@AA-Turner  I just sent you an invitation. Please accept the invitation.

**Comment by AA-Turner** [comment]
@shimizukawa Thank you!

**Comment by AA-Turner** [comment]
@selobu I have updated the translation per your suggestion; https://www.transifex.com/sphinx-doc/sphinx-1/translate/#es/sphinx-pot/168708353.

If you would like to contribute more translations (or have any others updated), please do; it is really helpful!

A

**Pull request closed without merging**
