### PR TITLE
Fix #3351: intersphinx does not refers context

### LINKED ISSUE #3351: intersphinx links must be fully qualified
I use intersphinx to link to other bits of documentation.

I would like to be able to write `:class:firedrake:.Function` and have this resolved, in the same way it would be by Sphinx in the "foreign" documentation, into (in this case) `firedrake.function.Function`.  Currently intersphinx only links correctly if I put in the fully qualified object name.  This can be rather tiresome.

If I understand the code to some level, I think one needs to update `missing_reference` in intersphinx to handle this case in the same way that (say) `PythonDomain.find_obj` works.  However, I can't just use that code directly, since the currently active domain inside `env` knows nothing about the intersphinx inventorys.

A hacky "fix" for this might be something like:

```patch
diff -u /data/lmitche1/src/firedrake/lib/python2.7/site-packages/sphinx/ext/intersphinx.py.bak /data/lmitche1/src/firedrake/lib/python2.7/site-packages/sphinx/ext/intersphinx.py
--- /data/lmitche1/src/firedrake/lib/python2.7/site-packages/sphinx/ext/intersphinx.py.bak	2017-01-18 13:02:28.528827706 +0000
+++ /data/lmitche1/src/firedrake/lib/python2.7/site-packages/sphinx/ext/intersphinx.py	2017-01-18 12:56:12.877045837 +0000
@@ -326,9 +326,22 @@
             in_set = setname
             to_try.append((env.intersphinx_named_inventory[setname], newtarget))
     for inventory, target in to_try:
+        fuzzy = target.startswith(".")
         for objtype in objtypes:
-            if objtype not in inventory or target not in inventory[objtype]:
+            if objtype not in inventory:
                 continue
+            if target not in inventory[objtype] and not fuzzy:
+                continue
+            if fuzzy:
+                matches = [key for key in inventory[objtype] if key.endswith(target)]
+                if len(matches) > 1:
+                    env.warn_node(
+                        'more than one target found for cross-reference '
+                        '%r: %s' % (target, ', '.join(match for match in matches)),
+                        node)
+                if not matches:
+                    continue
+                target = matches[0]
             proj, version, uri, dispname = inventory[objtype][target]
             if '://' not in uri and node.get('refdoc'):
                 # get correct path in case of subdirectories
@@ -343,8 +356,11 @@
                 # use whatever title was given, but strip prefix
                 title = contnode.astext()
                 if in_set and title.startswith(in_set+':'):
-                    newnode.append(contnode.__class__(title[len(in_set)+1:],
-                                                      title[len(in_set)+1:]))
+                    if fuzzy:
+                        title = target
+                    else:
+                        title = title[len(in_set)+1:]
+                    newnode.append(contnode.__class__(title, title))
                 else:
                     newnode.append(contnode)
             else:

Diff finished.  Wed Jan 18 13:02:49 2017
```

But I'm not really very happy, and this seems unlikely to work with domains other that Python.  Thoughts, suggestions?

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #3351 

I added a new interface `Domain.get_full_qualified_name()` to get the full qualified name from the node.
It allows to refer a target using context (e.g. `py:module`).

- [x] Implement `get_full_qualified_name()` for other domains => #3630
- [x] Add doc about `get_full_qualified_name()`
- [x] Add more test cases

### CODE REVIEW

**Comment by bitprophet** [comment]
A couple random suggestions:

- Given the implemented behavior is backwards compatible (the fully-qualified name is only added to the `to_try` list if it's non-empty), I'd argue there is no need to implement it for all other domains before merging; that could be left for future PRs from interested users.
- I wonder if it's possible to simply reuse the machinery that implements the 'find it anywhere' behavior from `py:obj`, i.e. the code that knows `.ClassName` can refer to anything called `ClassName` within the current project, regardless of module scope.
    - This is partly because I'm not 100% sure the current code will work right; when I apply it to an intersphinx reference, it would attempt to look up the name _as if it was defined in the referencing module and class_ instead of the module and class it truly lives in.
    - So for example, referencing `remote.project.FooClass` inside a docstring from `local.project.BarClass` would try to add the name `local.project.BarClass.FooClass` to the lookup list...which I don't think would exist in the inventory for `remote`?

**Comment by tk0miya** [comment]
Now I rebased to master HEAD. Unfortunately, I don't have enough time to improve this to all of domains. so I'll do that in future version (@bitprophet Thank you for advice, I've overlooked your comment longer...).

@shimizukawa could you review this please? This adds a new interface to Domain class. So it should be reviewed before merging.

**Comment by tk0miya** [comment]
>So for example, referencing remote.project.FooClass inside a docstring from local.project.BarClass would try to add the name local.project.BarClass.FooClass to the lookup list...which I don't think would exist in the inventory for remote?

@bitprophet Did you mean like following case?
```
.. py:module:: local.project

.. py:class:: BarClass

   This class refers :py:class:`remote.project.FooClass`.
```

In this case, intersphinx tries to search both `FooClass` and `local.project.BarClass.remote.project.FooClass` from remote inventories (after this PR).

Surely, the next case searches both `FooClass` and `local.project.BarClass.FooClass`. I think this is correct behavior of intersphinx.
```
.. py:module:: local.project

.. py:class:: BarClass

   This class refers :py:class:`FooClass`.
```

**Comment by bitprophet** [comment]
> In this case, intersphinx tries to search both FooClass and local.project.BarClass.remote.project.FooClass from remote inventories (after this PR).

If that's the case then I misunderstood something, I thought it was _only_ going to search for the fully-qualified `local.project.BarClass.remote.project.FooClass`. So, I'll wait & see if this gets merged & try it out. Thanks :)

**Comment by tk0miya** [comment]
Ah, sorry. my explanation was wrong.
Both `remote.project.FooClass` and `local.project.BarClass.remote.project.FooClass` are correct.
With this PR, intersphinx tries to search using both original keyword and full qualified one.

**Review by shimizukawa — APPROVED** [review]
LGTM!

I haven't seen generated doc, but new API should be described by autodoc, right?

**Comment by tk0miya** [comment]
Thank you for reviewing.
I will merge this after discussion in #3630 is finished.

**Pull request merged**
