### PR TITLE
Complete sphinx simplified Chinese translation

### PR DESCRIPTION
**Pull request by dpy013**
#6724 Complete sphinx simplified Chinese translation

### CODE REVIEW

**Comment by tk0miya** [comment]
Thank you for your great work. But, unfortunately, we've manage all of translations on transifex.com. 
Could you join our team on transifex.com and translate these sentences again?
https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#contributing-to-sphinx-reference-translation

Thanks,

**Comment by dpy013** [comment]
> Thank you for your great work. But, unfortunately, we've manage all of translations on transifex.com.
> Could you join our team on transifex.com and translate these sentences again?
> https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#contributing-to-sphinx-reference-translation
> 
> Thanks,

Hi I really want to use transifex.com to maintain the translation, but since I am a blind person, it is not good for transifex.com to support screen readers, so I used GitHub to submit translations. Thank you.

**Comment by tk0miya** [comment]
I see. I'll try to upload your translations later!

**Comment by shimizukawa** [comment]
I tried to find out if I could upload the translation to Transifex while keeping your name, and eventually I uploaded it with my name....

Anyway, all your translations have been applied! Thanks!

**Comment by shimizukawa** [comment]
Translations are already included, so translations will be applied in the next release without merging this PR. However, I think it's better to merge as a record of contributions.
@tk0miya If you don't have any trouble with the release procedure by merging this, I would like to merge.

**Comment by tk0miya** [comment]
Okay, merging now.

**Comment by tk0miya** [comment]
Thank you for your great contribution, @dingpengyu!

**Pull request merged**
