### PR TITLE
Add exact phrase searching in HTML

### PR DESCRIPTION
**Pull request by mherbold**
New exact phrase searching feature (for HTML)

### CODE REVIEW

**Comment by tk0miya** [comment]
@shibukawa could you review this please?

**Comment by AA-Turner** [comment]
@marxin do you think this would be useful?

A

**Comment by marxin** [comment]
@mherbold Can you please explain the motivation for the change (please share some https://www.sphinx-doc.org/ search example). Do you have a checkbox in a theme where you enable/disable the mode?

**Comment by AA-Turner** [comment]
We can't update this PR as it is made from an organisation account. Re-opened as #12552.

A

**Pull request closed without merging**
