### PR TITLE
add text_file_suffix conf support for text builder.

### PR DESCRIPTION
**Pull request by qytz**
need to build `.rst` files for rendering in gitlab.

### CODE REVIEW

**Comment by tk0miya** [comment]
A bit strange for me. the text builder does not generate `.rst` files.

**Comment by qytz** [comment]
refer form http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.text.TextBuilder

> This builder produces a text file for each reST file – this is almost the same as the reST source, but with much of the markup stripped for better readability.

I use autodoc to generate my doc files, so I need the result `.rst` or `.md`files.

**Comment by tk0miya** [comment]
Yes, it is similar to reST, but not same as reST.

For example, code-blocks are converted to simple text block.
So this code-block will be recognized as description-list if you reuse text output to reST.

```
.. code-block:: python

   def hello(name):
       print "Hello, %s" % name

   def say(name):
       print "My name is %s" % name

   def main():
       hello("Sphinx")
       say("tkomiya")
```

I think this way is not good for autodoc.

**Comment by qytz** [comment]
ok, then i think we need a builder to generate `.rst` files.

**Comment by tk0miya** [comment]
Thanks.

Note: The reST builder is registered at PyPI: https://pypi.python.org/pypi/sphinxcontrib-restbuilder
(But I don't know it works fine or not)

**Comment by qytz** [comment]
I use Python3 and install it with pip, with some modify, it works :)

**Comment by tk0miya** [comment]
Good to know!

**Pull request closed without merging**
