### PR TITLE
Differentiate the colour of previously-visited hyperlinks

### LINKED ISSUE #1708: make visited links default color different
Browsers differ visited links with unvisited ones. And some users (like me) make use of this: it makes it easier to find frequently visited links, especially when there is a list and I often visit a small fraction of links in the list. It also tells me whether the content behind a link is fresh to me, or I've already read, as I don't remember the exact titles.

Making visited links default color different from unvisited ones, so when the doc authors don't find a reason to make them the same, they will be different, as the browsers always do.

### PR DESCRIPTION
**Pull request by kaycebasques**
Subject: Make visited links default color different

### Feature or Bugfix

- Feature

### Purpose

- Make it easier to tell which pages you have visited

### Detail

- Updates the visited link color in all the themes to the [HTML5 reference color](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) per [suggestion](https://github.com/sphinx-doc/sphinx/issues/1708#issuecomment-609018269) from @septatrix 
- Fix #1708 

### Relates

- https://github.com/sphinx-doc/sphinx/issues/1708
- https://github.com/sphinx-doc/sphinx/pull/9027

### Screenshots

All are ordered before and then after.

#### agogo

agogo-before

agogo-after

#### basic

basic-before

basic-after

#### bizstyle

bizstyle-before

bizstyle-after

#### classic

classic-before

classic-after

#### default

default-before

default-after

#### epub

epub-before

epub-after

#### haiku

haiku-before

haiku-after

#### nature

nature-before

nature-after

#### nonav

nonav-before

nonav-after

#### pyramid

pyramid-before

pyramid-after

#### scrolls

scrolls-before

scrolls-after

#### sphinxdoc

sphinxdoc-before

sphinxdoc-after

#### traditional

traditional-before

traditional-after

### CODE REVIEW

**Comment by kaycebasques** [comment]
I can't tell if that `CI / Docutils HEAD (pull_request)` is related to my changes or is just flaky: https://github.com/sphinx-doc/sphinx/actions/runs/4855074164/jobs/8653200660?pr=11390

**Comment by webknjaz** [comment]
@kaycebasques that looks flaky. Try retriggering the CI by closing and reopening this PR...

**Comment by kaycebasques** [comment]
I'll try one more time but it seems like there may actually be something failing here...

**Comment by AA-Turner** [comment]
Thanks @kaycebasques!

**Pull request merged**
