### PR TITLE
Fix quotes in docstring in ext.napoleon

### PR DESCRIPTION
**Pull request by LouisJustinTALLOT**
Subject: Fix quotes in docstring in ext.napoleon

### Feature or Bugfix

- Bugfix

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Hi @LouisJustinTALLOT , thanks for your pull request! However I think you created your branch from `master`, and you are proposing a pull request to `4.x`, therefore there are some extra commits. 

Would you please change the target branch to `master`? Or, if you think this should be included in the next minor version, rebase your changes on top of `4.x`.

**Comment by LouisJustinTALLOT** [comment]
Hello @astrojuanlu, I think I managed to rebase the branch. Tell me if it is okay, else I re-do it !

**Comment by astrojuanlu** [comment]
@LouisJustinTALLOT It's better now, but notice that you are still adding two extra commits: 1f75b2b and 768af26. This pull request should only contain d4029b3 to be merged in `4.x`

**Comment by astrojuanlu** [comment]
Thanks for your patience and for this contribution @LouisJustinTALLOT !

**Pull request closed without merging**
