### PR TITLE
Fix #1480: LaTeX: Support math in section titles

### LINKED ISSUE #1480: latex math output is broken for inline math in chapters.
We are trying to upgrade sphinx shipped in sage (sagemath.org) to the latest 1.2 release. However producing pdf documents is broken with this release. We get the following error:

```
Chapter 1.

Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 170.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `subscript' on input line 170.


! LATEX ERROR: BAD MATH ENVIRONMENT DELIMITER.

SEE THE LATEX MANUAL OR LATEX COMPANION FOR EXPLANATION.
Type  H <return>  for immediate help.
 ...                                              

l.170 ... index subgroups of \({\rm SL}_2(\ZZ)\))}

? 
! Emergency stop.
 ...                                              

l.170 ... index subgroups of \({\rm SL}_2(\ZZ)\))}

!  ==> Fatal error occurred, no output PDF file produced!
```

The issue is caused by the commit solving issue #929 were the delimiter for inline math was changed from "$...$" to "(...)", the later form being actually tex syntax rather then latex. The breakage occurs because the math is in a chapter header

```
\chapter{Arithmetic subgroups (finite index subgroups of \({\rm SL}_2(\ZZ)\))}
```

where the "(..)" construct is deemed fragile. Reading issue #929 I have trouble understanding the reason for changing the delimiter for math.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1480
- Originally reported by: François Bissey
- Originally created at: 2014-06-04T04:43:09.709

### PR DESCRIPTION
**Pull request by xuhdev**
Fix #1480

### CODE REVIEW

**Comment by tk0miya** [comment]
Before merging this, I want to reproduce the bug with current release (1.3.3).
I tried the formula `:math:E = m c^2`, but it does not raise any errors.
so I think this example is not good to testing.

Please let me know any error cases.

**Comment by xuhdev** [comment]
@tk0miya Strangely, this testing case can produce an error for me if the PR is not incorporated. I've pasted my error message [here](https://gist.githubusercontent.com/xuhdev/abb349c97307439bda4b/raw/e912d4083929966b96ba573223566e0d6996137a/gistfile1.txt). The error vanishes after making the changes proposed in this PR. Could you double check again?

**Comment by tk0miya** [comment]
I feel too. But, in my environment, MacTex 2015 does not raise any errors.

```
Running LaTeX files through pdflatex...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C _build/latex all-pdf
pdflatex  'test.tex'
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
...
Output written on test.pdf (5 pages, 78598 bytes).
Transcript written on test.log.
pdflatex finished; the PDF files are in _build/latex.
```

I'll try it again on other platform. 
I think your changes are alright. so I'll merge it even if I can not reproduce till this weekend.

Please wait a moment. Thanks.

**Comment by shirou** [comment]
On my Mac Yosemite + Sphinx-1.3.3 + TexLive 2015 environment, this error happens.

```
! LATEX ERROR: BAD MATH ENVIRONMENT DELIMITER.

SEE THE LATEX MANUAL OR LATEX COMPANION FOR EXPLANATION.
Type  H <return>  for immediate help.
 ...                                              

l.136 \chapter{Test math extensions \(E = m c^2\)}

?
```

And I confirmed this PR solves.

**Comment by tk0miya** [comment]
@shirou Sounds good! Thank you for double check!

**Comment by shimizukawa** [comment]
In my environment (Ubuntu-12.04 + Sphinx-1.3.3 + TeXLive2014) can reproduce the issue. Now patched sphinx by this PR will resolve the issue.

**Comment by tk0miya** [comment]
Merged. Thanks always!

**Pull request merged**
