### PR TITLE
add --pdb support to setuptools command

### PR DESCRIPTION
**Pull request by mindw**
Same implementation as in the command line tool.

### CODE REVIEW

**Comment by tk0miya** [comment]
It seems PR has broken.
Could you pick your commits and resend new PR please?

**Comment by mindw** [comment]
better?

**Comment by mindw** [comment]
rebased.

**Comment by tk0miya** [comment]
Thanks, I'll take a look later!

**Comment by tk0miya** [comment]
LGTM

**Comment by tk0miya** [comment]
Merged.
Thank you for contribution!

**Pull request merged**
