### PR TITLE
[tests] Attempt to uncover and resolve test flakiness in 'test_linkcheck_exclude_documents'.

### PR DESCRIPTION
**Pull request by jayaddison**
### Feature or Bugfix
- Bugfix (test suite)

### Purpose
- As reported in #12188, the `test_linkcheck_exclude_documents` test case failed recently.  It appears that it makes an assumption about the order that linkchecking results will be received in -- linkchecking [uses threading](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/linkcheck.py#L252-L258), so we cannot rely on the ordering of those results.

### Detail
- Initially this pull request should update the application code to make the occurrence of the problem more likely -- ideally 50% occurrence rate in our workflow jobs -- so that the problem becomes easier to confirm.
- After we have found a reliable way to replicate and observe the problem, we can apply a fix.  Continuous integration workflows should begin passing reliably again.
- Finally, the temporary changes to the application code should be reverted.

### Relates
- #12188.

### CODE REVIEW

**Comment by jayaddison** [comment]
> Initially this pull request should update the application code to make the occurrence of the problem more likely -- ideally 50% occurrence rate in our workflow jobs -- so that the problem becomes easier to confirm.

Unit test results:

# Passes (expected to be ~50%):

  * [Python 3.9 (Docutils 0.18)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099255?pr=12189)
  * [Python 3.10 (Docutils 0.18)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099541?pr=12189)
  * [Python 3.11 (Docutils 0.18)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099677?pr=12189)
  * [Python 3.12 (Docutils 0.18)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099751?pr=12189)
  * [Python 3.12 (Docutils 0.20)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099789?pr=12189)
  * [Windows](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099322?pr=12189)

# Failures (expected to be ~50%):

  * [Python 3.9 (Docutils 0.20)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099498?pr=12189) - (one [failure](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099498?pr=12189#step:9:2300) - `test_linkcheck_exclude_documents`).
  * [Python 3.10 (Docutils 0.20)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099639?pr=12189) - (one [failure](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099639?pr=12189#step:9:2298) - `test_linkcheck_exclude_documents`).
  * [Python 3.11 (Docutils 0.20)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099713?pr=12189) - (one [failure](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099713?pr=12189#step:9:2299) - `test_linkcheck_exclude_documents`).
  * [Python 3.12 (Docutils 0.19)](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099848?pr=12189) - (one [failure](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099848?pr=12189#step:9:2306) - `test_linkcheck_exclude_documents`).
  * [Docutils HEAD](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099430?pr=12189) - (one [failure](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099430?pr=12189#step:8:2281) - `test_linkcheck_exclude_documents`).
  * [LaTeX](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099384?pr=12189) - (one [failure](https://github.com/sphinx-doc/sphinx/actions/runs/8403518388/job/23014099384?pr=12189#step:7:2300) - `test_linkcheck_exclude_documents`).

**Comment by jayaddison** [comment]
> After we have found a reliable way to replicate and observe the problem, we can apply a fix. Continuous integration workflows should begin passing reliably again.

This appears true for the test results of 6a3d3d9c61033e88a843b00f662866b0b52b225c (essentially: confirming that `a in results` and then `b in results`, instead of confirming `results == [a, b]`).

**Review by picnixz — APPROVED** [review]

**Comment by picnixz** [comment]
Thank you!

**Comment by jayaddison** [comment]
Thanks!

**Pull request merged**
