### PR TITLE
Update packaging script (refs: #3256)

### PR DESCRIPTION
**Pull request by tk0miya**
refs: #3256.

@shimizukawa Could you review this please?

### CODE REVIEW

**Review by shimizukawa — APPROVED** [review]
LGTM for the update

**Comment by shimizukawa** [comment]
Additionally, perhaps we should have compiled grammar file (like `Grammar-py2-sphinx1.5.pickle`) in data directory by using `package_data` keyword for setup.py. 
https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

If we did, we have to use resource management API to get the data.
https://setuptools.readthedocs.io/en/latest/setuptools.html#accessing-data-files-at-runtime

**Comment by wallrj** [comment]
Additionally I noticed there are a few files which aren't included in the sdist.

```
# Fetch and checkout this PR branch
$ git fetch origin refs/pull/3262/head
$ git checkout FETCH_HEAD

# Run all the tests (NB lots of test failures)
# Generates a bunch of .pyc files in the working dir.
$ tox

# Tars up the code, but also includes a bunch of PYCs
$ python setup.py sdist --dist-dir /tmp

# Remove everything excluding the `.git` dir
# Git now reports *everything* deleted.
$ rm -rf *
$ git status

# Restore the files from the sdist.
$ tar --strip-components 1 --extract --file /tmp/Sphinx-1.5.2.dev20161219.tar.gz

# Git now *still* reports files missing.
# I'd say these files should probably be included in the sdist too.
$ git status
HEAD detached at FETCH_HEAD
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    CHANGES.old
	deleted:    CONTRIBUTING.rst
	modified:   setup.cfg
	deleted:    sphinx/locale/.tx/config
	deleted:    sphinx/locale/sphinx.pot
	deleted:    sphinx/pycode/pgen2/parse.c
	deleted:    sphinx/pycode/pgen2/parse.pyx
	deleted:    sphinx/search/test
	deleted:    test-reqs.txt
	deleted:    tox.ini
```

I'm not quite sure which of the `make` targets are called during a release.
It'd be nice to have brief summary of the release process in the CONTRIBUTING doc (or somewhere).
It'd also be nice if the travis builds / make test used tox....i.e. have one recommended way to run the tests.

**Comment by tk0miya** [comment]
>	deleted:    CHANGES.old
>	deleted:    CONTRIBUTING.rst
>	deleted:    sphinx/locale/.tx/config
>	deleted:    sphinx/locale/sphinx.pot
>	deleted:    sphinx/pycode/pgen2/parse.c
>	deleted:    sphinx/pycode/pgen2/parse.pyx
>	deleted:    test-reqs.txt
>	deleted:    tox.ini

Added to MANIFEST.in

>	modified:   setup.cfg

modified by setuptools. So I don't change anything.

>	deleted:    sphinx/search/test

This appeared at ba64f54e4e817677341eae05907ae5160acc2560. But it seems not used. So I removed this.

**Comment by tk0miya** [comment]
@shimizukawa Did you mean this?
```
    package_data={
        'sphinx': ['pycode/*.pickle'],
    },
```

**Comment by tk0miya** [comment]
@shimizukawa ping

**Comment by tk0miya** [comment]
@shimizukawa ping again. If no reaction, I will merge this soon.

**Comment by shimizukawa** [comment]
"by using package_data keyword for setup.py" is incorrect.  This is correct code:
```
    data_files=[
        ('pycode', [
            'sphinx/pycode/Grammar-py2.pickle',
            'sphinx/pycode/Grammar-py3.pickle',
        ]),
    ],
```
This will create `Sphinx-1.5.2.dist-info` and` Sphinx-1.5.2.data` by bdist_wheel and the `Grammar-py*.pickle` file will be stored under `.data/pycode`.

However, there was two problems with this way.

1. The files under `.data` are installed in the appropriate directory depending on the environment, but when I tried it, it was installed in `/usr/local/pycode` (on docker environment). For now, I don't know whether this is the intended behavior or not.

2. I don't know how to get these installed files. I think pip installed the .data files by using the bundled distlib library, so I guess we should use distlib for acquisition as well. To use distlib from Sphinx, additional installation of distlib is required.

Because of these problems, so far, let's move forward without installation on `.data`.

**Comment by shimizukawa** [comment]
memo:

- [2.7. Installing Additional Files - Python 3.6](https://docs.python.org/3.6/distutils/setupscript.html#installing-additional-files)
- [data_files - Packaging and Distributing Projects - Python Packaging User Guide](https://packaging.python.org/distributing/#data-files)
- [Including Data Files - setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files)
- [Package Discovery and Resource Access using pkg_resources - setuptools](https://setuptools.readthedocs.io/en/latest/pkg_resources.html) this is not a wheel way
- [The .data directory - PEP 491 -- The Wheel Binary Package Format 1.9](https://www.python.org/dev/peps/pep-0491/#the-data-directory)
- [Using the resource API - distlib’s documentation](http://distlib.readthedocs.io/en/latest/tutorial.html#using-the-resource-api)

**Comment by tk0miya** [comment]
Okay, I don't mind about `package_data` at this moment.
Thanks,

**Comment by tk0miya** [comment]
Merged.
Thank you for reviewing.
Please let me know if next package still has any problem.

**Pull request merged**
