### PR TITLE
epub: allow to override build date

### PR DESCRIPTION
**Pull request by bmwiedemann**
to enable reproducible builds of packages like certbot in openSUSE

See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
I need some help here to make the tests pass. mypy seems to think that I cannot do `int(str)`

**Comment by bmwiedemann** [comment]
I made the code cleaner and got all tests green.
open question: should the buildtime function return a datetime object instead of a UNIX epoch (number of seconds)?

**Comment by tk0miya** [comment]
Thank you for PR!

Could you use `sphinx.util.i18n:format_date()` instead?
I feel new utility function is not needed.

**Comment by bmwiedemann** [comment]
updated and the epub3 part is somewhat tested.

**Comment by tk0miya** [comment]
Thanks!

**Pull request merged**
