### PR TITLE
fix #11121 added missing app.add_node(pending_xref_condition)

### LINKED ISSUE #11121: NotImplementedError: <class 'sphinx_math_dollar.extension.MathDollarReplacer'> visiting unknown node type: pending_xref_condition
### Describe the bug

Sphinx doesn't want to play nice with `sphinx-math-dollar`. Probably related to https://github.com/sphinx-doc/sphinx/issues/9240. The problem seems to be that `GenericNodeVisitor` lacks a `visit_pending_xref_condition` method. After some digging I figured this is because Sphinx does not register `pending_xref_condition` as a node.

The relevant code sections are:

- `sphinx-math-dollar`  https://github.com/sympy/sphinx-math-dollar/blob/be629b9cc252dd478bd99592578a2a79731eb649/sphinx_math_dollar/extension.py#L13-L44
- `docutils`: https://github.com/docutils/docutils/blob/173189b4c1c095a43c9388f4edd9bf1ff5d5b49d/docutils/docutils/nodes.py#L1953-L2080
- `sphinx`:  https://github.com/sphinx-doc/sphinx/blob/master/sphinx/addnodes.py

The issue seems to be that simply in https://github.com/sphinx-doc/sphinx/blob/e17f39e7b535f4849754d46f2cd2e411df8aa535/sphinx/addnodes.py#L521-L562 the statement `app.add_node(pending_xref_condition)` is missing.

-----

I also tried the following, as per the `sphinx-math-dollar` documentation:

```python
from sphinx_math_dollar import NODE_BLACKLIST
from docutils.nodes import header
from sphinx.addnodes import pending_xref_condition
math_dollar_debug = True
math_dollar_node_blacklist = NODE_BLACKLIST + (header, pending_xref_condition)
```

which didn't change anything, because `pending_xref_condition` is not registered as a node.

### How to Reproduce

Will provide if necessary

### Environment Information

<details><summary>bug report</summary>

```text
# Platform:         linux; (Linux-6.0.0-1009-oem-x86_64-with-glibc2.35)
# Sphinx version:   6.1.2
# Python version:   3.10.8 (CPython)
# Docutils version: 0.19
# Jinja2 version:   3.1.2
# Pygments version: 2.14.0

# Last messages:
#   reading sources... [  5%] apidoc/modules
#   reading sources... [  6%] apidoc/xxxx
#   reading sources... [  7%] apidoc/xxxx.config
#   
#   ====================== slowest reading durations =======================
#   0.084 RECIPES
#   0.012 CHANGELOG
#   0.008 apidoc/xxxx
#   0.007 README
#   0.007 CONTRIBUTING

# Loaded extensions:
#   sphinx.ext.mathjax (6.1.2)
#   sphinxcontrib.applehelp (1.0.3)
#   sphinxcontrib.devhelp (1.0.2)
#   sphinxcontrib.htmlhelp (2.0.0)
#   sphinxcontrib.serializinghtml (1.1.5)
#   sphinxcontrib.qthelp (1.0.3)
#   alabaster (0.7.12)
#   sphinx.ext.autodoc.preserve_defaults (6.1.2)
#   sphinx.ext.autodoc.type_comment (6.1.2)
#   sphinx.ext.autodoc.typehints (6.1.2)
#   sphinx.ext.autodoc (6.1.2)
#   sphinx.ext.autosectionlabel (6.1.2)
#   sphinx.ext.autosummary (6.1.2)
#   sphinx.ext.coverage (6.1.2)
#   sphinx.ext.doctest (6.1.2)
#   sphinx.ext.duration (6.1.2)
#   sphinx.ext.intersphinx (6.1.2)
#   sphinx.ext.napoleon (6.1.2)
#   sphinx.ext.todo (6.1.2)
#   sphinx.ext.viewcode (6.1.2)
#   sphinx_copybutton (0.5.1)
#   sphinx_math_dollar (unknown version)
#   pydata_sphinx_theme (unknown version)

# Traceback:
Traceback (most recent call last):
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/core.py", line 226, in publish
    self.apply_transforms()
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/core.py", line 206, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx/transforms/__init__.py", line 80, in apply_transforms
    super().apply_transforms()
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/transforms/__init__.py", line 173, in apply_transforms
    transform.apply(**kwargs)
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/sphinx_math_dollar/extension.py", line 80, in apply
    self.document.walk(MathDollarReplacer(self.document))
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/nodes.py", line 150, in walk
    if child.walk(visitor):
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/nodes.py", line 150, in walk
    if child.walk(visitor):
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/nodes.py", line 150, in walk
    if child.walk(visitor):
  [Previous line repeated 6 more times]
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/nodes.py", line 142, in walk
    visitor.dispatch_visit(self)
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/nodes.py", line 2005, in dispatch_visit
    return method(node)
  File "/home/rscholz/Projects/KIWI/xxxx/.venv/lib/python3.10/site-packages/docutils/nodes.py", line 2028, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'sphinx_math_dollar.extension.MathDollarReplacer'> visiting unknown node type: pending_xref_condition
```

</details>

### Sphinx extensions

```python
see bug report
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by randolf-scholz**
Subject: fix for #11121 !?

Simply added the (missing?!) line

```python
    app.add_node(pending_xref_condition)
```

### CODE REVIEW

**Comment by randolf-scholz** [comment]
Can this be merged? @tk0miya

**Comment by picnixz** [comment]
I don't think `pending_xref_condition` should be a supported node. This node is only meant to be a "placeholder" for reference resolvers which then choose amongst the different `pending_xref_condition` nodes the one which must be kept and rendered. 

If a `pending_xref_condition` node is still hanging, this means that a `pending_xref` node has never been processed (note that the `pending_xref_condition` should never be used as a standalone node and only used under a `pending_xref` node).

**Comment by randolf-scholz** [comment]
@picnixz The problem is that if it is not registered, then `GenericNodeVisitor` will raise an error when visiting the node.

In [`Sphinx.add_node`](https://github.com/sphinx-doc/sphinx/blob/b6e6805f80ad530231cf841e689498005cf2bb96/sphinx/application.py#L567-L609), `docutils.register_node(node)` is called, which adds a `visit_pending_xref_condition` method to `GenericNodeVisitor`.

https://github.com/sphinx-doc/sphinx/blob/b6e6805f80ad530231cf841e689498005cf2bb96/sphinx/util/docutils.py#L115-L123

AFAIK, the way sphinx-math-dollar works, is that it traveses all nodes, and whenever it encounters a text node tries to replace math `$$ ... $$` with actual RST math-tags. So if there are these "hanging nodes" that should be no issue? (sorry I am not that familiar with the internals of sphinx and docutils).

**Comment by picnixz** [comment]
I don't know whether it is intended or not to not add `pending_xref_condition` to the set of nodes. The documentation of `pending_xref_condition` states:

> This node is only allowed to be placed under a :py:class:`pending_xref`
node.  A **pending_xref** node must contain either no **pending_xref_condition**
nodes or it must only contains **pending_xref_condition** nodes.

For me, marking `pending_xref_condition`as a node means that it can be used as a standalone node which is not the case. 

In addition,

> The cross-reference resolver will replace a :py:class:`pending_xref` which
  contains **pending_xref_condition** nodes by the content of exactly one of
  those **pending_xref_condition** nodes' content.

In particular, the document obtained after applying the cross-reference resolvers must *never* contain a `pending_xref_condition` node. If it does, this means that there is an issue with the code itself. Now, if you can give me an example for which `sphinx-math-dollar` extension fails (and only this extension without any other extensions that can mess up the resolution phase), I'd be glad to investigate.

> An alternative would be to ask the maintainers of sphinx-math-dollar to manually add the visit function for pending_xref_condition, but that is not really a sustainable solution, because the package will break every time sphinx decides to add a new unregistered node type.

Technically, this should have been reported there before reporting here. I personally feel that `sphinx-math-dollar` should not have used a visitor pattern and instead rely on  `document.findall(...)` (at least, that's how most of the Sphinx transformations perform).

**Comment by randolf-scholz** [comment]
@picnixz I create a demo repository that shows the bug, both when using recursive autosummary or autoapi: https://github.com/randolf-scholz/sphinx-demo.

Enabling `sphinx-math-dollar` in the extension list in either case raises the error. I also added the patch at the bottom of each `conf.py` that makes it go away:

```python
from sphinx.util.docutils import register_node
from sphinx.addnodes import pending_xref_condition
register_node(pending_xref_condition)
```

**Comment by picnixz** [comment]
Thank you for your example but the example is too much complicated. I isolated the minimum example for which it fails and this is mainly because of `python_use_unqualified_type_names = True`.

### main.py

from typing import Any

```python
def foo(x) -> Any:
    r"""The identity function $f\colon X\longrightarrow X$."""
    return x
```

### index.rst

```rst
.. automodule:: main
   :members: 
``` 

### conf.py

```python
extensions = ['sphinx.ext.autodoc', 
              'sphinx.ext.intersphinx', # to see the different pending_xref_condition nodes
              'sphinx.ext.mathjax', 
              'sphinx_math_dollar']

intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}

mathjax3_config = {
  "tex": {
    "inlineMath": [['\\(', '\\)']],
    "displayMath": [["\\[", "\\]"]],
  }
}

# python_use_unqualified_type_names = True   # (failure)
# python_use_unqualified_type_names = False  # (default value)
```

The reason is that `python_use_unqualified_type_names` introduces `pending_xref_condition`, because there is *no* way to know  in advance how to resolve some unknown references. More precisely, the following nodes are created when encountering the `io.StringIO` in the function docstring when `python_use_unqualified_type_names=True`:

```xml
<pending_xref py:class="True" py:module="testmodule" refdomain="py" refexplicit="False" refspecific="True" reftarget="io.StringIO" reftype="class">
  <pending_xref_condition condition="resolved">
    <emphasis>
      StringIO
  <pending_xref_condition condition="*">
    io.StringIO
```    

Now, with `python_use_unqualified_type_names=False`, the node being generated is:

```xml
<pending_xref py:class="True" py:module="testmodule" refdomain="py" refexplicit="False" refspecific="True" reftarget="io.StringIO" reftype="class">
  io.StringIO
```

For me, the issue does not lie with Sphinx but with `sphinx-math-dollar` itself. IMHO, the approach of using a visitor pattern is not the correct one if they are using a docutils or Sphinx transformation and they should instead use `document.findall()` to correctly replace what they want (this is how docutils and Sphinx do for transformations or post-transformations). If they want to use the `GenericNodeVisitor` interface, they *should* also override `unknown_visit` in order to handle unknown remaining nodes.

I still believe that adding `pending_xref_condition` is wrong because this exposes an additional layer of implementation, even to developers. From my understanding, `add_node` is meant to add nodes that are supported by *translators* or to *validate* nodes in parsed documents. This is not the same as supporting them for *transformations* (which is what `sphinx-math-dollar` does). A translator transforms a document tree to another format (e.g., HTML output) whereas a *transformation* (or a post-transformation) is a mapping from a document tree to another document tree. Semantically speaking, this is something different (or at least, that's why I am opposed to adding `pending_xref_condition` as a real node). 

Furthermore, when writing extensions responsible for resolving references (or creating ones), we don't want to incorrectly introduce `pending_xref_condition` nodes without knowing that they are  placed under a `pending_xref` node. It will be quite difficult to check (at construction time of `pending_xref_condition`) that the node is indeed a child of a `pending_xref` node. 

The final decision is left to @AA-Turner or @tk0miya but I would object adding this "virtual" node to the list of real nodes unless they have a strong argument (the argument "it breaks a third-party extension but not Sphinx itself" is not strong enough for me). Instead, I think that `sphinx-math-dollar` must patch their implementation. In fact, using visitor pattern to only visit a single type of node (namely `nodes.Text`) feels an overkill.

### Note for myself

It appears that `desc_sig_element` is also a node that is not added (since it is more of a "base" class). This means I should probably change #11311 or ask @AA-Turner about the direction to take. If we do add `pending_xref_condition` to the set of supported nodes, then the treatment of `desc_sig_element` in #11311 should be changed as well. Currently `SigElementFallbackTransform` assumes that no instance of `desc_sig_element` exist in a document tree but only instances of subclasses (e.g., `desc_sig_space`) exist but I thought that `desc_sig_element` is a real node and I assumed that if a translator class implements a `visit_desc_sig_element` visitor method, then the node is supported (even if it is not added via `sphinx.add_node`).

**Comment by AA-Turner** [comment]
Closing, needs more discussion (on the issue, please!)

A

**Pull request closed without merging**
