### PR TITLE
Latex suppress vspace in multiline signatures

### PR DESCRIPTION
**Pull request by jfbu**
This is based on PR #3072, and addresses only a LaTeX issue. To be considered only after #3072.

### CODE REVIEW

**Comment by jakobandersen** [comment]
Thanks @jfbu for your quick response! I have now merged #3072.

**Comment by jfbu** [comment]
@jakobandersen on second thoughts I wonder if my patch has any real effect. Without it there is some glue first negative then positive to compensate, the effet of my patch is simply to remove them. But I now doubt it is necessary because trying to build flushedbottom pages I see that the interline spacing remains non-modified inside the multiline signatures... (which is logical because I think TeX spreads the needed total stretch on all available glue so negative should keep on compensating positive).

My TeX knowledge is a bit sketchy there. Do you have a concrete test file which shows some irregularity in interline spacing for the multiline signatures, for PDF output ?

(it could be that my PR is unneeded after all ;-) )

**Comment by jfbu** [comment]
I close this because although what it does is ok it seems it is in fact unneeded.

**Comment by jfbu** [comment]
I renamed the branch to https://github.com/jfbu/sphinx/tree/latex_multiline because the name was too long for my Terminal usually set at 80 chars.

**Comment by jakobandersen** [comment]
The following should illustrate the (minor) spacing problem. I have annotated with what I think the spacing should be.
```rst
.. cpp:function:: void a()
                  void b()

   Multiple single-line signatures: a bit of spacing and a bit of stretch.

.. cpp:function:: template<typename T> void c() 

   Multi-line signature: zero spacing and zero stretch.

.. cpp:function:: template<typename T> void d()
                  template<typename T> void e()

   Multiple multi-line signatures: zero, small, zero.

.. cpp:function:: void f()
.. cpp:function:: void g()

   An undocumented signature followed by another signature: normal large spacing with normal stretch.
```
The last case, between f and g, is already fine, as they are in different ``fulllineitems`` environments.
If I understand the definition of ``fulllineitems`` and your changes correctly, then I think we can just increase the default ``\itemsep`` (which currently is ``-\parskip`` to give zero spacing) to be the "small space plus small stretch". However, this will of course change the rendering of all cases similar to a,b in all other domains as well.

**Comment by jfbu** [comment]
arrgh, I had deleted the branch, and should have restored it from the github web interface, but I pushed to my fork a branch with same old name and now it seems I can't map this PR to it after this update. Ok, I will keep this PR closed and open a new one. Sorry for inconvenience I will link back to your comment from there.

**Pull request closed without merging**
