### PR TITLE
Quickstart should return an error consistently on all error conditions

### LINKED ISSUE #2955: Quickstart should return an error consistently on all error conditions
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py#L630 and https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py#L636 do not return an error but
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py#L595 does, even though all three conditions are equally fatal to the execution.

### PR DESCRIPTION
**Pull request by arcivanov**
fixes #2955, connected to #2955

### CODE REVIEW

**Comment by tk0miya** [comment]
LGTM.
Could you rebase this to stable branch? It would be nice this fix will be included next stable release.
In addition, please add CHANGES entry.

**Comment by arcivanov** [comment]
Will do, thanks @tk0miya

**Comment by arcivanov** [comment]
@tk0miya all set

**Comment by tk0miya** [comment]
Thanks for your quick work.
merged just now

**Pull request merged**
