### PR TITLE
Add py.typed to make PEP-561 compatible

### PR DESCRIPTION
**Pull request by lewis6991**
Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature

### Purpose
- Make module PEP-561 compatible

### Relates
- #6780

### CODE REVIEW

**Comment by tk0miya** [comment]
Have you tested this? It seems mypy docs you linked in #6780 says `setup.py` should be also modified. If working fine, I'll merge this soon.

**Comment by lewis6991** [comment]
Wasn't sure if it was needed. Tested locally and can confirm it works now.

**Comment by tk0miya** [comment]
Okay, I'll merge this after all tests are passed!

**Comment by tk0miya** [comment]
Merged. Thank you for contribution!

**Pull request merged**
