### PR TITLE
Let LaTeX writer allow figure dimensions using px unit (96px=1in)

### PR DESCRIPTION
**Pull request by jfbu**
Since 2005, pdftex allows to specify dimensions using px unit. One needs however to modify default 72px=1in to more standard (and CSS specified for print media) 96px=1in.

### CODE REVIEW

**Comment by nmat** [comment]
I like this. However it should be added to document also as a safe guide of how to calculate the html + PDF widths of for example images I guess. Mostly as a "keep it safe when converting to pdf" or am I wrong?

**Comment by jfbu** [comment]
@nmat I guess the better way to specify desired widths of included images for multiple output formats is to use cm, in, or like dimensions. But people may have project targeting primarily html and be used to px unit. Then they should not be surprised that when producing LaTeX the `:width:` specification is ignored if expressed in px. This PR makes it so that px specifications are passed over to produced latex. However possibly I should improve so that conf.py has some new key `latexpxperinch` with default value `96` (as per CSS recommendation for print media), but user can do `latexpxperinch=72` or `100` if needed.

**Comment by nmat** [comment]
@jfbu that makes sense...I guess I am just lazy with wanting the system to translate the `px` to `cm` for me.Like a one less thing to worry about when writing docs.

**Comment by jfbu** [comment]
Now, use new `'pixelsize'` key in `latex_elements` dictionary to change if needed default which will be `96px=1in` for LaTeX output. Prior to this PR, dimensions using px were just ignored by LaTeX writer. Now they are passed over as is to LaTeX source. 

Not compatible with xelatex. If xelatex needed, do not use px as dimension unit.

**Comment by jfbu** [comment]
@nmat problem is that it is not exactly clear what `1px` is. Only for print media there seems to be a recommendation that `96px=1in`. PDFTeX recognizes px unit since release 0.30 (2005) but has default `72px=1in`. Many documentations of LaTeX on the web do not explain one can use px unit since 2005. Besides, LuaLaTeX honors it, but not XeLaTeX.

**Comment by jfbu** [comment]
@nmat the `96px=1in` corresponds to simple `1px=0.75 postscript point`. But whereas html uses `pt` for the postcript point, TeX uses `pt` for a slightly smaller dimension: 1 postscript pt= 1.00375 TeX pt = 1 TeX bp. The docutils `latex2e` writer transforms `pt` into `bp`, but not so Sphinx, whose LaTeX writer simply copies from rst source to LaTeX output the given dimension as expressed in pt. This is a reason why I prefer using `cm` or `mm` unit. But I am no web designer. CSS recommends using `em` units, and there is more recent `rem` (aka root em). That is still usable directly without conversions by  LaTeX source but causes timing problems: should the `em` refer to the font used for the caption or for the text ? and if previous line was typeset bold, which may increase `em`,  should that mean the image is made bigger ?

More confusing yet is that the `96px=1in` CSS rule is only for print media. But is latexpdf really for print media ? afterall we probably read PDF more on screen than on paper ... but I am not aware of use of `px` by PDF viewers, like HTML viewers do.

**Comment by nmat** [comment]
@jfbu well using `px` values in general is bad I guess. Its only what most are used to use.

In the main sphinx documentation a reference on how to look up or to calculate the `em`, `cm`, `pt` etc might be good so that its clear what can be used with what converter.

IMO the HTML, PDF, MAN and text are the most common used formats today. (maybe even .docx is used quite a lot also for those with the office suite)

However converting to PDF and still having HTML is a really good starting point.

So in the doc it could be a good idea to have "tips and tricks" or just a way to find out more about the certain values to get the document the way they want?

I am not sure I know it would help quite a lot for me at least to see something of a "if you are going to convert to pdf make sure you use `em` value. Also check ......... for more information on calculating the value of `em` for your document."

Something like that?

**Comment by jfbu** [comment]
@nmat I gather from https://www.w3.org/TR/CSS2/syndata.html#length-units and https://www.w3.org/Style/Examples/007/units.html that px is good for html/xml on anything from smartphones to giant billboard. For pdf I prefer to use cm or in: I dislike using pt in Sphinx context because of ambiguity that TeX pt is not like everone's else pt hence I get a discrepancy between html and pdf output; and I dislike em for LaTeX, as I don't see why the typical width of characters in current font should influence size of included images, but I see the point of em in html.

Sure, some advice in Sphinx doc would be good, but that needs knowledgeable person... there is some documentation for the latex2e writer of docutils http://docutils.sourceforge.net/docs/user/latex.html. But what is needed is documentation which considers all cases: only html target, only pdf target, both html and pdf, and other output modes still.

**Comment by jfbu** [comment]
it slowly trickles down to me with horror that for browsers CSS says 1in=96px always, thus on higher density screen 1in is smaller than 1 physical in. In fact, as user I knew it from having since 2012 a laptop with higher than 96dpi, I always have to zoom web pages or customize firefox to use bigger fonts. The horror is that seemingly earlier CSS had the correct approach that 1in was always 1 physical in, but that 1px corresponded to a varying number of screen pixels depending on factors like distance of viewer to screen, and device resolution. But as there was a majority of faulty implementations, they have changed the thing and opted for the awful shocking approach that 1cm or 1in  is not really 1cm or 1in ! sorry for this rambling on topics people here no very well, but I hate it when compromises with real world go too far. (heritage from French Revolution).

**Comment by tk0miya** [comment]
almost LGTM. But this is incompatible changes. so this should move to master branch.

it would be better if sphinx can obtain the physical size of images from its property.
In addition, we have to improve this to convert the dimensions by python code for pTeX and XeTeX users.

**Comment by jfbu** [comment]
I am closing this, better way (as it works also for xelatex and platex) is #2711. Thanks @tk0miya for review and suggestion !

**Pull request closed without merging**
