### PR TITLE
Close #267: html: Eliminate prompt characters of doctest block from c…

### LINKED ISSUE #267: Eliminate prompt characters in examples from copyable text
It would be nice if the prompt characters in examples were easily copyable and pasteable somehow. For example, if this showed up on the document:

```
>>> for i in xrange(32)
...     print i
```

And you selected it, only these bits were selected.

```
for i in xrange(32)
    print i
```

This would make it easier to actually paste the examples into an interpreter.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/267
- Originally reported by: Michael Hoffman
- Originally created at: 2009-10-06T17:05:39.855

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Feature

### Purpose
- refs: #267

### CODE REVIEW

**Comment by ankostis** [comment]
That should be a goof fix till the javascript solution allows more flexibility to enable/disable copiable content.

**Comment by tk0miya** [comment]
Merged. This will be released as 2.3.0 later.

Note: I'm afraid that JS helper (like python-doc does) effects to HTML family builders (EPUB, HTMLHelp, AppleHelp and so on.). So I'd not like to add it for now.

**Comment by become-nice** [comment]
May i ask a question ? how to config it ? I can't find any information in docs.

**Comment by tk0miya** [comment]
No configurations. This change is always applied.

**Pull request merged**
