### PR TITLE
Fix: stemming removes short words from search results

### PR DESCRIPTION
**Pull request by TimKam**

### CODE REVIEW

**Comment by tk0miya** [comment]
Surely this change rescues short words from filters. But could you search these words?

In my environment, I put the word "zfs" to my document. And I confirmed the keyword was indexed in `searchindex.js`.
But I could not find the document from the search result of "zfs".
In my understanding, searchtools.js singularize the keywords as a normalization before looking up index. So it fails to search by "zfs".

**Comment by TimKam** [comment]
@tk0miya : I adjusted `searchtolls.js_t` a while ago. Could you have a look?

**Comment by tk0miya** [comment]
Oh, I've not noticed that. I'll take a look later.

**Comment by tk0miya** [comment]
@shibukawa could you give me your advice about this?

**Comment by shibukawa** [comment]
I think this fix is not general solution. How about this solution?
1. Add extra config to specify special words that should not be filtered, skip stemming to save special words.
2. Add build command line option to show filtering/stemming statistics to help/confirm setting of above special words configuration.

I have thought additional intention to index words would be required to add any meta-data. This will help adding other extra feature for example special stemming/alias (e.g. MacOSX -> macOS), word combinations support ("extra bold" instead of "extra" and "bold") and so on.

**Comment by TimKam** [comment]
Thanks a lot for the feedback.

Could we implement your suggestion and still keep the current fix (in addition)?
Because with this fix, all words >= 3 characters are added to the search index (excluding stop words, of course).
At least with a fuzzy search, writers then don't need to worry about maintaining a list in the configuration file.

**Comment by TimKam** [comment]
@shibukawa Could you please provide feedback on my suggestion?

**Comment by shibukawa** [comment]
Sorry my late reply.

I think current one is not preferred for Sphinx. Original searching feature was designed to reduce index file size as much as possible because search indexes are downloaded to client. Allowing all words are easy to use but against the original design. White list plan is controllable with size and quality, I think.

I have two question. How many meaningful short words in your document? And do you have any stats of index file sizes? These metrics are very helpful to decide the design. Sphinx is long living project, but there haven't been PR or issues about this part. I don't know how much / whether there is the needs for it.

**Comment by TimKam** [comment]
Thank you @shibukawa 
Maybe we have different perspectives on the implications of this feature/fix.
My implementation should add an additional word only if the word is:
- +=3 letters long
- cut by the _stemmer_ to a two letter word
- not excluded by the _filter_

This implementation addresses a particular edge case that creates false negatives.
However, there seem to be other users who experience this issue as well (see original ticket, + reference to this PR from another project).

In one of my larger Sphinx projects, my implementation increases the size of the search index from ~2950 LoC to ~3000 (by less than 2%).
I suppose this is ok.

However, I am - atm - not sure about the impact on false positives and will try to investigate this.

**Comment by shibukawa** [comment]
I tested your branch with bigger and the world biggest Sphinx project (searchindex.js file size):

Sphinx: 97kb -> 106kb
Python-3.5: 934kb->957kb

It seems ok for me. They are much smaller than I thought.

@TimKam Could you rebase to resolve conflict? Excuse our conservative decision-making.
@tk0miya I have no objection to merge this PR.

**Comment by TimKam** [comment]
@shibukawa Thank you!

**Comment by tk0miya** [comment]
Merged.
Thank you for all your help!

**Comment by jason-s** [comment]
Is there a way to facilitate search phrases? In other words if your Sphinx docs have lots of instances of "pink" and "pig" but only one instance of "pink pig", is there a way to configure / assist it into finding this reference?

**Pull request merged**
