### PR TITLE
enable pip cache in appveyor build

### PR DESCRIPTION
**Pull request by thijstriemstra**
Subject:  Enable caching of pip packages on appveyor.

### Feature or Bugfix
- Feature

### CODE REVIEW

**Review by tk0miya — CHANGES_REQUESTED** [review]
+0; I don't know so much about appveyor, but it looks good.

Could you rebase this into 1.7-release branch please? Then I'll merge this soon.

**Comment by thijstriemstra** [comment]
@tk0miya I don't know much about it either, but took these updates from https://github.com/scipy/scipy/blob/master/appveyor.yml where it seems to work well. If this PRs build is green I will rebase (need to figure out how though..)

**Comment by tk0miya** [comment]
If rebasing is hard to you, please close this and open a new PR. It's much simple.

**Comment by thijstriemstra** [comment]
@tk0miya opened #4552, closing this one.

**Pull request closed without merging**
