### PR TITLE
autosummary: expose inherited_members to template

### PR DESCRIPTION
**Pull request by kmaehashi**
I want to expose this variable to separately list inherited methods/attributes in class documents.

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
+1: reasonable.

**Review by shimizukawa — APPROVED** [review]
LGTM!

**Comment by tk0miya** [comment]
Merged.
Thank you for contribution!

**Comment by kmaehashi** [comment]
Thanks!

**Comment by fredrik-1** [comment]
I tried to use this today but the feature seems to be in the documentation and master but not in any release. Why?

edit: Ok, I found a 1.8.0 flag and realized that most of my searches to sphinx get me to the master documentation and that I also found a "button" where I can change what documentation I want to read.

**Comment by tk0miya** [comment]
oh, we have to mark `versionadded:: 1.8` to the variable. I'd missed it. Thanks,

**Pull request merged**
