### PR TITLE
Save search result score to HTML element for debugging

### PR DESCRIPTION
**Pull request by marxin**
It is handy for debugging of search results.

### CODE REVIEW

**Comment by AA-Turner** [comment]
Rebased.

A

**Comment by marxin** [comment]
@AA-Turner  Can you please merge the current `5.x` branch into `master` so that I can experiment with Sphinx docs search results?

**Comment by AA-Turner** [comment]
Done, but I think `readthedocs`'s server side search is overriding `searchtools.js`.

If you build the docs locally you can run `python -m http.server --directory build/sphinx` and go to `localhost:8000/` to get around CORS, does that help?

A

**Comment by marxin** [comment]
Great, that works fine, thanks!

**Pull request merged**
