### PR TITLE
builders/linkcheck: include "experimental" HTTP 308 as "permanently"

### PR DESCRIPTION
**Pull request by birkenfeld**
Also remove redundant "default" case.

### CODE REVIEW

**Review by tk0miya — COMMENTED** [review]
LGTM, boss. Could you rebase this to 2.0 branch? Then I'll ship this in next stable release (maybe in next weekend).
Thanks,

**Comment by tk0miya** [comment]
Note: it seems tests were failed. But it is not related with this patch, and it was already fixed at HEAD of master.

**Comment by birkenfeld** [comment]
Rebased! Nice to be committing again, even if it's only one line :)

**Comment by tk0miya** [comment]
Merged. Thanks,
We're always welcome you :-)

**Pull request merged**
