### PR TITLE
Psychopy

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Adding the chapter for programming experiments

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Ugh that's an ugly commit history ...

**Comment by jona-sassenhagen** [comment]
@aylinsgl do you know how we can check how it renders? Is it in the Circle builds?

**Comment by jfbu** [comment]
It seems you are targeting the wrong project, this is the Sphinx project itself here `:)`

**Comment by jona-sassenhagen** [comment]
Argh sorry :D

**Comment by jona-sassenhagen** [comment]
@jfbu would it be possible to delete this PR? I've been inaccurately classified as having contributed to sphinx development because of it.

**Comment by jfbu** [comment]
@jona-sassenhagen I think only an Owner can do that, if at all possible. @tk0miya what do you think?

**Comment by tk0miya** [comment]
I don't know the way to delete this. This post says you need to mail to github staff:
https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Comment by jona-sassenhagen** [comment]
Hm, it does not fall in that category (TOS violations/sensitive data). I guess then it will forever look like I contributed 20k lines of js and css on my GitHub.

Thanks for the help! (Sphinx is a great project!)

**Pull request closed without merging**
