### PR TITLE
Allow custom link texts for permalinks and links to source code.

### PR DESCRIPTION
**Pull request by doerwalter**
I'd like to be able to customize the content of the HTML links that Sphinx generates for permalinks and links to source code (generated by the `viewcode` extension).

E.g. instead of ``<a class="headerlink" href="..." title="Permalink to this definition">¶</a>``, I'd like to have ``<a class="headerlink" href="..." title="Permalink to this definition"><i class="fas fa-link"></i></a>`` to use [FontAwesome](https://fontawesome.com/) icons.

Note that the "Read The Docs" theme does this by fidling with the CSS to hide the text of the link and add's the icon via some `:after:` CSS rules.

IMHO it would be much clearer if this was customizable via configuration options.

This patch adds two configuration options:

`html_add_permalinks_html` which does the same as `html_add_permalinks`, but interprets the value as HTML, not as text.

`viewcode_source_html` which will be used as the link content for source code links generated by the `viewcode` extension. (The default is `<span class="viewcode-link">[source]</span>`).

This is my first attempt to work with the Sphinx source code, and I'm not exactly sure, whether defining a new node for the viewcode link text and replacing that node with the configured HTML in the HTML writer is the correct approach.

However with this patch I can now put
```python
html_add_permalinks_html = '<i class="fa fa-link"></i>'

viewcode_source_html = '<span class="viewcode-link"><i class="fa fa-code"></i></span>'
```

in my `conf.py` to get nice Font Awesome icons.

### CODE REVIEW

**Comment by tk0miya** [comment]
Thank you for proposal. I agree with your idea. But it would better to customize it via CSS to me. How about wrapping these labels with `<span>`? Adding a custom node will cause incompatibility to writers. Please take a look errors in Travis CI.

**Comment by doerwalter** [comment]
I agree that adding a custom node might be to invasive, but I don't know how else it would be possible to influence the generated HTML.

Tests seem to pass now, but I don't know whether `getattr` is the correct approach for that.

**Comment by doerwalter** [comment]
Hmm, the unused import that https://travis-ci.org/sphinx-doc/sphinx/jobs/555878900 complains about, seems to be used in the type annotation comments.

**Comment by doerwalter** [comment]
I've updated the pull request and removed the changes to the viewcode link. So there are no longer any custom nodes introduced by the patch. Only the option `html_add_permalinks_html` remains. Is there any chance for this patch to be merged?

**Comment by tk0miya** [comment]
Finally, I determined to support custom link text for permalinks. But it is not better to provide two ways to change the link text; `html_add_permalinks` and `html_add_permalinks_html`. Now I'm thinking about a new interface to control link text.

* `html_permalinks = True | False`: Enable or disable permalinks feature.
* `html_permalinks_icon = "¶"`: A text for the label of permalink. HTML tags are allowed.

Note: I think "add" prefix is a bit strange for the configuration name. So the new interface does not use it.

@shimizukawa Please let me know your idea if you have.

**Comment by shimizukawa** [comment]
I think the spec change looks good, but I have questions and ramblings.

* Question: What about html_add_permalinks support for HTML rendering? Of course backward compatibility will be lost, but I don't think it's unlikely that anyone would specify HTML fragments, since they have never been interpreted as HTML.

* Miscellaneous: Naming of `html_add_permalinks` is not good. I agreed `html_permalinks` is better.

* Miscellaneous: I found it difficult to understand that HTML can be specified from the name `html_permalinks_icon`. I feel that the name of the setting is not easy to understand no matter how it is devised, because many things can be specified such as icons, text, and HTML. I thought of this idea: `html_permalinks` can be set to text, icons, or HTML, and if the value is false it will not be displayed. I thought of this idea, but that would be adding a change to the original spec to accept HTML.

<details>
<summary>In Japanese</summary>
私はその仕様変更はよさそうだと思いますが、質問と雑感があります。

* 質問: html_add_permalinks がHTMLレンダリングをサポートするのはどうでしょうか？もちろん後方互換性は失われますが、これまでHTMLとして解釈されていないため、HTML断片を指定している人はまずいないと思います。

* 略

* 雑感: 私は、html_permalinks_icon という名称からHTMLを指定してよいことが分かりづらいと感じました。アイコンやテキスト、HTMLなど色々指定可能なため、設定名称はどう工夫しても分かりやすくなりにくい気もします。 `html_permalinks` に、文字やアイコン、HTMLを指定できるようにして、値が偽だったら表示しない。このような案を考えましたが、それは元の仕様にHTMLを受け入れる変更を追加したものですね。
</details>

**Comment by tk0miya** [comment]
I think it is not a good way that one config variables controlling both enabling the feature and changing the marker. So I'd like to separate them into individual variables. So I object to adding a new feature to `html_add_permalinks` itself. I think it is more explicit to separate them.

>I found it difficult to understand that HTML can be specified from the name html_permalinks_icon.

I'm not so worried about that. It's enough to describe it accepts HTML tags in the document.

**Pull request closed without merging**
