### PR TITLE
[doc] Compare docutils and Sphinx

### PR DESCRIPTION
**Pull request by stephenfin**
Add an FAQ entry comparing the two.

### CODE REVIEW

**Review by tk0miya — APPROVED** [review]
LGTM. I'll merged this after CI fixed.

**Comment by stephenfin** [comment]
> LGTM. I'll merged this after CI fixed.

I don't think that's related to this change?

**Comment by tk0miya** [comment]
>I don't think that's related to this change?

Yes, but 3.x branch is now broken. So I'd not like to merge it now.

**Comment by tk0miya** [comment]
Merged now.

**Pull request merged**
