### PR TITLE
Napoleon keyword

### PR DESCRIPTION
**Pull request by dahpgjgamgan**
an initial fix for #2379 - I am not sure I github enough to link the issues correctly...

anyway, few notes:
- I am not sure about the patching of PyObject.doc_field_types (it works, but not sure if this is the right way to go)
- I've kept the new behaviour under config flag... but maybe it's better to keep it under napoleon_use_param ?
- plz let me know if any additional docs/tests are required

### CODE REVIEW

**Comment by RobRuana** [comment]
Sorry I didn't respond sooner, for some reason github did not send me a notification about this pull request.

A few comments:
- I agree that patching PyObject.doc_field_types directly is probably not the right way to go. I am not sure how to best implement this behavior. If you want to find a better way, please give it a try.
- Keeping the new behavior under a new config flag is probably better.
- Can you please squash the commits in the pull request?

If I don't respond to any updates, please drop a comment in the original issue: #2379. I am definitely receiving notifications for that issue.

Thank you very much for contributing!

**Comment by dahpgjgamgan** [comment]
So - one alternative to monkey patching... an obvious one - is to have the new field info description available for everyone - under a slightly awkward name, but with the added benefit of having the solution backward compatible. BTW the current field info description was inaccurate.

I can't see any other solutions that would not involve either changing the existing python domain (either via monkey patching or not), creating an own domain (which again, would server only the purpose of changing the doc_field_types) or a completely-blown-out-of-proportion-refactoring after which I could write myself my own sphinx... with blackjack and... :)

if you ok this approach, I'll do the squash, no problem.

**Comment by RobRuana** [comment]
Hmm, this is a tough decision. I hate to say it, but I think the original monkey patch was actually cleaner. Otherwise we end up with an undocumented role – `kwtypearg` – in the main sphinx code that is semantically the same as existing roles – `keyword`, `kwarg`, `kwparam` – but produces different output :(

And like you say, any other design would be total overkill. I think we should keep the original design. If you revert the pull request back and squash it, I'll go ahead and merge it.

Thank you again for your work!

**Comment by dahpgjgamgan** [comment]
No problem, better to see a few solutions before deciding.  So, I reverted the last changes and squashed the other ones. Hope this is ok.

**Comment by RobRuana** [comment]
Looks great! Thanks again!

**Pull request merged**
