### PR TITLE
Fix #5294: sphinx-quickstart blank prompts in PowerShell

### LINKED ISSUE #5294: sphinx-quickstart blank prompts in PowerShell
Subject: using sphinx-quickstart with PowerShell (v1.0) in Windows results in blank prompts

### Problem
image

#### Procedure to reproduce the problem
run `sphinx-quickstart`

#### Expected results
Works fine in git-bash
image

### Environment info
- OS: Windows 10
- Python version: 3.6.5
- Sphinx version: 1.7.6

### PR DESCRIPTION
**Pull request by tk0miya**
### Feature or Bugfix
- Bugfix

### Purpose
- refs: #5294

### CODE REVIEW

**Comment by shimizukawa** [comment]
master
image

this branch
image

**Comment by shimizukawa** [comment]
default windows powershell colorschema
image

**Review by shimizukawa — APPROVED** [review]
I think `bold` in the PowerShell is `yellow`, so this PR looks good to me.

**Comment by tk0miya** [comment]
Thanks!

**Pull request merged**
