### PR TITLE
Fix #3788: smartquotes emits warnings for unsupported languages

### LINKED ISSUE #3788: Turkish smart quotes / docutils warnings
I updated Sphinx to version 1.6.1 and docutils to version 0.13.1. I'm building .tex documents in several languages, including Turkish. The Turkish build outputs first

`[exec] WARNING: C:\foo\bar.rst:: (WARNING/2) language "tr" not supported: Docutils-generated text will be in English.`

and then thousands of lines similar to 

`[exec] C:\foo\foobar.rst:28: WARNING: No smart quotes defined for language "tr".`

I see there are some changes in latest Sphinx versions related to handling of smart quotes. I also see that docutils languages directory does not include Turkish language (tr.py). Is the problem simply that docutils does not support Turkish translation? In the end, my end results (PDF files) look fine and, on first glance, references etc. seem to work fine.

I did not get these warnings with Sphinx version 1.5.x. What can I do to get rid of the warnings?

### PR DESCRIPTION
**Pull request by tk0miya**
This tries to reduce warnings from docutils.
refs: #3788

### CODE REVIEW

**Comment by tk0miya** [comment]
I closed/reopened this intentionally because I'd chosen wrong target branch.

**Review by jfbu — COMMENTED** [review]
There is a difficulty that docutils has a discrepancy between the list of languages supported already at 0.13.1 by smartquotes and the list of languages for which a module exists in docutils.languages

For example there is
```
              'et':           u'„“‚‘', # no secondary quote listed in
              'et-x-altquot': u'»«›‹', # the sources above (wikipedia.org)
```
in docutils.utils.smartquotes, but there is no ``et`` module in docutils.languages.

When I tested #3788 I got the impression that 1.5.6 Sphinx ended calling `get_language` always with `'en'`. It seems it does not matter for Sphinx.

edit: I mean by that it does not matter because in my testing the smart quotes were applied (for French, Turkish after setting `quotes['tr']` even if `get_language` was called only with ``'en'``. And the html was internationalized, like the latex.

**Comment by tk0miya** [comment]
>There is a difficulty that docutils has a discrepancy between the list of languages supported already at 0.13.1 by smartquotes and the list of languages for which a module exists in docutils.languages

Hmm... but the warnings are emitted by `docutils.languages.get_language()` and it is called before smart-quotes processing (see `docutils.transforms.universal`). So it is better to use the function to check supported or not.

**Comment by jfbu** [comment]
I have asked a question  at https://sourceforge.net/p/docutils/mailman/docutils-develop/.

(it will appear there promptly)

https://sourceforge.net/p/docutils/mailman/message/35861133/

Is it correct that before Sphinx 1.6 series the `docutils.languages.get_language()`  ended up being called <strike>by Sphinx</strike> during document processing only with ``'en'`` as language code ? (independently of the ``language`` config)

**Comment by jfbu** [comment]
I have slightly off-topic question: also with 1.5.6 when I try with `tr` I see

    dumping search index in Turkish (code: tr) ... done

but with `et` (which is also [Sphinx supported language](http://www.sphinx-doc.org/en/stable/config.html?highlight=language#confval-language)) it ends wih

```
loading translations [et]... done
loading pickled environment... done
[...]
dumping search index in English (code: en) ... done
```
The html output for ``'et'`` does use the language.

**Review by jfbu — APPROVED** [review]

**Comment by tk0miya** [comment]
>Is it correct that before Sphinx 1.6 series the docutils.languages.get_language() ended up being called by Sphinx during document processing only with 'en' as language code ? (independently of the language config)

As a quick look, `docutils.frontend.OptionParser` which is creator of the settings objects has following definition:
```
         ('Specify the language (as BCP 47 language tag).  Default: en.',
          ['--language', '-l'], {'dest': 'language_code', 'default': 'en',
                                 'metavar': '<name>'}),
```
before 1.6, we did not give a language option to docutils. so this default setting might be used.


On the other hand, about a language of search index, Sphinx only supports very few languages for search index: https://github.com/sphinx-doc/sphinx/tree/master/sphinx/search .
We provides `sphinx.search.tr` for Turkish, but we don't provides no definitions for Estonian.
So Sphinx fallbacks to English.

**Comment by jfbu** [comment]
1. I did not know settings objects came from ``docutils.frontend.OptionParser``.
 
   There is a very complete [reply by Günter](https://sourceforge.net/p/docutils/mailman/message/35861407/) to my question about the language code settings. I need to examine more closely, but as far as I understand now it matters only if the document will have Docutils generated strings, but Sphinx seems to rely entirely on its own localizations.

   Hence whether the language is recognized by Docutils ``get_language()`` seems not important for Sphinx, and one should not exclude such language from smart quotes processing. I need to get better understanding of mechanism though. Perhaps my monkey patch at #3788 which simply tricks ``get_language()`` into thinking the language code is always ``'en'`` has no bad effect, after all. But of course it should be done differently by core Sphinx because monkey patching is bad.

2. Thanks for information about search indices. I understand now.

**Comment by tk0miya** [comment]
merged #3813 instead.

**Pull request closed without merging**
