### PR TITLE
Closes #1968: Show extended type hints for function annotations that use 'typing' module

### LINKED ISSUE #1968: Show PEP 484 type hints correctly
Currently Sphinx outputs function annotations in a way that is not quite compatible with how PEP 484 type hints look like.

Here is a test Python module where I have identified some bugs in the visual representation of annotations generated by Sphinx:

``` python
from typing import (Union, AnyStr, Callable, TypeVar, Iterable, List, Tuple,
                    Generic)


class MyClass:
    """Some class."""


def simple_classes(p1: str, p2: int, p3: MyClass, p4: int=None) -> None:
    """Simple classes.

    BUG: No spaces around ``=`` in ``p4: int=None``.
    """


StrAlias = str
UnionAlias = Union[str, bytes]


def type_aliases(p1: StrAlias, p2: UnionAlias, p3: AnyStr) -> None:
    """Type aliases.

    BUG: ``typing.Union`` instead of ``typing.Union[str, bytes]``.

    Q: Is ``typing.Union`` too long?
    """


def callable_types(p1: Callable[[int], str], p2: Callable[..., str]) -> None:
    """Callable types.

    BUG: The same as for ``typing.Union``.
    """


T = TypeVar('T')
T_co = TypeVar('T_co', covariant=True)
T_contra = TypeVar('T_contra', contravariant=True)
OurStr = TypeVar('OurStr', str, bytes)


def generic_functions(p1: T, p2: Iterable[T_co], p3: OurStr) -> List[T_contra]:
    """Generic functions.

    BUG: ``typing.T`` for ``p1`` is wrong. It should be ``foo.T`` or
    ``typing.TypeVar('T')`` or something else. The same problem is with
    ``typing.OurStr`` for ``p3``.

    BUG: The same as for ``typing.Union``.

    Q: How to represent covariant and contravariant types?

    * ``T(covariant=True)``
    * ``+T`` (as in ``__repr__``)
    """


def tuple_types(p1: Tuple[str, int, list], p2: Tuple[str, ...]) -> None:
    """Tuple types.

    BUG: The same as for ``typing.Union``.
    """


def quoted_hints(p1: StrAlias, p2: 'StrAlias') -> None:
    """Quoted hints.

    BUG: The hints for ``p1`` and ``p2`` should be the same. Get types
    using ``typing.get_type_hints()``.
    """


class MyGeneric(Generic[T], MyClass):
    """User-defined generic classes."""

    def get(self) -> T:
        """Return user-defined generics.

        BUG: The same as for ``typing.T`` in :py:func:`generic_functions`.
        """

    def set(self, T) -> None:
        """Accept user-defined generics as parameters."""

```

### PR DESCRIPTION
**Pull request by vlasovskikh**
The results of the EuroPython 2015 sprint. See #1968.

### CODE REVIEW

**Comment by vlasovskikh** [comment]
Now all the tests pass.

The only thing from the PEP 484 notation that still isn't shown correctly is a function type with unspecified parameters: `typing.Callable[..., int]`. The problem with it is due to a bug in the `typing` module, see https://github.com/ambv/typehinting/issues/149.

Possible next steps are adding hyperlinks to type annotations, but this is out of the scope of this PR.

**Comment by birkenfeld** [comment]
Thanks for the PR! I'll check and merge it soon.

**Comment by lehmannro** [comment]
I stumbled over the new `autodoc.formatargspec` during review for PR #1882.  Is there any good reason why the _whole_ formatting machinery needed to be reimplemented instead of just tuning `inspect.formatargspec(formatarg=)`?

**Comment by vlasovskikh** [comment]
@lehmannro `inspect.formatargspec()` isn't flexible enough to handle the formatting we use for type hints. In particular, we couldn't manage to put the right spacing around `=` for annotated and not annotated parameters. There were other reasons related to type hints in function annotations, but I cannot remember them. The idea is that parameters are related and cannot be processed one by one using `formatarg=`. The diff between the current `formatargspec()` and `inspect.formatargspec()` could help here.

**Pull request merged**
