### PR TITLE
``'sphinxpackageoptions'`` for key=value styling of Sphinx LaTeX

### PR DESCRIPTION
**Pull request by jfbu**
added note at the time of second commit: I realized that PR #2685 (e5db9da45d31014b99615748b5611892a8f9a35d) which introduced the various macros `\sphinxwarningborder` etc... had never been merged yet into a release, but only in master branch. Hence they were not documented officially yet (12ade10d5593a07beab438140f0b27a390a84fff was only in master), so in second commit I can remove a dozen lines by using directly the `\spx@opt@warningborder` etc... provided by the option handling.

### CODE REVIEW

**Comment by jfbu** [comment]
The https://github.com/jfbu/sphinx/blob/latex_keyvalueoptions/doc/latex.rst documents the possible options. Should we tag this as experimental ? This builds upon PR #2685 which made the various types of admonitions separately configurable. With the present PR, one only needs to set-up `'sphinxpackageoptions'` string in conf.py. But if in future more ways of styling LaTeX could arise, and perhaps some of the options (width of the frame, colour of the frame, colour of the background) could become non adequate. I thus don't know how to best document it.

Perhaps simply add a warning: _these options correspond to what has been so far Sphinx default's styling in LaTeX; if in future Sphinx offers various "themes" for LaTeX, the interface may change_

**Comment by jfbu** [comment]
side-note: there is a problem with the `sphinx13` theme for HTML output when a code-block appears inside an admonition (note, warning, ...: one sees white vertical strips next to the code-blocks). For example, an extract of how
https://github.com/jfbu/sphinx/blob/latex_keyvalueoptions/doc/latex.rst looks in html output:

capture d ecran 2016-10-29 a 16 40 52

**Comment by jfbu** [comment]
@tk0miya 

The legacy colours are TitleColor, InnerLinkColor, OuterLinkColor, VerbatimColor and VerbatimBorderColor. For notices and admonitions, there were no colours. They were first introduced at PR #2685 but using lowercase names sphinxwarningbordercolor etc...

I am thinking it would be more coherent to have uppercase too: sphinxWarningBorderColor, etc... Then I would name the option for the key=value syntax also WarningBorderColor. The PR #2685 has not been part of official release yet, it was only on master. Thus this would not break things. What do you think about uppercasing all names for colour options ? (it is easiest if the option name and the colour name are handled the same, hence I would uppercase also all colour names, but they were not yet public hence this is not breaking change.)

Apart from that, the key=value syntax is well-known now in LaTeX world. Perhaps a Python dict could be used, but as this is only for LaTeX target, I thought that using directly LaTeX, not Python syntax was ok.

Initially in this PR I was passing all options to sphinx as package options. But this is not possible for options whose values are LaTeX macros (like for the "verbatimcontinued" option.) We must use `\sphinxsetup` command for this kind of package options.

The next step in this PR was to re-factor the key handling, because with the initial version of `\sphinxsetup` each time it was used for one option it would redeclare all dimensions and colours. Thus I re-factored the key handling to work individually. I use "kvoptions" package which was almost final at time of TL2009. There is more modern syntax with "pgfkeys" package but this can wait until we support only TL2013.

I have updated the documentation, and for the LaTeX chapter I used `raw` directive to inject some LaTeX styling via the `\sphinxsetup` interface...

**Comment by tk0miya** [comment]
Great work!
Of course I'm okay to rename the variable names to camelCase.

> But if in future more ways of styling LaTeX could arise, and perhaps some of the options (width of the frame, colour of the frame, colour of the background) could become non adequate. I thus don't know how to best document it.

I know. It is not easy to say the interfaces are stable.
But nobody don't know perfect one. So don't be afraid the changes.

Of course, it's okay to mark them as experimental if you feel the variables are still unstable or fragile.

> Perhaps simply add a warning: these options correspond to what has been so far Sphinx default's styling in LaTeX; if in future Sphinx offers various "themes" for LaTeX, the interface may change

Maybe, LaTeX themeing will bring breakable change.
So I think it would be nice to introduce it in next major release; Sphinx-2.0.

**Comment by jfbu** [comment]
@tk0miya thanks for comments, 

at https://github.com/sphinx-doc/sphinx/pull/3104/commits/e70746e8daf208d88c9e8d88b1fc623d0cbe669d I already camelCased the colour names but with `warningBorderColor`, `attentionBgColor`... i.e. keeping the admonition names in lowercase as in the LaTeX environment. (for technical reasons).

regarding possible instability of interface I have currently included this warning

capture d ecran 2016-10-31 a 19 26 55

I think package `tcolorbox` mentioned in other thread could be useful for LaTeX themeing.

**Comment by jfbu** [comment]
sorry, thread mentioning `tcolorbox` is at #3099.

**Comment by tk0miya** [comment]
Okay. I believe #3070 helps to use `tcolorbox`.

Anyway, I'm okay to merge this. Please merge this when you like.

**Comment by jfbu** [comment]
@tk0miya thanks a lot for looking ! I will now merge so that it gives more time to see if problems arise.

**Comment by jfbu** [comment]
There was a Python  error (my bad, sorry) in latex.py in commit https://github.com/sphinx-doc/sphinx/pull/3104/commits/528b6c374c9ca3ba6f80817a3253e1207f286ef6#diff-81c44cde8d80608ae558b93878f9be8aR451 which I have fixed at f2b63b4 by reverting to earlier code. I was trying to avoid unneeded commas, but anyhow it is not a problem if there is one.

**Pull request merged**
