### PR TITLE
Allow image directory to be specified (solution for #10906)

### PR DESCRIPTION
**Pull request by pcolmer**
Subject: extends image support to allow directory and HTML path to be set

### Feature or Bugfix
- Feature

### Purpose
- Using #10906 as the initial concept, this PR allows the name of the directory where the images will be stored to be set, as well as an optional setting for the path to be used when generating the HTML.

### Detail
- Provides a configuration key of `html_image_dir` which is a relative path, e.g. `images` or `images/foo`. This will be used instead of `_images` when building the documentation.
- Provides a configuration key of `html_image_path` which is the path from the documentation root to be used instead of the default, which is a path relative to the page referencing the image. This is useful if the images get copied elsewhere as part of incorporating the documentation into a larger website.

### Relates
- #10906

### CODE REVIEW

**Comment by pcolmer** [comment]
There will also be a PR for `sphinxcontrib-serializinghtml` to implement the matching change.

**Comment by pcolmer** [comment]
I'll make the code more robust and use try...except so that the extension works with current and future versions of Sphinx.

**Comment by jayaddison** [comment]
What's the reason for two separate configuration entries?  I understand that one of them is a path, and one of them is a directory name - it seems like a single directory path might suffice?

Also, as the commits here are from two different identities (both you, but possibly from one work and one personal account?), could you confirm whether these are contributions on behalf of Linaro or by you individually?  I don't believe we require a DCO at the moment, but providing an appropriate self/corporate credit in `CHANGES.rst` would make sense in any case.

**Comment by pcolmer** [comment]
> What's the reason for two separate configuration entries? I understand that one of them is a path, and one of them is a directory name - it seems like a single directory path might suffice?

One of them specifies the name of the directory that the images are being copied into. This meets the requirements of #10906, I believe.

The path was an extra setting that I wanted to add because it solves an issue where the images might be located in a folder OTHER than one relative to the current document.

For example, when building with Next, typically the directory to store images in might be called `/public/images` ... but the path when the website is built becomes `/images`. As a result, I couldn't think of a way to solve this with one configuration entry, but I did try to tackle it in a way that existing documentation repositories will build without any changes needed.

> Also, as the commits here are from two different identities (both you, but possibly from one work and one personal account?), could you confirm whether these are contributions on behalf of Linaro or by you individually? I don't believe we require a DCO at the moment, but providing an appropriate self/corporate credit in CHANGES.rst would make sense in any case.

Apologies for that. I don't think it matters whether it is a credit to me or to Linaro.

**Comment by jayaddison** [comment]
> The path was an extra setting that I wanted to add because it solves an issue where the images might be located in a folder OTHER than one relative to the current document.

Thanks for the explanation.  I'm OK with the `html_image_dir` setting, and I think that would resolve #10906 -- I'm less confident about the `html_image_path` setting.

To elaborate on that: I think altering the internal URI paths goes against an implicit principle of the Sphinx HTML builders: they produce HTML output where all internal resources are referenced relative to a common base location, meaning that the output directory provides a functional, internally-consistent website when hosted using a simple HTTP server.

I'm not keen on supporting divergence from that; it seems like the kind of thing that should be resolved either by configuration on the host's webserver, or if necessary by post-processing the output on a per-project basis.

**Comment by pcolmer** [comment]
> I'm not keen on supporting divergence from that; it seems like the kind of thing that should be resolved either by configuration on the host's webserver, or if necessary by post-processing the output on a per-project basis.

The first approach won't work for our infrastructure because we don't use webservers. We use CloudFront + S3, and trying to manage any sort of URL redirection would become an administrative nightmare compared with building the site "correctly" in the first place.

I don't know how to tackle post-processing the output. The person who created #10906 suggests that they tried a similar approach just to handle the image directory name - not even where it was located - and got stuck.

But that's OK. I'll fork an internal copy of Sphinx and adapt it to better suit our needs.

Feel free to use the contribution for the image directory if you like. No attribution required.

**Comment by AA-Turner** [comment]
Sorry I haven't had time to review until now

I think ``html_image_path`` is actually fine. We allow fully-qualified URIs in quite a few cases, and this is one where it makes sense (e.g. all images on a different server).

I might suggest naming it with the ``uri`` suffix instead, to make it clear that this is an advanced option, though.

Would you still be willing to continue the PR @pcolmer? At first glance it looks good, ideally we would want documentation of the new settings and some tests.

A

**Comment by pcolmer** [comment]
@AA-Turner I'm out of the office next week for offsite work purposes and then I'm on vacation for two weeks. I can try to spend some time on it when I return.

Where do you want the new settings documented?

**Pull request closed without merging**
