### PR TITLE
[docs] Add Github repo icon-link to topbar

### PR DESCRIPTION
**Pull request by chrisjsewell**
Add a link to https://github.com/sphinx-doc/sphinx, via an icon on the right of the topbar

image

https://sphinx--12462.org.readthedocs.build/en/12462/

### CODE REVIEW

**Comment by chrisjsewell** [comment]
cc @timhoffm

**Review by picnixz — COMMENTED** [review]
Don't we have this already with the RTD widget? do you want to duplicate it? Personally, I'd prefer having it in the footer rather at the top (it's a bit less intruisive)

**Comment by chrisjsewell** [comment]
> I'd prefer having it in the footer rather at the top (it's a bit less intruisive)

I'm afraid I must vehemently disagree here;
the whole is to make it prominent, and obvious to users how to navigate to the source repository.
I can point to a multitude of OSS based tools (particularly related to documentation) that use this convention in their documentation, in fact it is hard to find any that do not 😅 

- https://react.dev/
- https://svelte.dev/
- https://astro.build/
- https://docs.solidjs.com/
- https://squidfunk.github.io/mkdocs-material/getting-started/

**Review by picnixz — APPROVED** [review]
Ok, I'm in.

**Comment by chrisjsewell** [comment]
> Ok, I'm in.

Thanks 😄 

and BTW thanks for all the quick reviews, let me know if you have any PRs outstanding I should be looking at!

**Comment by timhoffm** [comment]
Thanks, this is an improvement. :+1: As a feedback, I've been looking for a GitHub link from inside the docs multiple times. It was something like "Contribute -> Contribute Code -> Find a link somewhere in a paragraph of text".

**Comment by picnixz** [comment]
> and BTW thanks for all the quick reviews, let me know if you have any PRs outstanding I should be looking at!

No problem! the only PR that is still waiting for rewiew is #12219 but this is a huge one. If you have a bit of time, then I don't mind. Most of my ongoing PRs are in CPython currently.

**Pull request merged**
