### PR TITLE
#3620: move basic theme's DOCUMENTATION_OPTIONS to js_t

### PR DESCRIPTION
**Pull request by ghost**
Subject: move basic theme's DOCUMENTATION_OPTIONS to js_t

### Feature or Bugfix
- Bugfix

### Purpose
- Removing inline javascript will allow certain users to enable [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

### Relates
- #3620

### CODE REVIEW

**Comment by shibukawa** [comment]
Great Pull Request!! Thank you!

**Comment by tk0miya** [comment]
I changed the target to master branch. So it will be released as 1.7.

**Comment by tk0miya** [comment]
OMG, conflicts with #4245. I will fix it tomorrow.

**Comment by tk0miya** [comment]
I merged this manually: de023f2dc0972fc398975c5614caf89149a2de16
Thank you for your contribution!

**Comment by davidism** [comment]
This broke the search page when using the `dirhtml` builder. When the JS was included inline, `pathto` generated a `url_root` of `../`, so that the links on the `/search/` page would point to the parent dir. Now `url_root` is always `''`, so the links incorrectly point below the search page.

**Pull request closed without merging**
