### PR TITLE
installation.rst: correct Windows Run keyboard shortcut

### PR DESCRIPTION
**Pull request by kenyon**
You type Windows-R to get the Run dialog, not Control-R.

### CODE REVIEW

**Review by stephenfin — APPROVED** [review]
Oh, that was dumb. Good catch. I'm a little concerned about the use of the unicode characters, but the docs build seems OK with it so why not

**Comment by tk0miya** [comment]
Thanks!

**Comment by jfbu** [comment]
This causes failed PDF build

```
! Package inputenc Error: Unicode char ⊞ (U+229E)
(inputenc)                not set up for use with LaTeX.
```

I will fix later.

**Comment by jfbu** [comment]
(fixed Unicode issue for PDF builds via pdflatex at 39ce9d9ab)

**Comment by jfbu** [comment]
At https://en.wikipedia.org/wiki/Windows_key, uppercase letters are used in the description ``⊞ Win + R`` for example (and I used a no break space before Win). What is common habit in Windows world? (I am completely ignorant)

**Comment by stephenfin** [comment]
Do we not build this stuff with CI? If not, we should add something to ensure this doesn't happen again.

**Comment by jfbu** [comment]
@stephenfin At my locale `make latexpdf` on a clean state takes about 1minute

```
real	0m57.888s
user	0m57.108s
sys	0m0.528s
```

compared to 12.5s for html

```
The HTML pages are in _build/html.

real	0m12.628s
user	0m12.400s
sys	0m0.207s
```

The overhead in PDF build isn't into the actual pdflatex processing but into the Sphinx build of the LaTeX source.

I have not checked our CI settings, but building PDF docs might have been deactivated because of that. When building first html then latexpdf, the latter takes only about 48s. TIming both together I get about 62s.

**Pull request merged**
