### PR TITLE
Format literalinclude directive options

### PR DESCRIPTION
**Pull request by timhoffm**
Follow-up to / in the same spirit of https://github.com/sphinx-doc/sphinx/pull/12725 and #12779.

### CODE REVIEW

**Comment by AA-Turner** [comment]
Docs failing

**Comment by timhoffm** [comment]
> Docs failing

with the message

> locale_dir /home/runner/work/sphinx/sphinx/doc/locale/en/LC_MESSAGES does not exist

This does not seem to be related to the PR. Is there a way to re-trigger the docs build?

**Comment by timhoffm** [comment]
Hm, still failing. OTOH this just changed one rst file. Do you have any idea how the error could be related to that?

**Comment by picnixz** [comment]
The failure is:

```
2024-08-17T12:05:05.4064723Z: /home/runner/work/sphinx/sphinx/doc/usage/restructuredtext/directives.rst:855: WARNING: duplicate description of directive:option code-block:force, other instance in usage/restructuredtext/directives
```

**Pull request merged**
