### PR TITLE
Make test_attrgetter_using test dependant.

### PR DESCRIPTION
**Pull request by marxin**
One cannot run the mentioned test individually and thus it brings troubles with pytest -n auto.

@AA-Turner

### CODE REVIEW

**Comment by picnixz** [comment]
Since your seem to fix those kind of tests, maybe you can gather them under the issue I created (which also includes a dependent test) https://github.com/sphinx-doc/sphinx/issues/11285 or make a separate "summary" issue ? (so that we know which are the ones to fix / that were already fixed)

**Comment by marxin** [comment]
Sure, good point. Do you have any other tests that have a global context dependency?

**Comment by picnixz** [comment]
Well, just running `python -m tox -e py310 -- tests/test_ext_autodoc*` would yield more failures but I don't know which test is dependent on which. I found the dependencies by explicitly testing different pairs (in the order they were specified when running `python -m tox -e py310 -- tests/test_ext_autodoc*`).

**Comment by marxin** [comment]
I see, I can confirm that as well with `pytest tests/test_ext_autodoc.py --random-order`. Can you please work on that :P ?

**Comment by picnixz** [comment]
> I see, I can confirm that as well with pytest tests/test_ext_autodoc.py --random-order. Can you please work on that :P ?

Well, I wonder actually about the way to patch this thing. Either we patch it by "cleanly" resetting things up, or we modify the flow of `do_autodoc` in the tests so that every autodoc test is independent. That's why I created #11285 in order to know which direction would be the best. Because I highly suspect that this is not the only test that has dependencies and that the whole testing flow should be revised.

**Comment by AA-Turner** [comment]
> Either we patch it by "cleanly" resetting things up, or we modify the flow of `do_autodoc` in the tests so that every autodoc test is independent.

I'm not entirely what the two options are here, but I think philisophically we should try and eliminate implicit state between tests. I think every test *should* be independent, but if it makes the tests take much longer, perhaps we make any state that is needed explicit via module-level setup or fixtures etc?

A

**Pull request merged**
