### PR TITLE
Add missing trailing space in italian translation

### PR DESCRIPTION
**Pull request by lelit**

### CODE REVIEW

**Comment by tk0miya** [comment]
LGTM!
Could you rebase this into stable branch please?

**Comment by tk0miya** [comment]
Note: I just updated the master translations on transifex. It will be applied to next major release.
https://www.transifex.com/sphinx-doc/sphinx-1/dashboard/

**Comment by lelit** [comment]
I'm not sure to understand your note... do you mean that you prefer me doing the fix through transifex, or simply redo the commit on top of your current stable branch?
In the meantime, I did the latter [here](https://github.com/lelit/sphinx/commit/624f2fe59c522eb0f9662176acb96e5261c40426). If that's fine, should I open another PR?

**Comment by tk0miya** [comment]
Ah, sorry for confusing.

Now we use two ways to manage translations.
The one is transifex. It is used to translate messages on master branch and it will be used in next major release (at this moment, v1.5).
The another one is .po files on stable branch. It is used for stable release (v1.4 series).

The note I commented means that I updated the translations on transifex.
So please open another PR to stable branch? It will be reflected to next stable release (v1.4.9).

Thanks,

**Comment by lelit** [comment]
Ok, see #3146.

**Comment by tk0miya** [comment]
Thanks,
I'll take a look.

**Comment by lelit** [comment]
Just to be sure, will the change popup also in 1.5, or should I learn how to use transifex and reapply it there?

**Comment by tk0miya** [comment]
I already fixed the translation in transifex. So you don't need to learn transifex.
Thanks

**Pull request closed without merging**
