### PR TITLE
Drop python 3.3 support

### PR DESCRIPTION
**Pull request by tk0miya**
@shimizukawa This PR includes what you said once. Please check this please.
And I want to ask you we also drop py26 at same time or not.

### CODE REVIEW

**Comment by willingc** [comment]
@shimizukawa @tk0miya PR looks good. Do you wish to drop on the napoleon extension as well? https://github.com/sphinx-doc/sphinx/blob/2b60fc202795d5351e13a6da98b4d046fe0c3be8/sphinx/ext/napoleon/__init__.py#L419

**Comment by tk0miya** [comment]
@RobRuana What do you think? I think updating the condition willingc pointed is not important in this case.

**Comment by RobRuana** [comment]
I agree, I do not think the condition needs to be updated. The condition doesn't **require** python 3.3. It's just saying that the feature it is looking for (the `__qualname__` attr) first became available in python 3.3.

**Comment by tk0miya** [comment]
ping @shimizukawa .
If there are no comments within a days, I will merge this first.
Then, I will file another issue for py26.

**Comment by tk0miya** [comment]
Ah, sorry. I've forgotten to write my opinion.
I don't have a strong opinion about dropping py26. So both are okay.

**Comment by shimizukawa** [comment]
Python 2.6.9 is the final release of Python 2.6.x series, that was release at October 2013.
https://www.python.org/dev/peps/pep-0361/

IMO, 2.6 is old enough, so I don't think that it requires active support.

**Comment by tk0miya** [comment]
@shimizukawa Thank you for comment!
Okay, I will post new PR for py26 later.

**Comment by bboe** [comment]
Hi, while I understand python 3.3 is old and not heavily utilized (~1% in my package's case), I'm simply curious if there is any specific feature that sphinx utilizes that python 3.3 doesn't support. I'm considering removing python 3.3 support myself if there's a good reason to.

**Comment by shimizukawa** [comment]
It is to save time. We do not care about Python-3.3 in every case, such as implementation, maintenance and support.
Sphinx may still work with Python-3.3, but it is not supported.

**Pull request merged**
