### PR TITLE
logging: Add a configuration option for disabling certain warnings.

### LINKED ISSUE #1895: There should be an easy way to disable certain warnings
Within my docs I use a few nonlocal images since they're automatically being generated by remote systems, and right now Sphinx warns me every time about this:

```
../README.rst:None: WARNING: nonlocal image URI found: https://travis-ci.org/WoLpH/mt940.png?branch=master
```

To have my docs automatically tested I generally run sphinx-build with `-W`, but this makes it difficult to do that.

### PR DESCRIPTION
**Pull request by cfelder**
fixes: #1895

### CODE REVIEW

**Comment by shimizukawa** [comment]
LGTM, waiting a travis result.

**Comment by ben-albrecht** [comment]
Any progress on this?

**Comment by lehmannro** [comment]
I have a high-level concern with this:  There are currently almost no configuration values that work per-file and if they do, they have a clear rationale to do so.  My fear is that this is going down a slippery slope:  If this is configured per-file, why not have everything per-file?  And then Sphinx becomes a giant pile of nested for loops, where maybe other measures such as intersphinx would've been better.

Could you maybe do some explaining why this is absolutely necessary?  _nonlocal URIs_ do not entirely convince me — this could just be a single configuration value, say `warn_nonlocal_uris`.  (Or the warning could be removed altogether and be replaced by a downloader, that automatically fetches nonlocal references for builders such as LaTeX where embedding is not possible.)

**Comment by tk0miya** [comment]
Thank you for suggestion.
Now, we implemented another warning suppression feature by #2346.

**Pull request closed without merging**
