### PR TITLE
Allow to choose Janome for Japanese splitter.

### PR DESCRIPTION
**Pull request by mocobeta**
I would like to support Janome as  Japanese splitter. 

Janome is a Japanese morphological analysis engine written by pure Python.
https://pypi.python.org/pypi/Janome

### CODE REVIEW

**Comment by shimizukawa** [comment]
Thanks for the PR! 

It seems test is failed, however it isn't your issue. Maybe SQLAlchemy-1.0.0 release (2 days ago) is related.

**Comment by shimizukawa** [comment]
Memo: #1853 is related to this PR.

**Comment by shimizukawa** [comment]
LGTM!
I'll resolve conflicts and merge by hand.

**Comment by mocobeta** [comment]
Thank you for merging. It will be nice if the three splitters (default tinysegmenter, mecab-python, janome) are decoupled from Sphinx core. I'll try to create extension(s) to switch those.

**Comment by shimizukawa** [comment]
Thanks! By #1853, now search option has a pluggable interface for custom splitters. Please try it.

**Comment by shimizukawa** [comment]
IMO, we should have least one splitter and I think tinysegmenter should be stayed as bundle.

**Pull request merged**
