### PR TITLE
fix #2336 autosummary imported members

### LINKED ISSUE #2336: autosummary with toctree always lists imported members
I continue to have the problem which I tried to describe in #2144. At that time there was some hassle because my patch caused problems elsewjere. Opening a new ticket, this time with a (hopefully) clean patch. It is inspired by 
http://stackoverflow.com/questions/25405110/sphinx-autosummary-with-toctree-also-lists-imported-members and the solution described there. The patch is against today's master from github.
[20160218.txt](https://github.com/sphinx-doc/sphinx/files/136248/20160218.txt)

### PR DESCRIPTION
**Pull request by lsaffre**
This fixes #2336

### CODE REVIEW

**Comment by shimizukawa** [comment]
Can you add a test case for this change?

**Comment by shimizukawa** [comment]
Ah, OK. `generate_autosummary_docs` have no test. So, now I merge this.

BTW, I think this is a "incompatible change" and this avoid imported class/function object even if it is intended. IMO, new default behavior is OK, however we should have a option for keeping previous behavior.

**Comment by lsaffre** [comment]
OK, so I don't continue diving into the Sphinx test suite (which is very
interesting to explore, but I have also other things to do ;-)

Yes, an option would be good, it should be settable at least in the
autosummary directive, and maybe also in the conf.py

**Comment by shimizukawa** [comment]
`--imported-members` options has been added.  4ece70109361ed

**Comment by dopplershift** [comment]
So how can I get the functionality of `--imported-members` if I was using `autosummary_generate` in `conf.py` before? I've tried running `sphinx-autogen -i`, and while it does some of the work, it doesn't seem to run recursively (generating autosummary pages for the imported members themselves) like I would like. Any help on restoring what worked with 1.5.6 would be very helpful.

**Pull request merged**
