### PR TITLE
latex: use in sphinx.sty \SPX or \spx@ prefix systematically

### PR DESCRIPTION
**Pull request by jfbu**
Also, rename some environments to start with SPX.

some exceptions: the macros in sphinx.sty starting with \py@, or \DU, or
\PYG as well as \ifsphinxpdfoutput and \sphinxAtStartFootnote have been
left as is. Also the literal-block environment which is removed in
another PR is left as is.

these changes such as \strong -> \SPXstrong, \code -> \SPXcode,
\titleref -> \SPXtitleref (fixing a memoir class incompatibility) etc..
will unavoidably break projets which used `.. raw:: latex` directive
or `'preamble'` key to customize them. But in the long run, using a
prefix is the best way to ensure user can add custom packages or own
latex code.

The command find . -name '*.sty' -exec grep -l \\spx@ {} \; and
similarly with \\SPX have been executed in TeXLive 2015 and 2016 root
latex repertories to make sure no other packages use \SPX or \spx@ as
prefixes.

### CODE REVIEW

**Comment by jfbu** [comment]
The find command in the commit message is

```
find . -name '*.sty' -exec grep -l \\\\spx@ {} \;
```

with four backslashes.

**Comment by jfbu** [comment]
by oversight I already included in this the PR #2669 related to `\includegraphics`, but this will facilitate merge if the latter is treated earlier

**Comment by tk0miya** [comment]
LGTM! This will be fixed #2629.

BTW, are abbreviated prefixes preferred in LaTeX packages? In python, I've usually used non abbreviated prefix to the name of functions and classes. There are only 3 characters differences. So I prefer to use full-spelled, more clear name. But It's ok if the abbreviation is common sense for TeX/LaTeX users.

**Comment by tk0miya** [comment]
In addition, "incompatible changes" entry is needed.
I know some users override some macros to change text styles.

**Comment by jfbu** [comment]
For macros like `\spx@colorbox` (currently `\Sphinx@colorbox` which are a priori only for internal use, and do not appear as is in latex document, it is common that a package uses abbreviated prefix. Already sphinx.sty does it with `\py@` prefi or `\DU` prefix. I have no preference between `\spx@colorbox` or `\sphinx@colorbox`, but the former makes shorter lines. The `\Sphinx@colorbox` now disturbs me a little, but that's psychological.

Aside: `\py@HeaderFamily` is something the user might want to change, like `TitleColor` etc.., probably there should be rather a `\sphinxSetHeaderFamily` macro. 

Typical LaTeX package do not worry too much about prefixing public macros, they usually don't have many, because they interface with the user via one or two environments, say `longtable`. It is only a matter then to choose a name which is not too likely to conflict. The customization can then be organized with only one macro handling key=value, as for example `\hypersetup` does.

In the case of sphinx.sty, I really hesitated mainly for `\code`, `\email`, `\titleref`,  `\crossref` ... which are likely to cause conflicts as well as `\version`, `\shortversion`, `\releaseinfo` which have setters `\setversion`, etc.. I opted for `\SPXversion`,  because `\sphinxversion` looked like the version of Sphinx, not the version of the project. But I made the PR to discuss it. By the way, these customization possibilities do not appear documented. I agree that my proposal `\SPX` does not look good at all there.

It does not look good either in environment names like productionlist, fulllineitems. One may argue that there is no need to prefix these environment names, it is hard to draw the thin line between words which are more likely than others to make conflict. Using `sphinxfulllineitems` has the advantage to solve problem.

But the big problem is indeed with `\strong`, `\code`, `\crossref`, ... that people may have customized.

Here is one option:  let latex.py write `\sphinxcode` in document, but define `\sphinxcode` in sphinx. sty to be wrapper of  unmodified current `\code`. This maintains 100% compatibility with existing projects with some LaTeX customization of `\code`,  or `\strong`, ...

Then add a Boolean option like `macrosuseprefix` which is documented to be used in case some conflict arise with a user added latex package, or document class. If set, the LaTeX writer will insert `\sphinxuseprefixtrue` at top of preamble. The sphinx.sty would check status of this boolean, and if set it will not at all define `\code`, `\titleref`, ... but only define `\sphinxcode` etc... (in this PR, I used `\SPXcode` but I agree it does not look good).

The documentation would say : "style macros are `\sphinxcode` etc... but for backwards compatibility you can still customize in your preamble `\code` macro with same effect;  with `latex_macrosuseprefix = True` (default False) you can tell Sphinx not to define `\code`, `\titleref` etc... macros -- to be used in case of conflict with added latex packages."

As it takes time to adjust all tests etc... we should informally agree on what to do matters of prefix before finalizing this PR ... I agree with replacement  `SPX->sphinx` in the current PR.

**Comment by jfbu** [comment]
I have added a commit which is much less aggressive in renames.
- leaves environments fulllineitems etc... untouched
- leaves macros \release, \authoraddress, etc .. untouched
- by default, still defines, `\strong`, `\code`, `\titleref` etc... but as these are more likely to cause conflicts (e.g. #2629), provide a boolean option to only define them with extra `\sphinx..` prefix.

With this commit there should be no backwards incompatibility, people can still customize the text styles `\strong`, `\code`, `\crossref` etc.. to their liking.

Also, I have opted for `\sphinx`, not `\Sphinx` prefix for public macros, and `sphinx` prefix for environments. I have made the shadow box customizable with public names `\sphinxshadowsep` etc...

**Comment by jfbu** [comment]
The CHANGES will need to be updated. I need some help with how to treat in latex.py an option like `latex_macroswithprefix`, with default False for compatibility, which if set to True in conf.py will result in `\sphinxalsonoprefixmacrosfalse` at top of produced `.tex` file. In that case sphinx.sty does not define text style macros with names like `\titleref` but only `\sphinxtitleref`.

**Comment by jfbu** [comment]
The current status is possibility for merge into stable as it fixes #2629 and does not introduce any breaking change. All in all, this PR
- adds some order in sphinx.sty's private macros by using `\spx@` prefix,
- uses lowercase `sphinx` as prefix to recently defined environments,
- regarding text styling macros, leave them usable under original short names, but add configuration option in case some clash with packages or classes arise,
- make the sphinxShadowBox for topics customizable via public lengths

I have also removed some `\includegraphics` changes which belongs more to #2672.
Still need to update CHANGES.

**Comment by jfbu** [comment]
If merge ok at some point, I will squash commits for cleaner history.

**Comment by jfbu** [comment]
I am closing this, because I have finally rebased it on stable at PR #2675 (with removal of some material already contained in other PR's). The initial commit did more extensive changes of macro names, with the idea to make conflicts impossible with user added latex packages. But as long as nobody complains perhaps it is not that needed. I have thus concentrated on the text styling macros which have names looking more likely for conflict. Backwards compatibility is fully maintained at #2675.

**Pull request closed without merging**
