### PR TITLE
setup.cfg: Ignore .venv

### PR DESCRIPTION
**Pull request by stephenfin**
Subject: Add a 'pep8' target and ignore '.venv' directories

### Feature or Bugfix
- Refactor

### Purpose
- Make pep8 easier to run and more useful

### Detail
- N/A

### Relates
- N/A

### CODE REVIEW

**Comment by peterjc** [comment]
Adding ``.venv`` to the ``.gitignore`` makes sense to me.

The tool flake8 tests more than just PEP8 compliance - it runs pycodestyle (PEP8 compliance) plus pyflakes, and mccabe - and can do far more with additional plugins. So I don't understand why you'd want to change the Tox environment names like this.

**Comment by stephenfin** [comment]
> The tool flake8 tests more than just PEP8 compliance - it runs pycodestyle (PEP8 compliance) plus pyflakes, and mccabe - and can do far more with additional plugins. So I don't understand why you'd want to change the Tox environment names like this.

This is all true. However, I consider *pep8* to be a synonym for general *code quality* within the Python ecosystem. I guess it's for this reason that `pep8` is a such a commonly used tox target for many Python projects. I haven't removed the `flake8` target (and don't intend to), but I'd like to help folks like me whose muscle memory causes them to type `tox -e pep8` by default every time.

**Comment by peterjc** [comment]
Thanks for explaining.

If you are used to running ``tox -e pep8`` in other projects, I can see why you might want to define a Tox alias ``pep8`` for the existing ``flake8`` environment here.

See also the renaming of the command line tool ``pep8`` to ``pycodestyle`` to avoid confusing it with the document and standard PEP8.

(Let's wait and see what the Sphinx team think)

**Comment by shimizukawa** [comment]
Actually, I don't know what is standard, and I've never seen `pep8` as a tox target then I researched a few projects.

--------------

flake8

* https://github.com/PyCQA/flake8/blob/master/tox.ini#L33
* tox target is `flake8`

tox

* https://github.com/tox-dev/tox/blob/master/tox.ini#L33
* tox target is: `style`

pip

* https://github.com/pypa/pip/blob/master/tox.ini#L30-L46
* tox target is `lint*`

django

* https://github.com/django/django/blob/master/tox.ini#L32
* tox target is `flake8`

-------------------

As a result of this, I don't think `pep8` is the common sense for now.

Of course, this is only a part of the famous package. BTW, if I change the name from now on, I may choose `style` as a name independent of a particular tool name or scope of pep 8.

**Comment by tk0miya** [comment]
-0; I don't have strong opinion, but I also don't know that. so there are no reason to change.

**Comment by stephenfin** [comment]
> Actually, I don't know what is standard, and I've never seen pep8 as a tox target then I researched a few projects.

It's used all through the OpenStack ecosystem, which is no small player in Python-land :smile: This is where I'm used to encountering it.

> As a result of this, I don't think pep8 is the common sense for now.
> 
> Of course, this is only a part of the famous package. BTW, if I change the name from now on, I may choose style as a name independent of a particular tool name or scope of pep 8.

Suggesting that it shouldn't become the main target is fair. However, can we add it as a simple alias? I've modified both the commit message and commit to remove suggestions that `pep8` replace `flake8` in the future. It's a small change, but this has tripped me up enough times that I'd like to simply resolve it now.

**Comment by peterjc** [comment]
Although I would include a comment in the Tox file stating that the definition is deliberately just an alias, the new commit is much clearer, and I have no objection.

(Personally I have used ``style`` as the Tox environment name for these kinds of check)

**Comment by tk0miya** [comment]
-0; again, I love well-known python's slogan; TOOWTDI. So I feel no alias is needed. BTW, renaming to `style` environment is ok to me.

**Comment by stephenfin** [comment]
> -0; again, I love well-known python's slogan; TOOWTDI. So I feel no alias is needed. BTW, renaming to style environment is ok to me.

OK, cool. I've dropped that patch, which means only the patch to ignore `.venv` from flake8 is include. We can do the `style` target at a later date :smile:

**Comment by tk0miya** [comment]
Thanks, merged.

**Pull request merged**
