### PR TITLE
update latex.rst (``LaTeX customization`` chapter in the docs)

### PR DESCRIPTION
**Pull request by jfbu**

### CODE REVIEW

**Comment by tk0miya** [comment]
Almost LGTM. but style-check warns for TABs. Please check it.

**Comment by jfbu** [comment]
arrgh! these TABs were put there by a mis-configured Emacs reST mode under which I suffer here and I forgot to transfer the settings from my personal laptop. And indeed I forgot the `make style-check` sorry for inconvenience.

**Comment by tk0miya** [comment]
Don't mind :-)
Travis CI checks styles automatically. So you don't need to run them locally.

**Comment by jfbu** [comment]
Thanks @tk0miya as always ! now merging.

**Pull request merged**
