### PR TITLE
classifier of glossary terms can be used for index entries grouping key.

### PR DESCRIPTION
**Pull request by shimizukawa**
The classifier also be used for translation.
IMO this is a experimental feature of sphinx-1.4. For now I don't care about non-glossary-term index entries. Actually I have no use cases about "specifying grouping key for non-glossary-terms".

Please see also a change of para.rst.

### CODE REVIEW

**Comment by shimizukawa** [comment]
Let me introduce usages.

# Case 1. non-translation document.

``` rst
Under the glossary directive
=============================

.. glossary::

   Term 3 : D
      description 3

   Term 4 : E
   Term 5 : e
      description 4 and 5
```

This converted as:
image

And index page is generated as:
image

**Comment by shimizukawa** [comment]
# Case 2 : translation

locale/ja/LC_MESSAGES/index.po

``` pot
#: ../../index.rst:18
msgid "Term 3 : D"
msgstr "単語3 : た"

#: ../../index.rst:20
msgid "description 3"
msgstr "説明3"

#: ../../index.rst:21
msgid "Term 4 : E"
msgstr "単語4 : た"

#: ../../index.rst:22
msgid "Term 5 : e"
msgstr "単語5 : ん"

#: ../../index.rst:24
msgid "description 4 and 5"
msgstr "説明4と5"
```

This effects to index.html as:
image

And index page is generated as:
image

**Comment by tk0miya** [comment]
LGTM.

BTW, why the code for indices is placed on `sphinx.environment`?
It would be much better if moving them into `sphinx.domains.std`.

**Comment by shimizukawa** [comment]
> BTW, why the code for indices is placed on sphinx.environment?
> It would be much better if moving them into sphinx.domains.std.

I think so too.
Another time, we should restructure whole of sphinx code (maybe on sphinx-2.0)

**Pull request merged**
